### ISSUE TITLE
caching of importScripts()-scripts

### ISSUE THREAD

**Issue by sicking** [slightlyoff/ServiceWorker#106]
How is caching supposed to work of importScripts-loaded scripts?

Normally any network requests coming from a service worker is supposed to not trigger any fetch event in the worker itself, but rather result in network requests. If the user is offline, that will often result in a failed request.

However if a network requests fails during importScripts(), generally the service worker will not work at all.

I guess the implementation can be extra aggressive about caching resources fetched through importScripts() calls in a service worker.

The obvious answer here is ES6 modules. Even if we just had the static import syntax that might be enough to carry us through until full ES6 support is deployed in browsers.

But is it ok to have a hard dependency on event the ES6 import syntax?

**Comment by slightlyoff** [comment]
hey all,

@wanderview and @tabatkins pointed out on IRC that we haven't closed this off and there was some confusion about what behavior Mozilla should implement. After a discussion, it seems we need to get something like @jakearchibald's language in.

@jungkees : do you agree with that?

**Comment by jungkees** [comment]
> it seems we need to get something like @jakearchibald's language in.

Agreed. Let me put this item in my queue.

Spec'ing this in HTML would be more accurate than monkey patching somehow. @Hixie Is there any way I can make a PR or something for this and some of the stuffs that need hooks between Service Workers spec and HTML?

**Comment by annevk** [comment]
@jungkees I recommend filing a bug on HTML and adding a monkey patch in service workers (that is clearly identified as such) to aid implementers. Then once HTML is fixed the monkey patch can be turned into more proper layering.

**Comment by jungkees** [comment]
@annevk Okay, I'll do it that way.
