### ISSUE TITLE
Define security policy

### ISSUE THREAD

**Issue by alecf** [slightlyoff/ServiceWorker#113]
We need to define the security policy more concretely. This has lead to a long discussion on the chrome side:

https://codereview.chromium.org/27278002/#msg23

We need to define the restrictions between the calling document, the pattern, and the script url in terms of what kinds of origins are compatible with what.

**Comment by annevk** [comment]
Yeah I think this is mostly sorted in other issues now and is specified in actual specifications to some extent.
