### ISSUE TITLE
Prefetch/prerender & Client id

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/ServiceWorker#210]
2 related questions from Joey Hurst:

 * Does the SW get a crack at pre-render requests?
 * If so, what's the `client`?

Prescanner requests in loading a document are easy (yes, the SW sees them).

Prerender is harder. No header distinguishes the fetch: https://developers.google.com/chrome/whitepapers/prerender

It's also not clear that these requests would even get sent to the SW of the pre-rendered document. Should they? If they do, what's the client? Do we need to add a flag to the fetch event to help distinguish it (seems like we should)?

**Comment by KenjiBaheux** [comment]
@slightlyoff @jakearchibald @annevk 

Could we use the Request's context to indicate that this is for prerendering purpose?
Anne said prerender was a valid context in this [comment](https://github.com/slightlyoff/ServiceWorker/issues/318#issuecomment-50446134)

A Service Worker might want to make different decisions for prerendering:
 - make sure side-effects (e.g. logging you out) are avoided
 - minimize resource contention with a different loading strategy

**Comment by annevk** [comment]
@KenjiBaheux for the request of the document I suppose. But I doubt you'd want `context` to be `prerender` for the images inside such a document. Perhaps `prerender` and such should be another axis altogether?

**Comment by igrigorik** [comment]
@annevk +1. We should report "prerender" context on any fetch that was initiated by `<link rel=prerender>`, and subsequent fetches that may be triggered by the prerendered resource itself should advertise the context that triggered it... e.g. HTML request for a prerender has the context of "prerender", but script/style/image/etc fetches initiated during prerendering should advertise their usual contexts.

**Comment by annevk** [comment]
@igrigorik but should we still advertize somehow that they are fetched for prerendering? E.g. through a prerender flag or some such. SW could use that as priority hint of sorts.

**Comment by KenjiBaheux** [comment]
@annevk +1, we need both bits of info.

I re-read the [prerendering documentation](http://www.chromium.org/developers/design-documents/prerender). 

I now believe that one can already tell if a request was part of a prerendering scenario by looking at the [page visibility](http://www.w3.org/TR/page-visibility/) of the associated Client (i.e. fetchEvent.client.visibilityState == "[prerender](http://www.w3.org/TR/page-visibility/#pv-prerender)"). 

Would that be enough?
If affirmative, then there doesn't seem to be any spec ask :)

**Comment by annevk** [comment]
So the initial fetch would not have a client, but would have `context` set to `prerender`, and subsequent fetches would have a client and `context` set to the expected value. Seems okay.

Not sure that works for `preload` though. Does that still exist?

**Comment by igrigorik** [comment]
@KenjiBaheux combination of `context == "prerender"` (first request) and `fetchEvent.client.visibilityState == "prerender"` (subsequent requests) is definitely sufficient. :+1: 

@annevk yes, preload is a thing -- implementation underway in Blink. For fetches initiated via rel=preload, I'd expect `context == "preload"`, which.. I believe, should not be a problem? We just might need to add "preload" to the Fetch context table.

**Comment by annevk** [comment]
Does `preload` not load further subresources?

**Comment by igrigorik** [comment]
@annevk short answer: no. long answer: current spec would allow that via `loadpolicy` that provides an equivalent to prerender, but I think we're going to drop that in favor of distinct: preload, prefetch, prerender rel's... Which, reminds me: prefetch should also have `context=="prefetch"`.

**Comment by annevk** [comment]
So if `prefetch` is equivalent to `prerender` except for having a client, what @KenjiBaheux listed above won't work.

**Comment by igrigorik** [comment]
@annevk they're not. prefetch fetches the resource but it wouldn't "execute" it - i.e. for HTML file it wouldn't trigger fetches for any subresources declared within it. Same applies to preload, the only difference being: preload is used to fetch resources for current nav context (i.e. high priority), whereas prefetch is used to fetch resources for next (likely) navigation context. Hope that makes sense.

**Comment by jakearchibald** [comment]
@igrigorik closing this here, as it's for resource hints to define how fetch is called. Feel free to reopen if I'm wrong
