### ISSUE TITLE
Interacting with HTTP/2 push

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#215]
HTTP/2 allows additional resources to be pushed with a response. This is something we may want to expose to SW.

This will probably need a new event, something like…

```js
self.onpushresponse = function(event) {
  event.response;
  event.request;
};
```

This would be fired when the request portion is received and we're at the start of the body (same as when `fetch` resolves).

This allows the developer to add the request/response pair into a cache. It response should be abortable too, we should probably have `.abort` on response objects.

The network can also abort the request, i.e. if it matches something already in the HTTP cache. Because of this, we probably need a way for the SW to "claim" the pushed response. Maybe this is as simple as `preventDefault`.

(I don't think we need this for the first version of the spec, but we should ensure we don't do anything that gets in the way)

/cc @willchan

**Comment by annevk** [comment]
Closing this. Once there's a concrete plan we can open an issue. Now this issue just makes it less clear what is left to be done on the specification.

**Comment by rektide** [comment]
Not sure entirely what relation this has to push support in fetch but, but that issue is https://github.com/whatwg/fetch/issues/51 . Also there's https://github.com/w3c/ServiceWorker/issues/796 which is a very specific use case of rejecting pushes.
