### ISSUE TITLE
Header for dissalowing SW registration (and implicitly removing SWs)?

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/ServiceWorker#224]
Pending discussion of CSP policy, it seems as though we should either craft the CSP support in such a way as to dissalow registration of SW's based on header (e.g., so that rawgithub.io can continue to function) and potentially unregister existing SW's when it encounters such a directive.

/cc @jakearchibald @mikewest

**Comment by jakearchibald** [comment]
@mikewest Am I right in thinking the CSP that prevent service worker reg is `child-src`? Reopen if not.
