### ISSUE TITLE
Add Quota Management APIs to the SW Global Execution Scope

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/ServiceWorker#229]
Per discussion with @kinu, the SW spec should take a dependency on [Quota Management](http://www.w3.org/TR/quota-api/) in preparation for an extension event that communicates storage pressure and pre-eviction information to the application.

**Comment by annevk** [comment]
Closing this as this is now being discussed in other places. E.g. https://wiki.whatwg.org/wiki/Storage and https://github.com/slightlyoff/StorageDurability/issues
