### ISSUE TITLE
Resources shared across documents controlled by different service workers

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#244]
Currently Fetch (at least as defined in HTML) allows the user agent to share fetching of a resource across e.g. document or even origin boundaries. So if the user has http://example/mail/ and http://calendar/ open and they both fetch /test that can be shared.

I guess if both are controlled by a service worker this is impossible? Or if either?

**Comment by jungkees** [comment]
@annevk We started this discussion in the `navigator.connect` issue tracker: https://github.com/mkruisselbrink/navigator-connect/issues/22. The basic idea there is to introduce a _fall through request_ concept that eventually dipatches a `fetch` event to the cross origin service worker that opted to serve those events.

Let's discuss this topic there. Closing.

**Comment by annevk** [comment]
No that is something else. Imagine the user having `https://example/` open twice. Both load `/test`. Does that cause one or two events?

**Comment by jungkees** [comment]
Getting just a single event for multiple requests means there must be some additional logic to aggregate them in Fetch layer I guess. Sharing resources at some point (i.e., network layer cache or SW cache for authors) is a must for sure, but I'm not sure how much benefit we can get from aggregating requests.

**Comment by annevk** [comment]
I'm leaning towards only at the network level and even that I'm not putting in the specification. But I'm somewhat curious if implementers I have not talked to explicitly have different ideas.

**Comment by wanderview** [comment]
> No that is something else. Imagine the user having https://example/ open twice. Both load /test. Does that cause one or two events?

I would expect that to cause two events.

**Comment by annevk** [comment]
Closing this for now. It seems everyone agrees that sharing is unlikely to happen and if it does it should not be observable (easily).
