### ISSUE TITLE
"I want to make an image request"

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#279]
Browsers make requests differently depending on their context.

http://jsbin.com/yacar/1/quiet - here I'm request the same url, one using XHR and one using `<img>`. The browser cannot dedupe these as they have separate `Accept` headers.

When using `fetch()` and populating caches, it'd be useful to ask the browser to make the request as if it were for an "image" or a "font". These are terms we currently use for `fetchEvent.context`.

I propose we move `.context` onto `Request` objects, and allow it to be set in constructor. The initial value of "context" will affect headers in a way that's UA-specific (eg, Chrome Accepts image/webp, Firefox does not). Any user-set headers will take priority.

```js
var req = new Request({
  url: '/whatever.png',
  context: "image"
});

req.headers.get('Accept') == "image/webp,*/*;q=0.8"; // in Chrome
```

**Comment by annevk** [comment]
I'm discussing this idea with @igrigorik in https://github.com/w3c/preload/pull/17#issuecomment-89366442 at the moment. It's still not entirely clear to me what the division of labor needs to be, but hopefully once we have the answers to the questions in that thread, we can open some issues against https://github.com/whatwg/fetch to add new features.

**Comment by annevk** [comment]
Closing this in favor of https://github.com/whatwg/fetch/issues/43.
