### ISSUE TITLE
Support range request in fetch() and cache

### ISSUE THREAD

**Issue by shacharz** [slightlyoff/ServiceWorker#288]
I would like to be able to listen to all kinds of http requests done by the page:
img,audio,video tags. so I can either retrieve them from local cache, get them from a server or several servers, manipulate the data if needed, merge it back together return the response to the page.
This is specifically interesting and challenging, I believe, in the context of range requests done by the video tag.

**Comment by annevk** [comment]
It's still not clear to me what actually needs solving here. `fetch()` provides full control over range-related headers as far as I can tell so this should all be feasible.
