### ISSUE TITLE
Make service workers use ES strict mode

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#294]
That way we can easily migrate to using the Module non-terminal later rather than needing an opt-in for that as other worker contexts likely do. Less mode switches = good.

See https://www.w3.org/Bugs/Public/show_bug.cgi?id=22700#c22 for more details. /cc @dherman

**Comment by mattto** [comment]
FYI marking the crbug (https://code.google.com/p/chromium/issues/detail?id=415443) WONTFIX for now, as it seems consensus is not clear and we already shipped so SWs are used in the wild. We can reopen if the spec changes.

**Comment by annevk** [comment]
So I guess we should just give up on this then. Sad as it is. And instead introduce something for module-based workers for all worker-types together when the time is right.
