### ISSUE TITLE
Client versus resource for workers, frames, etc.

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#345]
While the intent of the explainer was that iframes are 'navigate' and handled by a potential service worker in the domain of the iframe, the spec is unclear about this. It uses a 'navigate' context to decide which registration to associate with a request, but in the fetch spec, iframes have a 'child' context.

**Comment by jungkees** [comment]
A service worker registration is selected upon a client request (https://fetch.spec.whatwg.org/#client-request). Anyone has concern about the list of contexts defined there?

**Comment by jungkees** [comment]
@annevk this part of the work is still in flux? Or can we settle on the current definitions?

**Comment by annevk** [comment]
I think I'm okay with what we have now.
