### ISSUE TITLE
Can Cache.add() committing at response resolution lead to duplicate requests?

### ISSUE THREAD

**Issue by gavinp** [slightlyoff/ServiceWorker#361]
Currently, cache.add() is described in the spec as being placed in the [[RequestToResponseMap]] when the response first resolves. There's no way to use cache.put() earlier than response resolution, since the spec doesn't permit passing a promise to the contructor for the response argument.

When the response resolves is somewhat implementation dependent; but it can be as early as when headers are received for the final, non-redirect response for the request; since the data is in a blob behind a promise, the response can be resolved before the full data is received.

Consider this duplicate load scenario:

1. A page loads foo.jpg, so we call add.
2. Another page loads foo.jpg. The cache still has no entry, so we call add.
3. The response from (1) resolves, so we store foo.jpg in the cache.
4. The response from (2) resolves, so we remove the cache entry created in (3), and store the new one in its place.

**Is this Race scenario desirable?** The underlying HTTP cache may save us here; in Chrome it's very likely that the two requests will join under the covers, but it's not guaranteed because cache control headers can block it.

Also of concern is that in (4) we are removing a response from the cache, before our replacement response is fully received. What if there's a network error?

In the HTTP cache, this is dealt with by locking a cache entry when the initial request is sent; the subsequent request will respect that lock.

**Comment by jungkees** [comment]
So now we settled on the behavior @wanderview suggested: https://github.com/slightlyoff/ServiceWorker/issues/361#issuecomment-48351750.

@wanderview do you still have a concern about https://github.com/slightlyoff/ServiceWorker/issues/665? Can I close both issues?

**Comment by wanderview** [comment]
> So now we settled on the behavior @wanderview suggested: #361 (comment).
>
> @wanderview do you still have a concern about #665? Can I close both issues?

Implementing that behavior sounds reasonable to me, but I think perhaps something is still missing.

For example, I don't see where the incumbent record is cleared for a fetch record when the new response body completes.  It seems the old incumbent should be dropped then.  Am I missing it?

**Comment by wanderview** [comment]
Also, can you clarify if Cache.put() is intended to implement stale-while-revalidate as well?  I think step 14.1 means it does not implement stale-while-revalidate, but I'm not sure:

  "Wait for either end-of-file to have been pushed to responses[0]'s associated response r's body or for r to have a termination reason."

**Comment by wanderview** [comment]
Actually, that same quote is used for addAll() as well as put().  That suggests to me that we will wait for new the newly inserted Response to always completely download before proceeding.

Is it the intention to require add()/addAll()/put() to wait tor resolve until the new Response is complete even if there is an existing incumbent response?

Sorry for my confusion.

**Comment by jungkees** [comment]
> For example, I don't see where the incumbent record is cleared for a fetch record when the new response body completes. It seems the old incumbent should be dropped then. Am I missing it?

[addAll()](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#cache-addAll) 6.4.2.2.1 waits until either the response's body completes or the stream's terminated. 6.4.2.2.3 replaces the old incumbent record with the successfully fetched fetching record whereas 6.4.2.2.2 performs the rollback.

> can you clarify if Cache.put() is intended to implement stale-while-revalidate as well?

Yes. As long as an incumbent record exists, matchAll() always returns the value even if the response argument to the `put()` method is still fetching the body. Step 14 of the `put()` method is basically doing the same thing with `addAll()`.

> Actually, that same quote is used for addAll() as well as put().

This is intended as addAll() and put() both deal with the fetching response object.

> That suggests to me that we will wait for new the newly inserted Response to always completely download before proceeding.

This is not the case. `matchAll()` always get the incumbent record if exists. The downloading bits are want-to-be-incumbent record for the next fetch event.

> Is it the intention to require add()/addAll()/put() to wait tor resolve until the new Response is complete even if there is an existing incumbent response?

Yes. Incumbent record has higher priority. And the fulfillment of the cache-adding methods (add/addAll/put) guarantees we have the incumbent record fully ready for the request. Holding the promise resolution until it completes also solves the issue posed in https://github.com/slightlyoff/ServiceWorker/issues/665's OP.

> Sorry for my confusion.

Not at all. Sorry for having got back to the issue late.

**Comment by jungkees** [comment]
Closing. History: https://github.com/slightlyoff/ServiceWorker/issues/362#issuecomment-119092324.
