### ISSUE TITLE
When should implementations serialize caches?

### ISSUE THREAD

**Issue by gavinp** [slightlyoff/ServiceWorker#362]
Currently, cache.add() is described in the spec as being placed in the [[RequestToResponseMap]] when the response first resolves. There's no way to use cache.put() earlier than response resolution, since the spec doesn't permit passing a promise to the contructor for the response argument.

When the response resolves is somewhat implementation dependent; but it can be as early as when headers are received for the final, non-redirect response for the request; since the data is in a blob behind a promise, the response can be resolved before the full data is received.

When should a Cache API implementation be fully committed to disk?

A common pattern of use is likely to be that a ServiceWorker creates a new cache, loads a series of resources in to it, and moves the new cache on top of the existing cache as a replacement. Example:

```javascript
var newCache = caches.add("newOfflineCache");
var toLoadRequests = ...;
Promise(toLoadRequests.map(newCache.add, newCache)).then(function() {
  return caches.rename("newOfflineCache", "OfflineCache");
});
```

But this rename isn't quite safe, is it? The requests are only guaranteed to have received headers, not bodies, and so if we do the rename, we risk partial/erroneous/missing responses in the renamed cache?

I am left with a few questions:
* When should implementations finalize serializing an entry to disk, so it is likely to be found in subsequent uses of that Cache?
* Should caches.rename() and others wait for all in-flight requests to reach this point before resolving?
* Why isn't this mechanism exposed as part of the Cache API?

**Comment by jungkees** [comment]
I think we finally settled on this behavior: https://github.com/slightlyoff/ServiceWorker/issues/573#issuecomment-67630115. (See also https://github.com/slightlyoff/ServiceWorker/issues/361#issuecomment-113444335). If there's no more concern, I'd be happy to close the related issues.

**Comment by jungkees** [comment]
Closing.
