### ISSUE TITLE
Should fetchStore.match reject if no match is found?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#374]
The current behaviour of rejecting has been questioned in #372.

**Comment by inexorabletash** [comment]
Did the `caches.match` spec change get reverted intentionally or unintentionally? The spec still has "Reject `p` with `NotFoundError` exception"

**Comment by wanderview** [comment]
> Did the caches.match spec change get reverted intentionally or unintentionally? The spec still has "Reject p with NotFoundError exception"

I believe it only does this if the cache name option is specified.  Its for not finding the specified cache.

**Comment by wanderview** [comment]
To clarify, I don't see any discussion above for this case:

```
caches.delete('myCache').then(function() {
  return caches.match(url, { name: 'myCache' })
}).then(function(resp) {
  // currently does not resolve undefined
}).catch(function(err) {
  // currently throws NotFoundError because myCache is missing
});
```

**Comment by inexorabletash** [comment]
Ah, you're correct. That line was (intentionally) not changed in jake's patch.

**Comment by jungkees** [comment]
Yes you're right.

> it only does this if the cache name option is specified. Its for not finding the specified cache.

is intentionally there.
