### ISSUE TITLE
Batch adding to a cache should fail if one request in the batch overwrites another

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#379]
```js
cache.add([
  '/hello/world/',
  new Request('/hello/world/', {
    headers: { "Accept": "blah/whatever" }
  })
]);
```

If the response to the first request does not vary on "Accept", it'll be overwritten by the second request and the transaction will fail. I'll fix this at the `.batch` level.

**Comment by jungkees** [comment]
[Batch Cache Operations](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#batch-cache-operations-algorithm) 3.3.2.3 meets this requirement. Closing.
