### ISSUE TITLE
[Exposed] annotations on InstallEvent an ServiceWorker make no sense

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/ServiceWorker#395]
`InstallEvent` has `[Exposed=ServiceWorker]`.  So its `.activeWorker` can only be accessed inside a ServiceWorker, fine.

But this attribute returns a `ServiceWorker,` and `ServiceWorker` has `Exposed=Window`.  So the methods/attributes of `ServiceWorker` are only accessibly inside a Window.

I have a hard time believing this is the desired behavior.  Either InstallEvent is exposed in Window, or ServiceWorker should also be exposed in non-Window scopes, I would think.

**Comment by jungkees** [comment]
`ServiceWorker` is now exposed to worker environments. Closing.
