### ISSUE TITLE
Possible ambiguity with "run these steps asynchronously"

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#403]
Spinning off of issue #396

This probably doesn't have practical impact on any implementation, so consider it low priority.

I'm wondering if "run these steps asynchronously" is sufficiently rigorous for a spec. To me, async just means run at some later time. The spec doesn't seem to require an ordering of the sets of async substeps. In fact, I don't see what prevents running two sets of async substeps concurrently.

Consider for example:
register();
register();

What ensures the first register's async steps run to completion, then the second register's async steps run?

This is especially tricky with steps like

> Wait until the Record {[[key]], [[value]]} entry of its [[ScopeToRegistrationMap]] where registation.scope matches entry.[[key]] is deleted.

The spec's intent is the first register runs until it hits the wait until step, then the second register runs until it hits the wait until step (rejecting the first register()'s promise which presumably aborts the first register()'s async steps). But AFAICT this kind of ordered run-to-completion is not spelled out anywhere.

**Comment by jungkees** [comment]
To synchronize algorithms, we introduced algorithm thread queues. And the global state processing part of Register has been moved onto the main thread. Closing.
