### ISSUE TITLE
Concerns about `cache.addAll` not filtering non-200 

### ISSUE THREAD

**Issue by tobie** [slightlyoff/ServiceWorker#407]
AppCache, despite all of its flaws, guaranteed all resources transactionally cached had a status of `200`.

For security reasons, `cache.addAll` can't give us these guarantees. Yet they-re critical to enable offline apps. Here are my concerns:

### scenario 1: dev isn't aware `cache.addAll` accepts responses with a status other than `200`
Consequence: Dev uses `cache.addAll` expecting all resources to be fully operational on a successful outcome of `cache.addAll`. Yet sometimes offline apps which have reported a fully successful install fail for odd and hard to debug reasons. Dev ends up finding out `cache.addAll` isn't _really_ transactional to the extent he expected it to be, vows to never use it again, blames W3C for all the things and moves to native.

### scenario 2: dev is aware `cache.addAll` accepts all kinds of responses
Consequence: "That's OK, he thinks, I'll build a transactional function using `fetch`, `put` and `promise.all` that works as expected." He then spends most of his days on Stackoverflow answering the questions of scenario 1 devs which don't understand why `cache.addAll` doesn't behave as expected; Writes a moderately successful library to fix SW issues; Gives a talk entitled "Service Workers are douchebags" and gets sued by the United Service Workers Union; blames W3C for all the things and moves to native.

**Proposed solutions:**

1. remove `cache.add` and `cache.addAll` completely,
2. Make filtering for a response status of 200 the default, throw on non-cors cross-origin request unless an `allowNonCors` option is present.
3. add a `filter` option to `cache.addAll` which is called with each request as first argument and allows to cancel the transaction (e.g. by throwing or returning false).

**Comment by jakearchibald** [comment]
@wanderview how do you feel about:

```js
cache.addAll(urls, {
  ensureOk: true
});
```

…that would fail if any response is opaque or `response.ok` is false for any response?

There's probably a better name for it.

**Comment by annevk** [comment]
@jakearchibald it seems if anything such a feature should be added to `Request`, not here.

**Comment by wanderview** [comment]
@annevk this seems like something saying "the result of request needs to be X", which is more a function of the Response consumer than the Request itself.

@jakearchibald thats fine with me.  I don't really have a strong opinion one way or another.  Whatever is nicest for devs.  (Sorry, that isn't very helpful.)

**Comment by annevk** [comment]
@wanderview how can it be a property of the response? Isn't what you want here the semantics of give a me a response that meets these conditions or a network error? That's the kind of thing `Request` does all the time.

**Comment by wanderview** [comment]
@annevk I guess I looked at this as filtering of `cache.put(req, resp)`.  This is about putting in, not getting out of cache.

Anyway, I don't really care one way or the other.  I'll let you two cage match over it. :-)

**Comment by annevk** [comment]
Well `addAll()` first does a network fetch and you're placing conditions on the return value. If the condition is a non-match, you treat it identical to how you'd treat a network error. I don't really see how that does not make it a `Request` concern.

**Comment by jakearchibald** [comment]
Hmm, having it on request would avoid the…

```js
fetch(url).then(response => {
  if (!response.ok) throw Error("NAH");
  // etc
})
```

…boilerplate. It would make the cache code:

```js
cache.addAll(
  urls.map(u => new Request(u, {ensureOk: true}))
);
```

…which is a bit more verbose, but it would allow:

```js
cache.addAll([
  '/hello/',
  '/world/',
  new Request('//other-origin/blah.txt', {mode: 'no-cors'})
].map(request => {
  if (request instanceof Request) return request;
  return new Request(url, {ensureOk: true});
}));
```

…meaning you could mix `ensureOk` requests with others.

**Comment by jakearchibald** [comment]
Moving to https://github.com/whatwg/fetch/issues/103
