### ISSUE TITLE
ServiceWorker inherits from Worker

### ISSUE THREAD

**Issue by catalinb** [slightlyoff/ServiceWorker#410]
Why does ServiceWorker have to inherit from Worker? Looks like SW just needs to expose a postMessage method and be able to receive message events.

So why not just inherit from EventTarget and declare postMessage in the ServiceWorker idl?

This will also fix the issue of hiding terminate().

**Comment by jungkees** [comment]
It's been sorted out and spec'ed (6dfce0aacceeef41c813c4680c7f67b96f80c4b6) as suggested in the original comment ( https://github.com/slightlyoff/ServiceWorker/issues/410#issue-40100202) along with the Run Service Worker algorithm and the text for messaging between ServiceWorker and Client.
