### ISSUE TITLE
304 handling for fetch()

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#412]
Per #398 we need to decide how to handle 304 responses for `fetch()` and we need to decide if developers setting conditional headers has any "magic" effects. Implementations for XMLHttpRequest reportedly do different things, though I have not tested this recently. https://www.w3.org/Bugs/Public/show_bug.cgi?id=22414 has additional context.

**Comment by mayhemer** [comment]
"store" - what is the meaning of this word exactly?

**Comment by mayhemer** [comment]
BTW, I just repeat what Gecko does when Cache-control: no-store header is received on a response.

The main point I originally wanted to make was that "bypass" doesn't mean "no-store" (which could be ambiguous with the cache-control header value.)

**Comment by mnot** [comment]
If you go on to actually read the linked text, it says:

> "MUST NOT store" in this context means that the cache MUST NOT intentionally store the information in non-volatile storage, and MUST make a best-effort attempt to remove the information from volatile storage as promptly as possible after forwarding it.

**Comment by annevk** [comment]
I opened three new issues for the remainder of this thread:

* https://github.com/whatwg/fetch/issues/38 (how to deal with partial content)
* https://github.com/whatwg/fetch/issues/39 (security review)
* https://github.com/whatwg/fetch/issues/40 (introducing fromCache)

If there's anything I missed please let me know.
