### ISSUE TITLE
clarify ServiceWorkerGlobalScope.caches is per-origin

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#415]
Currently the spec states that "Caches are not shared across domains", but it does not explicitly define this in any algorithms.  In IRC @jakearchibald suggests this should be per-origin instead of per-domain to match the behavior in IDB.  This should be clarified in the spec.

**Comment by jungkees** [comment]
`self.caches` represented by a _name to cache map_ is per-origin: 

* https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#global-caches
* https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#cache-constructs

Closing.
