### ISSUE TITLE
Consider producing distinct objects for the same entity to enable garbage collection

### ISSUE THREAD

**Issue by coonsta** [slightlyoff/ServiceWorker#416]
ServiceWorker APIs vend various objects... ServiceWorker, ServiceWorkerRegistration, Cache. It is possible to retrieve the same thing multiple times.

This creates an issue for implementations, which must be conservative when reclaiming these objects, because they may be re-retrieved later. Whether it is safe to reclaim an object is not decidable in general because of the halting problem, it's an interactive system, etc.

For example:

    self.caches.create('seldom-used').then(function(cache) {
        cache.kiss = 'death';
      });

The implementation cannot reclaim 'cache' as long as the page is open, because it can't decide if the page will come along later and do `self.caches.get('seldom-used')` expecting to find the kiss of death on the object.

(I'm not talking about the cache *entity* here, but the page's JavaScript wrapper, the thing that the 'cache' variable is referring to.)

The same issue happens with registrations (because of getRegistration) and ServiceWorkers (through getRegistration and the active, etc. properties.) Other APIs avoid this problem by returning a distinct object instead of modelling the entity directly. For example, IndexedDB returns new *connection* objects to the same *database* entity.

**Comment by mattto** [comment]
Are distinct objects for the same entity expected to be in sync? E.g., must two ServiceWorker objects representing the same entity always have equal .state? In Chrome, distinct objects get individually updated, so this happens:
```javascript
register().then(function(r) {
  r.installing.addEventListener('statechange', function(e) {
    e.source.state == 'installed';
    r.waiting.state == 'installing';
 });
});
```

If it's required, I think the most straightforward implementation for Chrome would be to try to reuse the JS objects after all (although not requiring JS equality is still nice for gc). More details on #622

**Comment by jakearchibald** [comment]
Agreed, being able to `===` is more useful than I first thought too, especially when comparing say a message event's `source` to the SW controlling the document.

**Comment by annevk** [comment]
I agree as well, which is why I'm having a hard time with treating the equivalent scenario in service workers totally opposite.

**Comment by mattto** [comment]
To avoid the unsynced states problem, Blink now has object equality between JS objects representing the same Service Worker entity: crbug.com/459457. I believe this is spec conforming because the current spec neither requires nor disallows object equality, but it does require synced state. Accordingly, our tests only assert that state is equal between the objects.

**Comment by annevk** [comment]
We should put that in the specification though. Not defining an object's lifecycle in detail is a bug.

**Comment by jungkees** [comment]
I added [NewObject] / [SameObject] extended IDL attribute to attributes and methods: https://github.com/slightlyoff/ServiceWorker/commit/655ededa26925c898721a741d81a1b483a1d8a07. I think Gecko implementation still returns distinct objects in many places according to the earlier discussion in this thread whereas Blink implementation came with the object equality. Please review the above update. /cc @ehsan @wanderview @mattto

**Comment by jungkees** [comment]
I'm not entirely clear about the promise resolution values of the cache methods:

```js
CacheStorage.match().then(response => {});
CacheStorage.open().then(cache => {});
Cache.match().then(response => {});
Cache.matchAll().then(responses => {});
Cache.keys().then(requests => {});
```

IMO, the resolved values of the promise returned from the above methods should be the same object as well. WDYT? /cc @wanderview 

To make it clear, resolved/returned `ServiceWorkerRegistration` objects / `ServiceWorker` objects are the same objects, and resolved/returned `Client` / `WindowClient` objects are distinct objects in the current spec.

**Comment by annevk** [comment]
No, they should be fresh promise objects. And also mostly fresh Request/Response objects. Not sure about Cache objects.

**Comment by jungkees** [comment]
All the promise objects except the one returned from `.ready` are fresh promise objects. I'm talking about the objects that are resolved from those promises.

**Comment by jungkees** [comment]
Regarding the Request/Response objects, most of them are related with the cache API.

How about `FetchEvent.request` and `FetchEvent.client`? Within the same event object, shouldn't they refer to the same object?

**Comment by annevk** [comment]
`FetchEvent` members should be [SameObject], yes.

**Comment by wanderview** [comment]
> IMO, the resolved values of the promise returned from the above methods should be the same object as well. WDYT? /cc @wanderview

All Request, Response, and Cache objects returned from Cache and CacheStorage should be new objects.  This can't be represented in webidl as far as I know, though.

Reasoning:

* Request and Response objects are drainable.  They must be different objects
* Returning same object for Cache adds complexity and possibly forces de-opt because now we have to deal with js code sticking stuff on the object, etc.  Its much simpler to return new objects (as is currently) spec'd and let the GC do its work.  Please don't change this.  It will just add complications for no benefit.

I am ok with the self.caches CacheStorage object being [SameObject].  That one makes sense because its an attribute.

**Comment by jungkees** [comment]
Understood. Fair enough.

**Comment by jungkees** [comment]
Oh I didn't catch the following implementation issues:
https://code.google.com/p/chromium/issues/detail?id=523904
https://bugzilla.mozilla.org/show_bug.cgi?id=1181039

So I think the following behavior seems right (the same object and the distinct object is for the promise resolution value):
```js
navigator.serviceWorker.register().then(registration => {}); // same object
navigator.serviceWorker.getRegistration().then(registration => {}); // same object
navigator.serviceWorker.getRegistrations().then(registrations => {}); // same object
clients.matchAll().then(clients => {}); // same object
clients.openWindow().then(windowClient => {}); // distinct object
WindowClient.focus().then(windowClient => {}); // distinct object
(Extendable/ServiceWorker)MessageEvent.source; // same object
(Extendable/ServiceWorker)MessageEvent.ports; // same object

CacheStorage.match().then(response => {}); // distinct object
CacheStorage.open().then(cache => {}); // distinct object
Cache.match().then(response => {}); // distinct object
Cache.matchAll().then(responses => {}); // distinct object
Cache.keys().then(requests => {}); // distinct object
```

In the spec, when a distinct object is required, I used "new" explicitly. For the same objects, I did it with "an object that represents the target object." It seems better wording is necessary here to make it clearer? (any suggestion?)

/cc @nhiroki @mattto @wanderview @nikhilm @slightlyoff @jakearchibald @annevk

**Comment by mattto** [comment]
Thanks for pinging this bug. Yes, better wording is needed; "an object" is ambiguous about whether it's the same or distinct. Saying "the object" instead may be sufficient.

As for the actual behavior, moving from same to distinct for the registration object made Blink/Chromium code a bit simpler, but I'm ok with requiring it to be same. It's actually probably needed to keep multiple registration objects in sync when listening for onupdatefound events (like statechange events for ServiceWorker: https://github.com/slightlyoff/ServiceWorker/issues/416#issuecomment-74889353)

**Comment by jungkees** [comment]
Changed it to "**the** object that represents the target object" expression for the same object case: 6643b11cdd52bf6732fe71e35ee1761569c50b82. Sorry for the confusion.

**Comment by wanderview** [comment]
Gecko bug to return same registration object: https://bugzilla.mozilla.org/show_bug.cgi?id=1201127

**Comment by jakearchibald** [comment]
```js
clients.matchAll().then(clients => {}); // ~~same object~~ distinct object ?
```

Not sure what this means, but I think these should be distinct objects as they're snapshots. Agree with all the other distinct/same decisions.

**Comment by jungkees** [comment]
Just tried to put a strikeout on the "same object" and clarified it to the "distinct object".

> clients.matchAll().then(clients => {}); // ~~same object~~ distinct object ?

The current spec resolves with distinct objects.

Thanks for the review! Closing.
