### ISSUE TITLE
Update clients spec

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#420]
The ts is up to date, as is the IDL at https://github.com/slightlyoff/ServiceWorker/issues/414#issue-40164668

**Comment by jungkees** [comment]
F2F: A service worker client is using a [creation url](https://www.w3.org/Bugs/Public/show_bug.cgi?id=27146) to represent it. That is to say, `.url` should return the url before it's changed by pushState(), etc.
