### ISSUE TITLE
Expose ServiceWorkerRegistration within ServiceWorkerGlobalScope

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#421]
This gives access to APIs that hang off the registration object, such as registering new geofences, unregistering push, setting a background sync etc. Obviously any calls that require a permission dialog would fail.

This would make `unregister` and `scope` redundant.

Also required by Notifications http://lists.whatwg.org/pipermail/whatwg-whatwg.org/2014-August/297371.html

**Comment by jungkees** [comment]
`ServiceWorkerRegistration` is not exposed to all worker environments. Closing.
