### ISSUE TITLE
ServiceWorkerClientQueryParams includeUncontrolled and algorithm are at odds

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#428]
By the spec definition of 'controlling', I'd expect getAll({includeUncontrolled: true}) to return clients that are not controlled, but *restricted to the scope of the relevant ServiceWorkerRegistration*. The spec algorithm returns all clients within the origin.

Rename to `includeOutOfScope`?

**Comment by jungkees** [comment]
It has been specified as:
> clients.getAll({includeUncontrolled: true}) to return all clients on the origin.

Closing.
