### ISSUE TITLE
ServiceWorkerClient can't be a MessageEvent.source because it's not a WindowProxy or MessagePort

### ISSUE THREAD

**Issue by coonsta** [slightlyoff/ServiceWorker#453]
MessageEvent.source is defined here: http://www.whatwg.org/specs/web-apps/current-work/multipage/comms.html#dom-messageevent-source

If a document postMessages a Service Worker, should the MessageEvent.source property be null? It can't be a ServiceWorkerClient because ServiceWorkerClient isn't a WindowProxy or MessagePort (nor should it be, probably...)

**Comment by KenjiBaheux** [comment]
Does the introduction of WindowClient help solve this issue?

**Comment by annevk** [comment]
@KenjiBaheux not really, since it's not persistent. And message ports typically are. I think we maybe need to revisit the static object design...

**Comment by jungkees** [comment]
It's been sorted out and spec'ed as in: 6dfce0aacceeef41c813c4680c7f67b96f80c4b6.

**Comment by inexorabletash** [comment]
Do we need to file a bug against html to get @hixie to modify `MessageEvent`, since `Client` is still not a `(WindowProxy or MessagePort)` ?

**Comment by jungkees** [comment]
Filed a bug: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28199 and left a comment: 480aa8f5465ffb4b8422e0acfe579c7895234433 in the spec. Thanks.
