### ISSUE TITLE
caches.create should return existing cache if it already exists

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#458]
Currently it rejects, and this is really annoying in practice. My code is littered with.

```js
caches.get(name).then(c => c || caches.create(name));
```

Should just be:

```js
caches.create(name);
```

(going to be reviewing the rest of the cache API tickets soon too, sorry for being slow on this)

**Comment by jungkees** [comment]
Now caches.open() does so. caches.create() in the example has been replaced by caches.open() as well. Closing.
