### ISSUE TITLE
Multi-author sites

### ISSUE THREAD

**Issue by mnot** [slightlyoff/ServiceWorker#468]
As discussed, https:// sites that have multiple authors may be surprised to discover that user a can now overwrite content for user b.

What's needed:
  1) text (Security Considerations?) explaining the attack
  2) evangelisation to warn sites
  3) maybe a csp-ish opt-out (or -in, but @slightlyoff isn't hot on that)

Will do a pull for 1.

**Comment by slightlyoff** [comment]
@mvano, @jakearchibald : I agree that we should change the default path. Have been bit by this now that Chrome implements the path restriction.

**Comment by jakearchibald** [comment]
@slightlyoff see #595 - we've done just that

**Comment by KenjiBaheux** [comment]
@jungkees would you mind updating the spec to take into account the Service-Worker-Allowed header as described in https://github.com/slightlyoff/ServiceWorker/issues/468#issuecomment-60276779 ? 

Background: we've got feedback from Service Worker customers that the ability to override the path restriction via this header is important to them. The team has pro-actively started its implementation assuming that it is in the pipeline of spec updates.

**Comment by jungkees** [comment]
Alright. I'll work on that.

**Comment by jungkees** [comment]
Updated the steps to allow setting a max scope with the Service-Worker_Allowed header: ddb21be5b42abd4e516112a2ff95d8c9dadf40b4.

The scope check has been moved from Register algorithm to Update algorithm 4.3.9 ~ 4.3.17 as such.

**Comment by mattto** [comment]
@jungkees Thanks for the quick update. I have some questions about the spec. I'll opened #604 as this bug is really long.
