### ISSUE TITLE
Cache Request/Response consistency

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#469]
From talking with @annevk, it seems that Fetch guarantees things like the Response.url will match the Request.url that generated it.  In contract, the Cache API currently allows you to store Responses with a completely different URL from their Request keys.

Should the cache force the Response URL to match the key Request URL?  Are there any other fields that should be similarly modified on the Response to match the Request?

A minor side benefit of this is that we can save a few bytes of storage in the cache for each Response.

**Comment by jakearchibald** [comment]
Can you create a response without a non-https scheme? I think this could be another issue.

As for this issue, you can create request.url/response.url mismatches.

**Comment by annevk** [comment]
Did you file that other issue? You can certainly get responses without HTTPS scheme (or without URL).
