### ISSUE TITLE
Cache spec needs to treat body data asynchronously

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#470]
Currently the spec text uses the concept of [[RequestToResponseMap]] to represent Cache storage.  For example:

> Set a newly-created Record {[[key]]: request, [[value]]: operation.response} to [[RequestToResponseMap]].

This maps well to the .ts file code, but unfortunately glosses over the important fact that the Request and Response body data are streams.  Writing and reading these body streams must be asynchronous.  Text such as quoted above does not satisfy this.

All kinds of race conditions end up unspecified if we do not recognize that body reads and writes are asynchronous.  For example:

```
cache.match(request).then(function (response) {
  cache.delete(request);
  var responseBodyJson = response.json();
});
```

Here we end up with an async read of the response body data in progress when cache.delete() wants to remove it.  We can make a guess as how this should work, but it probably needs to be part of the spec.

In this particular case I spoke with @jakearchibald and he suggested that the delete should remove the response from the index and schedule the body data to be removed later after the read is done.  Overall, though, I think the spec text should be more clear about how body data storage is handled.

Thanks!

**Comment by jakearchibald** [comment]
Reviewed the spec at f2f, we seem to be doing the right thing here
