### ISSUE TITLE
Relationship to Caches & ScriptCache in ServiceWorkerGlobalScope

### ISSUE THREAD

**Issue by dmurph** [slightlyoff/ServiceWorker#473]
The relationship between caches & scriptcache to each serviceworkerglobalscope is not clear in the spec:

*  Do many serviceworker versions point to the same caches?  Yes would make sense.
*  It seems like there should be one script cache per service worker version (due to different scripts being loaded per version).  Is this the case?

Since it seems like there are different answers here, then this means we'll be needing slightly different cache architecture for script vs normal caches.  I know currently this is very much the case, as script cache isn't even hooked up (and it lives on it's own SimpleCache).

**Comment by wanderview** [comment]
There is no concept in the ServiceWorker life cycle of some external script on the main thread modifying the Cache.  Its not like the SW would reload from that, etc.

I think we should remove `scriptCache` now and maybe add it back if we have the concept of a read only Cache.

We're not implementing it in gecko for the foreseeable future. @inexorabletash also says "no plans to implement it any time soon in blink, either".

**Comment by jakearchibald** [comment]
Done! https://github.com/slightlyoff/ServiceWorker/commit/88e970d7c17e6871f48a490d14e9a693d94e89d0

I think it's a good feature, and may be brought back to help with https://github.com/slightlyoff/ServiceWorker/issues/639. We should at least have script cache as a concept to explain how and when `importScripts` scripts are cached.

**Comment by jungkees** [comment]
Yes, I spec'ed the internal slot, _script resource map_ for now which stores the `importScripts` scripts https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-script-resource-map.

We can use this internal slot the spec the relevant attributes when needed.

Closing the issue for now.
