### ISSUE TITLE
ServiceWorker's postMessage method is not defined

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#479]
It can't work the same way as it does on workers, since we don't know whether the service worker is running.

This is why I mentioned several times that you need an intermediate place where you queue all these messages, that can then be dispatched when the service worker wakes up.

**Comment by owencm** [comment]
Am I right in saying there is currently no postMessage interface for interacting with a SW in this case? I'm just wondering about the actual practicality of communicating from a SW -> app code today.

**Comment by jungkees** [comment]
Spec'ed it here: 6dfce0aacceeef41c813c4680c7f67b96f80c4b6. If we need to discuss further on what has been defined there, let's file a new ticket.
