### ISSUE TITLE
Cache object grammar

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#494]
"The Cache interface represents the storage for the pairs of a Request object and a Response object that are cached as part of the Service Worker installation." This sentence could use improving. Perhaps

"The Cache object represents an unordered sequence of `Request`/`Response` object pairs."

is better. Note that the final bit of the original sentence is wrong, as `Cache` can be used outside service workers as well.

**Comment by jungkees** [comment]
This part of the text has been largely updated, and the original sentence has been replaced. Thanks for the comment. Closing.
