### ISSUE TITLE
Changing ServiceWorkerClient.hidden to visibilityState

### ISSUE THREAD

**Issue by beverloo** [slightlyoff/ServiceWorker#498]
In Chrome for Android, and I suspect other mobile browsers as well, the operating system may kill any renderer process at any time, for any reason. Tabs whose process has been killed will still show up in the tab switcher, so as far as the user is concerned the tab is opened.

This creates an interesting problem when iterating over the clients:
```
clients.getAll().then(function (clients) {
    clients.forEach(function (client) {
        client.postMessage('hello!');
    });
});
```
Unless we wake up the client to deliver the message send to them (which I don't want to do from a resource consumption point of view), it'll just silently disappear in a black hole, with no way for the developer to know.

The `client.hidden` property is not sufficient for to deal with this. A window which is hidden on desktop platforms can still be assumed to be alive, and thus be able to receive messages.

I propose removing `client.hidden`, and instead exposing `client.visibilityState`. Like `hidden`, it would be a snapshot, but next to _hidden_ and _visible_ it also indicates if the client is _unloaded_.

http://www.w3.org/TR/page-visibility/#dom-document-hidden

**Comment by jungkees** [comment]
Yes, we not have `WindowClient.visibilityState`. Closing.
