### ISSUE TITLE
ServiceWorkerClients.getAll should be sorted by recency

### ISSUE THREAD

**Issue by johnmellor** [slightlyoff/ServiceWorker#499]
When a SW receives a notificationclicked event, app developers will typically want to focus the most recently used tab from their origin matching some URL pattern.

To make this easier, I'd suggest defining [ServiceWorkerClients.getAll](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-clients-getall-method) to return the clients sorted in Most Recently Used (MRU) order (currently the order is undefined).

@jakearchibald

**Comment by jungkees** [comment]
Addressed: 55d359fc18351850d288c4eb759b4f3629fb43f0.

**Comment by jungkees** [comment]
Closing.
