### ISSUE TITLE
Need a linkable section for "start up a service worker if it is not running"

### ISSUE THREAD

**Issue by mvano** [slightlyoff/ServiceWorker#501]
Currently in the Push API in the section for firing a push event I have a phrase like this: "If the Service Worker associated with the webapp is not running, start it."

Other specifications like Notifications and Geofencing will have very similar sections. I think we need something linkable in the Service Worker spec that defines this concept.

**Comment by jungkees** [comment]
Here's a guide to dispatch a functional event to a service worker: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#request-functional-event-dispatch. Feel free to reopen it if you have any concern. Closing.
