### ISSUE TITLE
Please mention relationship to HTTP cookies

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#509]
Insofar that the "clear cookie" UI in user agents should also clear service workers. Otherwise they would be a cookie-reviving mechanism, and we don't want those.

See also: https://html.spec.whatwg.org/#fingerprinting-vector

**Comment by inexorabletash** [comment]
Spec basically just needs a Privacy section similar to https://w3c.github.io/IndexedDB/#privacy

**Comment by jakearchibald** [comment]
@annevk should/could this go into the storage spec?

**Comment by annevk** [comment]
Maybe once everything is written on top of actual storage primitives the storage specification defines, that would sort of fall out naturally. But I think for now every specification that defines some type of storage needs to call it out explicitly.

We haven't really figured out what the primitives are (even just in text form) you can build storage for localStorage, Indexed DB, service workers, etc. on top on.

**Comment by jungkees** [comment]
Added text for privacy section: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#privacy. 

/cc @slightlyoff @jakearchibald

**Comment by jungkees** [comment]
Closing.

**Comment by annevk** [comment]
I would prefer it if you explicitly mention cookies.

**Comment by jungkees** [comment]
The [unsanctioned user tracking](http://www.w3.org/2001/tag/doc/unsanctioned-tracking/#h-unsanctioned-tracking-tracking-without-user-control) xref explicitly points out the cookie-reviving scenario:
> So-called SuperCookies use implementation bugs, browser fingerprinting and other techniques to continue to identify you and correlate your activity even after you clear your cookies (e.g. “re-synchronizing” them).

This seems cover your concern?

**Comment by annevk** [comment]
I guess that's okay for now.
