### ISSUE TITLE
new ServiceWorkerClient makes no sense?

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#511]
So the idea is that `new ServiceWorkerClient` instantiates a new `Window`. However, a Client represents both a `Window` and a `WorkerGlobalScope`. This needs to be done some other way I think.

**Comment by jungkees** [comment]
I believe we've been discussing through it and sorted out the issue. For the original question here, we provide `clients.openWindow(url)`. Closing.
