### ISSUE TITLE
Move installEvent.replace() onto ServiceWorkerClients

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#518]
Use Case comes from @paullewis, paraphrasing:

> When a new SW version installs, I want to `postMessage` any in-scope pages so they can show an "update downloaded, click to show" banner. When this banner is clicked, the waiting worker is nudged, it calls `replace()` and the pages refresh themselves so they're loaded with the latest data.

`reloadAll()` would better suit this use case, but we're a while off specing that (it's huge and full of new things).

Paul's use case isn't possible because the install event has been and gone, so the opportunity to call `replace()` has passed. We already moved `reloadAll()` to `ServiceWorkerClients` before we punted on it, I think `replace()` makes more sense there too, renamed something like `takeControl`.

So, if a ServiceWorker calls `clients.takeControl()`:

1. If the ServiceWorker is installing, wait until install complete
1. If the ServiceWorker is redundant, reject
1. If the ServiceWorker is installed, activate it (removing any current active version)
1. For each client
  1.  If the result of running Match Scope algorithm, or its equivalent, with documentURL as its argument, is equal to this worker's registration, then
    1. Let client use this worker's registration as its service worker registration

**Comment by jungkees** [comment]
`self.skipWaiting()` is done. `clients.claim()` will be tracked in another thread. Closing.

**Comment by jungkees** [comment]
`Clients.claim()` has been specified: https://github.com/slightlyoff/ServiceWorker/commit/aeee6b9d5fa3eb071cb9667f1d599ecf90a78410.
