### ISSUE TITLE
Define environment settings object for service workers

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#526]
There's a number of difficulties here. E.g. service workers cannot have a responsible document or browsing context. They might also want to store additional things, such as a service worker registration.

I would probably coordinate with @Hixie how to best approach this. You might want to refactor the way workers are defined a bit so more things can be shared and less special casing is required for service workers.

**Comment by jungkees** [comment]
I spec'ed it in the Run Service Worker algorithm: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#run-service-worker-algorithm.

I haven't particularly come across a need for a service worker registration in the environment settings object while spec'ing it.

Let me know if you have any suggestion.

**Comment by annevk** [comment]
Where else do you get the service worker registration from?

**Comment by jungkees** [comment]
They are mostly gotten by invoking Match Service Worker Registration algorithm or Get Registration algorithm. And the ServiceWorkerRegistration objects are associated with the service worker clients, so in the client context they can be directly referred to through the associated ServiceWorkerRegistration objects.

**Comment by annevk** [comment]
In the service worker they also need to be associated with something since you can access them directly from a service worker.

**Comment by jungkees** [comment]
From a service worker, you can access them by its [containing service worker registration](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-containing-service-worker-registration) which is persistent to the lifetime of the service worker.

**Comment by jungkees** [comment]
Closing.

**Comment by annevk** [comment]
But what object holds the pointer to the containing service worker registration? Shouldn't that be the environment settings object? Am I missing something from the object model?

**Comment by jungkees** [comment]
A service worker's global, i.e. a `ServiceWorkerGlobalScope` object has its associate _service worker_. (https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#dfn-service-worker-global-scope-service-worker) And this _service worker_ internal slot has a reference to its _containing service worker registration_.  (https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#dfn-containing-service-worker-registration)

**Comment by annevk** [comment]
Thanks, I guess that works. I would have put it all on the environment settings object since it's 1:1 with the global, but okay.
