### ISSUE TITLE
"The user agent may terminate service workers at any time it has no event to handle."

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#527]
This seems wrong. It's fine for a user agent to have an external queue and not fire up the service worker because it wants to allocate resources elsewhere.

I recommend defining the actual run and terminate algorithms for a service worker and not talk about the exact timing when they need to be invoked.

**Comment by jungkees** [comment]
It's been spec'ed with the following text:
2.1.1 Service worker lifetime
- The user agent may terminate service workers at any time it has no event to handle or detects abnormal operation such as infinite loops and tasks exceeding imposed time limits, if any, while handling the events.
4.4.1 event.waitUntil(f)
- The user agent may impose a time limit to this lifetime extension.

Closing.
