### ISSUE TITLE
ServiceWorkerRegistration should not be a dumping ground for features

### ISSUE THREAD

**Issue by esprehn** [slightlyoff/ServiceWorker#532]
We shouldn't be adding a property to the registration object for features that are not related to service worker. Specifically it seems like right now the object is becoming the new Window object with properties for push, geolocation, notifications, and will similarly dispatch events for those things. Please factor these apart, ServiceWorkerRegistration shouldn't need to know about every feature in the engine.

**Comment by RichardMaher** [comment]
Why was this added to Version 2 milestone. What is the alternative ?

**Comment by jakearchibald** [comment]
> push, geolocation, notifications

But these features are very much associated with the SW registration. The push registration is per SW registration, and the related events go to the active SW within that registration. If the SW is unregistered, these things are also unregistered.

Really sorry this issue got lost in the noise, but I'm closing this issue. Feel free to reopen if I've got the wrong end of the stick, or there's a better alternative to putting these features on SW registration.
