### ISSUE TITLE
Provide opt-in to avoid request body duplication

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#533]
Once streams land, we want support in fetch. This issues tracks that and is a home for considerations.

**Comment by annevk** [comment]
So when I added `redirect = "error"` I forgot about this optimization.

The other avenue for a repeated request is HTTP authentication. Now normal HTTP authentication is not a problem as that is disabled in `fetch()` (you need to handle that yourself, building `Authorization` headers etc.). However, there is also HTTP proxy authentication. Opting out of that might be tricky or not desired. So I'd still need some input from network experts whether we can make the optimization and how that would affect HTTP proxy authentication.

**Comment by annevk** [comment]
(It might be better to move this issue to https://github.com/whatwg/fetch at this point... I'd like to stop using this repository for Fetch issues.)

**Comment by tyoshino** [comment]
On network with small RTT, it might be ok to:
- ask users who want to do streaming to return a response header asap
- have UAs refrain from forgetting sent data until it receives a response header

Can we use 100 continue or something to carry this kind of signal (It seems the final HTTP2 spec allows 100 continue)?

For large RTT network, it would be big loss if we don't start sending data until we receive a response (we shouldn't assume the underlying connection is TCP. Now we have HTTP2, etc.).

**Comment by annevk** [comment]
So that would be a protocol addition to enable something similar to this with the server controlling behavior. That might be good to support in due course and probably warrants a distinct ticket (against whatwg/fetch) and coordination with @mnot and cohorts.

However, my open question is about letting the client decide. That is, what should do about the situation where apart from proxy authentication we know no teeing would be needed?

**Comment by mnot** [comment]
It sounds like you're talking about expect/continue:
  http://httpwg.github.io/specs/rfc7231.html#header.expect

**Comment by annevk** [comment]
Thanks! Indeed that seems sufficient for a negotiated version of this with some kind of opt-in flag passed to `fetch()`. I'd still be interested in hearing if we can avoid or fail on HTTP proxy authentication (407) so we can have a client-driven solution as well.

**Comment by annevk** [comment]
Opened two issues. One for the protocol-based version and one for the client decides version:

* https://github.com/whatwg/fetch/issues/41
* https://github.com/whatwg/fetch/issues/42

Closing this one. Other Fetch stream concerns are tracked by this repository by the way:

* https://github.com/yutakahirano/fetch-with-streams
