### ISSUE TITLE
Registration API doesn't expose primitives

### ISSUE THREAD

**Issue by sicking** [slightlyoff/ServiceWorker#534]
As I was writing up the proposals in issue #445 I noticed some mainly unrelated oddities in the current registration API.

Right now there's a few operations that aren't exposed through the API. These operations are instead only available 

1. Waiting for a given registration to become available. The ```serviceWorker.ready``` property lets you do this, but only for the SW whose scope covers the current page. If you want to do it for any other SW you have to create an `<iframe>` to a page within that scope and call serviceWorker.ready there.
2. You can't force just an update. You can do this by calling ```register()```, but that forces you to pass in the same registration parameters as when the registration was originally. It also creates a new "service worker registration", which I'm not sure if that has the side effect that it causes ```getRegistration(s)``` to return a different ```ServiceWorkerRegistration``` instance (or does ```getRegistration(s)``` always return new instances?)
3. You can't do an atomic "check if a SW registration exists, if so hand it back, otherwise create a registration". Again, ```register()``` does this, but it also forces an update check if the registration already exists.

Per extensible web we should expose these lower level operations rather than just have them be part of larger APIs.

We could solve 1. by firing events on ```navigator.serviceWorker``` whenever registrations are added/removed/updated. Or we could add something like ```registrationReady(url)``` which is like ```getRegistration(url)``` except rather than resolving with undefined if no registration is found, it waits to resolve until such a registration is created.

Adding a ```Promise<boolean> ServiceWorkerRegistration.update()``` function would solve 2.

I don't have a great solution for 3. One option would be to have ```register()``` not do an update check if a registration exists. That way ```register()``` would provide this primitive. Alternatively we could add a ```getOrRegister()``` function which is like ```register()```, except it doesn't do the update check.

**Comment by jakearchibald** [comment]
We added `reg.update`, and `.register` doesn't trigger a soft update.

`reg.ready` is still a good idea. Broken out into https://github.com/slightlyoff/ServiceWorker/issues/770
