### ISSUE TITLE
window.caches and window.fetch should be [Replaceable]

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#535]
…so we don't break pages that currently have:

```js
var caches = {};
var fetch = "Hooray!"
```

**Comment by tyoshino** [comment]
BTW, it seems `[Replaceable]` is defined only for attributes. Maybe `[Unforgeable]` is the right extended attribute to discuss? Operations don't have it by default, and so the current spec allows overwriting window.fetch on both objects and their prototype objects?

I find `[Unforgeable]` in some part of ServiceWorker IDLs. Is there any trend to use it for newly introduced APIs?

(Copied from blink-dev https://groups.google.com/a/chromium.org/d/msg/blink-dev/qwRO52vsQlU/5YzMNwThrjoJ)

**Comment by annevk** [comment]
No, we typically avoid it. This issue was probably started based on the wrong facts.

**Comment by tyoshino** [comment]
OK. So, maybe now we can just close this?

**Comment by annevk** [comment]
Yeah.
