### ISSUE TITLE
CacheStorage.delete() does not specify how to handle currently referenced Cache

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#538]
Currently the spec simply states the following for CacheStorage.delete():

> 1. If cacheExists is true, then:
>   1. Delete a Record {[[key]], [[value]]} entry of its [[NameToCacheMap]] where cacheName matches entry.[[key]].
>   2. Resolve q with true.

Per IRC and other issue discussions it seems that there is an expectation the underlying Cache data will continue to live until the last reference to the Cache object is dropped.  At that point the underlying storage should be removed.

This should be clarified in the spec.

Also, please clarify whether the Promise returned from CacheStorage.delete() should be resolved after removing the reference from the CacheStorage index or only after the Cache has been truly delete.  I assume its after removal from the index.

**Comment by jakearchibald** [comment]
We should add a note on the lifetime of cached items on disk (or wherever they're stored).

A cached item should remain on disk until:

* its cache has been dereferenced from `NameToCacheMap`
* no references exist to the cache
* no references exist to the request/response

**Comment by wanderview** [comment]
Just to clarify, I think saying "existing DOM objects should remain functional" is a little better.  If an implementation pulls data into memory for DOM objects, then it could reasonably delete from disk immediately.

The important part is that caches.delete() doesn't break referenced Cache, Request, and Response objects.
