### ISSUE TITLE
installing/waiting/activating state transition event and state lead to confusion.

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#539]
For example, [[Install]] step 8.5-8.7 state:
> Set registration's waiting worker to registration's installing worker.
> Set registration's installing worker to null.
> Run the Update State algorithm passing registration's waiting worker and installed as the arguments.

If page script has:

    register("foo.js").then(function(reg) {
      // A
      reg.installing.onstatechange = function() {
        // B
        reg.installing.state == ???
        reg.waiting.state == ???
      }
    })

At "A" above, reg.installing will be a ServiceWorker object for the internal representation's `installing` service worker.
When [[Install]] reaches the above steps, it will change the internal values, and queue a statechange event. In addition, due to thread scheduling and [[Activate]] possibly being called right after the task is statechange task is queued, you can end up with waiting worker already getting swapped out to activating.
At "B", accessing state is not straightforward at all. The correct check seems to be

    // Code in block B
    if (reg.installing && reg.installing.state == "redundant") { /* something went wrong; */ }
    else if ( reg.waiting && reg.waiting.scriptURL == ".../foo.js" ) { 
        // more code here to wait for reg.waiting to statechange to active.
    } elseif (reg.active && reg.active.scriptURL == ".../foo.js") {
        /* do something useful now that the new worker is activated. */ 
    }

Am I making it too complicated or is this a real issue?

P. S. The reason this came about is, I'm trying to write a test where the driver wants to wait for a newly registered serviceworker to become active, and right now there is no way to test that from the driver which is in a different scope. Issue #534 considers the API for such a primitive.

@KenjiBaheux @coonsta How have Blink's tests implemented the above pattern?

**Comment by jungkees** [comment]
@jakearchibald I'd like to hear your comment before closing this.

**Comment by jungkees** [comment]
F2F day2: See no problem tracking ServiceWorker object instance throughout scripts. Closing.
