### ISSUE TITLE
Clarify if Cache put()/add()/addAll() should mark Request body used

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#550]
Please clarify how the Cache should treat the Request body for the put()/add()/addAll() methods.

My interpretation is that the Cache must store the Request body in order to reproduce the Request in the keys() method.  The Fetch spec does not provide a way to retrieve the body from the Request without marking the body used.  So my position is that the current spec requires put()/add()/addAll() to mark the Request body used.

Also, I believe the discussion in #372 came down on the side of avoiding magical implicit clones in favor of explicit clones.

cc / @jakearchibald @inexorabletash

**Comment by jungkees** [comment]
Closing.
