### ISSUE TITLE
SW spec should expose Resource Timing and User Timing

### ISSUE THREAD

**Issue by igrigorik** [slightlyoff/ServiceWorker#553]
_(based on discussion at TPAC...)_

* http://w3c.github.io/resource-timing/ - allows SW to get timing information for network fetches.
* http://w3c.github.io/user-timing/ - allows SW code to set and measure own marks + durations.

We don't need to expose Navigation Timing since all fetches look like "resource fetches" to SW - i.e. navigation requests are covered by Resource Timing.

Also, related: https://github.com/w3c/hr-time/issues/1

**Comment by jakearchibald** [comment]
Is this stuff available in workers? 

I see it defined on windows, but not workers https://dvcs.w3.org/hg/webperf/raw-file/tip/specs/NavigationTiming/Overview.html#sec-window.performance-attribute

**Comment by igrigorik** [comment]
The spec doesn't, and we need to fix that. I'm thinking:

- Update Performance Timeline to expose itself on [Window,Worker]
- Update other specs and drop "window.performance" language in favor of more generic description that is worker friendly.

/cc @plehegar any thoughts on this one?

**Comment by igrigorik** [comment]
> @jakearchibald: "If it's exposed to Worker, it'll be in ServiceWorker (that's how SW gets idb etc)."

Closing, resolved by https://github.com/w3c/performance-timeline/pull/7.
