### ISSUE TITLE
When responses from origin A are used in response to a request for origin B, treat as a redirect

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#560]
Basically, with:

```js
self.onfetch = function(event) {
  // event.request.url == //example.com/blah.css
  event.respondWith(
    fetch('//other-origin/whatever.css')
  );
};
```

…it would be treated as a redirect.

It's a suggestion from @metromoxie to avoid big changes to Chrome's codebase. It's a bit vague right now, I'll update with more details as I get them.

I'm not really interested in compromising the API or adding complications for the sake of Chrome's codebase, but if Mozilla has the same issue we could give it some more thought.

Initial thoughts:

**This impacts base URLs** for things like CSS. In the example above `background-image`s would become relative to `//other-origin/`, whereas in the current model URLs are relative to `//example.com/` (as a proxy response would work).

**Do these redirects come back through the ServiceWorker?** That feels weird to me, but maybe I've been working with the current model too long.

**What happens with manually created responses?** What origins do they have?

```js
self.onfetch = function(event) {
  // event.request.url == //other-origin/blah.css
  event.respondWith(
    new Response("body { background: green; }", { headers:{'Content-Type': 'text/css'} })
  );
};
```

If the above generates a redirect, it'd have to be to some kind of blob url. Or maybe manual responses are exempt from these redirects. Both options feel weird to me.

**Prevents responding to navigations with other-origin content** such as:

```js
self.onfetch = function(event) {
  // event.request.url == //this-origin/
  event.respondWith(
    caches.match('//my-static-server/static-ui.html')
  );
};
```

The above works in the current model, as long as the response isn't opaque. However, in the redirect model, the redirect would happen, URL in the URL bar changes, and the above service worker wouldn't be able to provide content as we're now out-of-scope.

@annevk @sicking @wanderview - how do you feel about this?

**Comment by annevk** [comment]
It seems we reached agreement on the current specification text here, closing.

**Comment by mattto** [comment]
I'm unclear what the conclusion of this thread is and don't see commits linked to it. Is this the relevant  spec text: "The final URL of all successful (non network-error) responses is the requested URL."

So I guess the conclusion to the bug title is "no, do not treat as a redirect"?  In the example SW above, after the fetch occurs, Request URL is "//example.com/blah.css" and the Response URL is "//other-origin/whatever.css". Whereas if it were a redirect, the Request URL would be "//other-origin/whatever.css" and the Response URL "//other-origin/whatever.css". Is that correct?

**Comment by annevk** [comment]
The relevant specification for this is Fetch. That "guidance" text should probably be removed from `respondWith()` or demoted to a note of sorts. It's not very clear nor necessarily accurate in the face of redirects (which modify the request URL).

What happens in Fetch is that the response URL is overwritten by the request URL just before the point where we hand the response back to the caller.

CSP needs to happen on the original response URL though (and perhaps also on any redirects it passed while in the service worker, that's not agreed upon as of yet).

**Comment by mattto** [comment]
Let me see if I understand. This means if you have ```<img src="http://www.example.com/blah">``` and your controlling SW is ```onfetch = function(e) { e.respondWith('http://www.wikipedia.org/image.png'); }```, from the point of view of the request for the ```img```, the request URL is ```http://www.example.com/blah```, the response URL is ```http://www.example.com/blah```, and the original response URL is ```http://www.wikipedia.org/image.png```. Does the response URL ever differ from the request URL, when the caller gets the response?

The Fetch spec mentions a "final url" flag, but it's never set by the current Fetch spec or SW spec, what's the idea for that?

**Comment by annevk** [comment]
@mattto they may differ from the perspective of the caller, since redirects are not exposed to the caller and redirects will change the request URL of the underlying request. And that request URL ends up on the response.

The "final url flag" may be removed per https://github.com/slightlyoff/ServiceWorker/issues/607#issuecomment-77590369 and subsequent comments. It's a bit magical with navigation and not a huge improvement over redirects otherwise I think.
