### ISSUE TITLE
IDL: define ContextFrameType

### ISSUE THREAD

**Issue by irori** [slightlyoff/ServiceWorker#572]
The frameType attribute of [ServiceWorkerClient](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-client-interface) is declared as [ContextFrameType](http://fetch.spec.whatwg.org/#concept-request-context-frame-type), which is not a part of the interface of the fetch spec but is an internal concept.

We should have a definition of ContextFrameType enum somewhere.

**Comment by jungkees** [comment]
Specified `Client.frameType`: 620cf7ccc0b7ded427b6539b18ae0f28d06e8cc7. 

Note that _window client_'s associated _frame type_ is defined as a _context frame type_ in fetch spec. And the frame type setup seems straightforward. Closing.
