### ISSUE TITLE
Can caches store and retrieve results that are still being written to the cache?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#573]
At the moment cache-adding methods resolve when the full body of the response if written to the cache. That means we can reject if the body stream looks like a failure, which can be suggested by content-length https://github.com/slightlyoff/ServiceWorker/issues/362#issuecomment-49011736. This is a must due to `installEvent.waitUntil(addStuffToCaches)` - we can't have that resolve but ultimately fail.

However, if you have code that tries the cache, falls back to the network and adds to the cache, you can end up with multiple pages doing this with the same resource, as `cache.match` won't return items until it's fully cached.

Shall we change this so items are added to the underlying cache as soon as we have headers? So for `cache.add(request)`:

1. Fetch request
1. If fetch fails, reject & abort
1. Add (request, response) to RequestToResponseMap
1. Wait for body to stream into cache
1. If body writing fails, remove (request, response) from RequestToResponseMap, reject the promise & abort these steps
1. Remove other entries in RequestToResponseMap that match request (`.match` can no longer reach them)
1. Resolve promise

If you call `.match(request)` and there's already a match fully-written in the cache, you'll get that rather than the in-progress one. This seems sensible to me, but we *could* favour the in-progress one.

If you get an in-progress response back from `.match(request)`, that goes back to the page, it may arrive slowly, it may ultimately fail. But hey, that's the same as the network, which it ultimately is.

Questions:

* Does this sound like a good idea?
* It is universally a good idea, or should it be an option to `.match()`. I don't think it needs to be optional.

Related: #361 #362

/cc Cache-warriors @wanderview @gavinp @sicking

**Comment by jakearchibald** [comment]
@jungkees 

I might be reading wrong, but I think there's been a couple of regressions in the spec. Imagine a cache with 2 entries that look like this header-wise (assume each has the same URL):

1. Request: `{ "Accept": "text/html" }` Response: `{"Vary": "Accept"}`
1. Request: `{ "Accept": "foo/bar" }` Response: `{}`

Then if we add a new entry to the cache, Request: `{ "Accept": "text/html" }` Response: `{}` (no Vary), the cache should now look like this:

1. Request: `{ "Accept": "text/html" }` Response: `{}`

The original algorithm would delete entries from the cache that match the new entry's request. As far as I can tell, the current spec would modify the first entry in the cache, leaving the second. That means the second entry cannot be matched, since the first will always match first. Am I reading it correctly?

In a system where we allow in-flight requests into the cache, it could work like this:

1. Request: `{ "Accept": "text/html" }` Response: `{"Vary": "Accept"}`
1. Request: `{ "Accept": "foo/bar" }` Response: `{}`

Then if we add a new entry to the cache, Request: `{ "Accept": "text/html" }` Response: `{}`:

1. Request: `{ "Accept": "text/html" }` Response: `{"Vary": "Accept"}`
1. Request: `{ "Accept": "foo/bar" }` Response: `{}`
1. Request: `{ "Accept": "text/html" }` Response: `{}` (in-flight)

So nothing's deleted from the cache at this stage. `.match` will favour entry 1 before 3, because it goes with first match. But once the request from entry 3 completes, it removes entries from the cache that match its request, leaving: 

1. Request: `{ "Accept": "text/html" }` Response: `{}`

This mean there aren't entries in the cache that cannot be matched.

I also think it's important to keep the cache in an order where the most recently added entries are at the end. This is useful when pruning caches. Talking to Twitter last week, they were interested in adding cached items back into the cache once they'd sent them to the browser. If added entries appear at the end of the list, this helps them track which items were "last accessed", therefore which entries they should keep.

**Comment by jakearchibald** [comment]
Also, sorry I was so late in getting to this :(

**Comment by jakearchibald** [comment]
@wanderview 

> But I still find the flag on fetch() harder to reason about

Yeah, my suggestion was silly. I think you're right, this needs to go on the cache. Will open a new ticket for that once we have the other in-flight stuff defined.

**Comment by jungkees** [comment]
> So nothing's deleted from the cache at this stage. .match will favour entry 1 before 3, because it goes with first match. But once the request from entry 3 completes, it removes entries from the cache that match its request

Addressed the point: 8e76892db1e9ccbe3a65601528f4f082f5e0eb46. Thanks for spotting it and explaining the details @jakearchibald.

**Comment by jungkees** [comment]
I believe we've done with defining the behavior for the fetching / incumbent records of caches. Closing.
