### ISSUE TITLE
Drop client from fetchEvent/request?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#575]
Do we have any good use cases for this?

Talking through with @Hixie & @annevk, communication between request initiator and SW would be better off more granular by setting up a port between the two.

This would be pretty easy with the `fetch` API, but trickier when it comes to elements that trigger requests such as `<img>`.

**Comment by jungkees** [comment]
Here came a relevant request: https://github.com/slightlyoff/ServiceWorker/issues/609#issuecomment-77479970

**Comment by annevk** [comment]
Yeah we should probably keep it this way.
