### ISSUE TITLE
service-worker.d.ts....

### ISSUE THREAD

**Issue by johnnyreilly** [slightlyoff/ServiceWorker#576]
Hullo good people!

I help out with [DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) (the home of TypeScript type definitions).  I'm mighty excited about Service Worker and since no-one else seemed to have tacked it I'd started putting together a type definition for Service Worker called service-worker.d.ts.

I'd got embarrassing far through creating a def based on the [spec](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/) before I noticed this:

https://github.com/slightlyoff/ServiceWorker/blob/master/service_worker.ts

Which looks mighty like a TypeScript implementation of ServiceWorker.  

Question: Is it useful for you to have me put this definition together and put it on DefinitelyTyped?  If so would it make more sense for me to ditch my own efforts and instead use ```service_worker.ts``` as a basis for this (assuming you're happy with that)?

FWIW I'm building this mostly because I'm excited by what Service Worker looks likely to bring to the table and also because I love TypeScript.  All the best!

**Comment by wintersommer** [comment]
Have you already submitted a serviceWorker.d.ts to DefinitlyTyped ? i would be interested

**Comment by johnnyreilly** [comment]
I haven't as I'm guessing it may be out of date by now - feel free to take mine from the linked repo though.  Go forth and conquer!

**Comment by jakearchibald** [comment]
The `.ts` is gone!

**Comment by johnnyreilly** [comment]
So it has! Where did it go? :smile:

**Comment by olemartinorg** [comment]
Since this still is the top result on Google, let's be helpful:
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/service_worker_api

**Comment by johnnyreilly** [comment]
Thanks!

**Comment by rektide** [comment]
That's gone too. :)
