### ISSUE TITLE
A programmatic and reliable way to unregister all ports (even it's used from others tabs)

### ISSUE THREAD

**Issue by h2non** [slightlyoff/ServiceWorker#579]
I'm reviewing the spec and I cannot be sure if that's programmatically possible.

The requirement is simple: a way to close/unregister all ports using the same service worker (like in shared workers it can be done), usually dispatched by a `postMessage()` from one of it's consumers

**Comment by h2non** [comment]
@jakearchibald Thanks for the reply

If you take a look at this experimental library you will fastly take an idea about what I'm looking for...
https://github.com/h2non/bock

The idea is, essentially, to have more programmatic control about the worker live-cycle, to behave accordly from the worker consumer side, for example to react properly when the worker was eventually shutdown, in order to proceed with the scope synchronization, since the worker isolated scope was flushed. The need is not new in thread based programming: deal with data and state synchronization across thread.

Indeed, web workers are strongly isolated by design, and that's fine, but also should provide alternative  ways to make this more easy, specially in the case of Service Workers by its live-cycle nature

**Comment by jakearchibald** [comment]
We don't use message channel ports, so this is redundant.
