### ISSUE TITLE
Privacy consideration about the "cache" parameter of the Request object

### ISSUE THREAD

**Issue by tyoshino** [slightlyoff/ServiceWorker#585]
(Copied from https://github.com/slightlyoff/ServiceWorker/issues/398#issuecomment-66421199)

Let's start reviewing new functionalities carefully from security point of view.

I'm concerned that fetch() with the cache parameter set to e.g. the only-if-cached option may cause privacy leak. Like CSS :visited (http://dbaron.org/mozilla/visited-privacy), could it be abused to probe if a certain site was visited by the user?

**Comment by annevk** [comment]
@mayhemer @nikhilm @mnot any thoughts? I kind of like preserving the functionality for same-origin, but that also adds some complexity (e.g. rejecting cross-origin redirects).

**Comment by mnot** [comment]
same-origin makes sense if it's a significant attack. I'm not sure it is -- how is this qualitatively different than timing the cache, or just examining the Date in the response (subject to clock skew)?

AFAICT the only differences are:

* It gives a slightly higher degree of confidence, but any decent heuristics on the timing + response are going to give a very high degree of confidence anyway...

* It doesn't allow information about the probing to escape to the server. That's a little more concerning, but OTOH a single request that is the same as any legitimate request -- except that it doesn't happen as part of a page load -- is unlikely to be useful in actually stopping the attack.

**Comment by mayhemer** [comment]
For cross-origin 'without credentials' (the default) XHRs Gecko is using a distinct cache area called 'anonymous'.  There is more - the anonymous context means to not send out any authorization headers, cookies, and to not use the standard cache (that is populated when you visit the page/load the resource as part of the page content.)

We could do the same here?

**Comment by mattto** [comment]
Cache control options are tracked in https://crbug.com/453190

**Comment by annevk** [comment]
This issue moved here: https://github.com/whatwg/fetch/issues/39 (There's also several other issues around cache in that repository, if anyone can solve them, please!)
