### ISSUE TITLE
Default scope to register()

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#595]
Currently the default scope is "/" which will likely result in failure due to the path restriction. There was some suggestions to revise it around https://github.com/slightlyoff/ServiceWorker/issues/468#issuecomment-60584294 but it seems not decided yet.

Chrome is happy making it something like "./". I'm not actually sure the difference between './' and new URL('./', scriptURL).href

**Comment by mattto** [comment]
I think it's ok for the default url and base url to be unrelated. ie., the following seems acceptable to me:

// example.com/foo/page.html
sw.register("bar/sw.js"); // scope == "/foo/bar/"
sw.register("bar/sw.js", { scope: "./" }); // scope == "/foo"

Anyway, this should be decided as soon as possible, as changing it later will likely break sites.

**Comment by jungkees** [comment]
> I think it's ok for the default url and base url to be unrelated.

Agreed. The default url for a scope seems more like just a constraint than a general rule for parsing scope urls.

/cc @jakearchibald @slightlyoff @annevk

**Comment by jungkees** [comment]
The default scope text has been sorted out, and the security condition for checking a scope against the location of the script url has been added: f23c1d4e566847feebcfee8814132b0f8a8d56f1.

**Comment by jakearchibald** [comment]
Agreed with @mattto's example, spec look good too!

**Comment by KenjiBaheux** [comment]
Shall this bug be closed?

Spec changes tracking note:
 - fixed in Blink (M41 via https://code.google.com/p/chromium/issues/detail?id=445154#c4).

**Comment by jungkees** [comment]
Yes, it's done! Closing.
