### ISSUE TITLE
location.reload(true) should reload without ServiceWorker

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#597]
This would allow scripts to trigger a reload without SW, which could be a useful panic-button, or to tools such as browsersync.

**Comment by annevk** [comment]
1) Boolean arguments are bad. 2) The location API is full of sorrow. 3) This particular part of the location API already has a bunch of special cases, how would such an argument affect them?

**Comment by jakearchibald** [comment]
The argument isn't new

**Comment by jakearchibald** [comment]
Hmm, it's not in the spec, let me double check I'm not just making shit up

**Comment by jakearchibald** [comment]
Hmm, it's not spec'd, but AKAIK it's well supported https://developer.mozilla.org/en-US/docs/Web/API/Location.reload

**Comment by annevk** [comment]
Filed https://www.w3.org/Bugs/Public/show_bug.cgi?id=27764 on HTML.

**Comment by jakearchibald** [comment]
Ta!

**Comment by Hixie** [comment]
It seems it's just a Gecko thing.

I would strongly recommend not trying to reuse this API. It's probably fraught with compatibility issues.

**Comment by jakearchibald** [comment]
Given `.reload(true)` isn't in the spec & is only supported by Gecko and they're [considering removing it](https://bugzilla.mozilla.org/show_bug.cgi?id=1037721)… nahhhhhhhhhh
