### ISSUE TITLE
Do not want ServiceWorker to interrupt a specific request

### ISSUE THREAD

**Issue by vigneshshanmugam** [slightlyoff/ServiceWorker#598]
Is there any way we can skip a request from being captured by SW?.

In the case of 304 - Not Modified status code responses, I do not want service worker to interrupt the request and tell what the browser should do. Just an Example. 

I don't want to incur the additional cost performed by the SW.

**Comment by wanderview** [comment]
Can you design your app so that the URL of the "no sw request" is outside the SW scope?

**Comment by vigneshshanmugam** [comment]
But that might solve only for specific cases. Not for all of them.

**Comment by annevk** [comment]
We might offer this in the future. For now the idea is to let the SW handle all fetches and see how it goes.

**Comment by domenic** [comment]
> I don't want to incur the additional cost performed by the SW. 

Have you measured this cost? Numbers would be helpful in convincing engineering teams that your problem is real enough to allocate resources toward solving.

**Comment by wanderview** [comment]
If you measure this please keep in mind there will be a slow path and a fast path.  If the ServiceWorker is shtudown and the UA has to spin it up then there will likely be more delay.  Content doesn't really have a (designed) way to control whether you hit this condition or not.

**Comment by vigneshshanmugam** [comment]
@domenic : Sure will create a sample use case and post the numbers here. 

@wanderview : Got it :+1:

**Comment by jakearchibald** [comment]
> In the case of 304 - Not Modified status code responses, I do not want service worker to interrupt the request and tell what the browser should do

I don't really understand this. You want to avoid the SW based on something in the response? Do you mean:

* Make request without ServiceWorker
* Wait for response
* If response has status 304, get response from the http cache and abort these steps
* Call the SW's fetch event…

Given that the SW may also make a network request, this feels potentially a lot slower.

**Comment by vigneshshanmugam** [comment]
@jakearchibald : Nope not in that sense. 

I meant to skip that request from being tracked down by SW itself.

**Comment by jakearchibald** [comment]
So, not in the case of 304 - Not Modified status code responses, you want to do that in the case of any response?

**Comment by vigneshshanmugam** [comment]
@jakearchibald : Let me iterate with an example. 

Assume we are loading index.html and it has static file App.js which has the cache-control header set to 1 year and Last-Modified header set to yesterday. In this case, both the browser and server are smart enough to handle the 304 response loading it from the cache. 

So in this case, I don't want SW to interrupt the request. I want to skip this request as such and let browser handle it.

**Comment by jakearchibald** [comment]
This can be handled today by not calling `event.respondWith`.

The performance impact of this should be low, as the ServiceWorker should already be awake from loading the HTML. If it turns out to be slow, we can solve this (and more) with a static routing API, but we don't want to introduce this optimisation unless we have proof that it needs optimising.
