### ISSUE TITLE
Errors inside Promises are not thrown

### ISSUE THREAD

**Issue by boopathi** [slightlyoff/ServiceWorker#600]
Also, reported this bug here, https://code.google.com/p/chromium/issues/detail?id=448281 

```javascript
this.addEventListener('install', function(event) {
	event.waitUntil(
		caches
			.open('demo')
			.then(function() {
				throw new Error('Blah Blah');
			})
	);
});
```

doesn't throw the error. It is being caught somewhere.

Also, whenever this error happens, the service worker is registered and immediately unregistered. And when refreshing the page, a new worker with an incremented version ID is registered and the same happens because of the error, and this error is never thrown. These errors cause creation of new workers and the source of the error remains unknown.

![screenshot 2015-01-13 11 28 55](https://cloud.githubusercontent.com/assets/294474/5716701/8839d19a-9b19-11e4-8628-f1705c1a6fa3.png)
![screenshot 2015-01-13 11 29 15](https://cloud.githubusercontent.com/assets/294474/5716700/8837498e-9b19-11e4-92e0-7cfaa1e28c8e.png)

**Comment by domenic** [comment]
You need to use .catch(function (err) { /* use the error */ }) to catch promise errors.

**Comment by boopathi** [comment]
Yes. But, shouldn't all uncaught errors should be thrown and be notified in the console ?

**Comment by boopathi** [comment]
My bad. Got used to Bluebird Promises. Native ES6 Promises don't throw.

```javascript
Promise
  .resolve()
  .then(function(){
    throw new Error('asdf');
  });
```

Bluebird:
http://jsbin.com/kahuzi/1/edit?html,js,console

native ES6:
http://jsbin.com/qivobibowa/3/edit?html,js,console

**Comment by boopathi** [comment]
The only problem is that the debugger tools doesn't allow me to see the unhandled exceptions.
