### ISSUE TITLE
Is the ServiceWorker also a client?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#603]
…and should it show up in `clients.getAll({ includeUncontrolled: false, type: 'all' })`?

I think yes, even a reference to itself would turn up in that case.

**Comment by annevk** [comment]
What would it message with? The whole point of a Client object is having something to message with.

**Comment by jakearchibald** [comment]
`ServiceWorkerGlobalScope` has `onmessage`, so `client.postMessage` should work fine. But I feel I've misunderstood the question.

**Comment by annevk** [comment]
The problem is that a service worker is not itself controlled by a service worker, so a `Client` object would not make sense.

**Comment by jungkees** [comment]
> a service worker is not itself controlled by a service worker, so aClient object would not make sense.
 
Yeah, I thought so too.

**Comment by wanderview** [comment]
Tracked in gecko here:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1130687
