### ISSUE TITLE
Timing of events relative to initial script load

### ISSUE THREAD

**Issue by wibblymat** [slightlyoff/ServiceWorker#605]
Let's say I have the following worker:

```javascript
var myCache;
caches.open('my-cache').then(function (cache) {
  myCache = cache;
});

self.oninstall = function(event) {
  event.waitUntil(myCache.add('index.html'));
};
```

Are there any guarantees about the order of operations? Specifically, will the promise created during script load, that sets the `myCache` variable, be resolved before the `install` event is triggered?

I'm guessing that, no, this is a race condition, and you can't rely on it. But it limits the useful setup work that can be done when a script is restarted. You can't defer boilerplate stuff to `install` or `activate` for scripts that are just being restarted.

**Comment by jakearchibald** [comment]
There are no guarantees here, it's the same as events in a window.

You'd need to use:

```js
self.oninstall = function(event) {
  event.waitUntil(
    caches.open('my-cache').then(function(myCache) {
      myCache.add('index.html')
    })
  );
};
```

ES7 async functions make it look more like sync code:

```js
self.oninstall = function(event) {
  event.waitUntil(async function() {
    var myCache = await caches.open('my-cache');
    return myCache.add('index.html');
  });
};
```

You can use that today using either https://github.com/google/traceur-compiler or https://6to5.org/
