### ISSUE TITLE
Remove registration from Client?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#608]
I added this in the original design, but it doesn't fit with the static nature of the rest of the object.

I propose removing it, we can add it back later if needed, or something like `client.getRegistration()`.

@mounirlamouri does this work for you?

**Comment by mounirlamouri** [comment]
lgtm. I actually did not notice this addition and it's not implemented so far ;)

**Comment by jungkees** [comment]
Addressed: cf2e59a16483b3bec796a2f34f5728d4410df84a.

**Comment by jungkees** [comment]
Closing.
