### ISSUE TITLE
Rename clients.getAll()

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#610]
…since it has filtering options that filter by default.

@annevk suggested `.get()`, but does that suggest a singular return?

Could be `.matchAll()` like the caches.

**Comment by jungkees** [comment]
`.get()` sounds more like getting a singular result.
`.getAll(options)` still LGTM as it suggests "get all the clients which meet the options which are happen to be _controlled_ _window_ for convenience."
But in case people still think it's not natural, `.matchAll()` seems fine to me too.

**Comment by KenjiBaheux** [comment]
Proactively filed crbug.com/451334 for Blink, pending a decision.

**Comment by jakearchibald** [comment]
@annevk still unhappy with `getAll`? Other suggestions are `matchAll`, `queryAll`.

**Comment by annevk** [comment]
I don't see how `All` makes sense given that it doesn't return all of them by default. Also, none of those names signifies that you are getting back copies rather than references.

**Comment by mvano** [comment]
How about just `filter` or `match`?

**Comment by slightlyoff** [comment]
@mvano: would we need to pun `filter` with `Array.prototype.filter`?

I'll go with whatever this group likes, but @mvano's `match` and `.matchAll()` as previously suggested sound good to me. They're at least internally consistent with the identity semantics that @annevk is worried about.

**Comment by mvano** [comment]
> would we need to pun filter with Array.prototype.filter?

Not sure what pun means in this context, but I recognize the potential confusion of having a method with the same name but different functionality on different classes. The same issue exists with `String.prototype.match`. I don't find this a major issue though. In an object oriented design you have natural namespacing and no real conflict.

**Comment by inexorabletash** [comment]
Since we're bikeshedding... how about `getClients()` ?

**Comment by jakearchibald** [comment]
Lets go with `matchAll`. Matches `caches.matchAll` which has a similar arg with filtering rules.

**Comment by wanderview** [comment]
Tracked in gecko here:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1130685

**Comment by ZhuoyuQian** [comment]
Commit a CL here:
https://codereview.chromium.org/892053003/
