### ISSUE TITLE
How to set the client for the requests initiated from within user agent's internal context?

### ISSUE THREAD

**Issue by jungkees** [slightlyoff/ServiceWorker#615]
https://github.com/slightlyoff/serviceworker/issues/404#issuecomment-72806964

As of now, a request's client / a service worker client is defined as an environment settings object. However, Fetch and Soft Update should deal with those requests initiated from within user agent's internal context.

**Comment by jakearchibald** [comment]
Can these requests ever reach a ServiceWorker?

**Comment by jungkees** [comment]
I don't think they do, but currently their client value is set to an empty environment settings object in Soft Update algorithm and used in Fetch algorithm.

**Comment by wanderview** [comment]
Would this also effect something like push notifications where there might not be an environment easily available?

**Comment by jungkees** [comment]
I don't think they would because the trusted events used in push/notifications don't involve any environment settings object. The problem here is Fetch has been designed assuming clients for its input requests would be those environment settings objects, but SW's Soft Update algorithm invoked inside user agents' internal context also invokes Fetch.

**Comment by annevk** [comment]
Fetch now allows for request's client to be null.

**Comment by jungkees** [comment]
Changed to set the request's client to null in those UA initiated updates: cfc485ed4099348721bc19bd18ef5a9582e0aae4.

**Comment by KenjiBaheux** [comment]
Tracked in blink via https://code.google.com/p/chromium/issues/detail?id=466413

I'm assuming that this is purely internal stuff with virtually no impact on compatibility but correct me if I'm wrong.

**Comment by jungkees** [comment]
Yes, you're right. It's a change in Fetch spec so it can embrace the requests whose environment is not defined i.e. null. (such as those requests initiated from UA internal contexts.)
