### ISSUE TITLE
Remove prefixMatch from CacheQueryOptions

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#617]
Implementor feedback from both Chrome & Firefox suggests this will be a de-opt case.

I added it to the spec to implement the kind of prefix matching appcache had in FALLBACK rules, but I can't say I've used it in practice in demos and apps.

We can add it back later if we see devs recreating this & we think the browser can do it faster.

@wanderview is getting further Mozilla feedback, if he gives the go-ahead, let's remove it.

**Comment by wanderview** [comment]
Yea verily, make it so:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1130452
