### ISSUE TITLE
Use SyntaxError when an URL can't be parsed in Clients.openWindow()

### ISSUE THREAD

**Issue by mounirlamouri** [slightlyoff/ServiceWorker#619]
A lot of specifications uses SyntaxError for that purpose. The only ones that don't are URL and Fetch. I still do not understand why we want to move all errors to TypeError. Meaningful error are for the best.

**Comment by annevk** [comment]
Please provide pointers.

**Comment by annevk** [comment]
Note that `"SyntaxError"` is not super useful since it means something completely different in the context of JavaScript.

**Comment by domenic** [comment]
Yes, SyntaxError should only be used for JavaScript syntax errors.
