### ISSUE TITLE
Confusing use of `transforming with` and `Upon fulfillment`.

### ISSUE THREAD

**Issue by jyasskin** [slightlyoff/ServiceWorker#621]
Several algorithms contain steps like the following two:

1. Let p be [transforming responseArrayPromise with onFulfilled](http://www.w3.org/2001/tag/doc/promises-guide#transforming-by).
1. [Upon fulfillment of p with value](http://www.w3.org/2001/tag/doc/promises-guide#upon-fulfillment) responseArray, perform the following substeps, onFulfilled, in parallel:

`onFulfilled` isn't defined except in the _Upon fulfillment_ substeps, but it's odd to see it used twice. In some cases, like [add()](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-add-method), the second use is inconsistent because it tries to resolve the already-fulfilled promise. Some other cases, like [addAll()](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-addAll-method), define `onFulfilled` twice, in different ways.

I suspect you don't mean to use "Upon fulfillment" after "transforming" at all.

**Comment by jyasskin** [comment]
@domenic to check our understanding of the shorthand phrases.

**Comment by jungkees** [comment]
Thanks for spotting it, @jyasskin. Some part of the shorthand expressions were redundant as you pointed. (The example in the original comment was not redundantly phrased but should have been simplified.) Also, I removed the name of the handler, onFulfilled, as it's not need.

@domenic review would be appreciated: 5aa0ca22a948cdb6934e79a5a7750adaec859f44. I believe returning values from within a fulfillment handler to resolve the transformed promise is a right usage, right? I've done that a lot referring to the example 2 in http://www.w3.org/2001/tag/doc/promises-guide#shorthand-reacting.

**Comment by domenic** [comment]
5aa0ca22a948cdb6934e79a5a7750adaec859f44 LGTM. And yeah, returning or throwing in the handler is perfect.

**Comment by jungkees** [comment]
Closing. Other incorrect usages have been addressed in https://github.com/slightlyoff/ServiceWorker/issues/627 and https://github.com/slightlyoff/ServiceWorker/issues/628.
