### ISSUE TITLE
Cache and Request objects

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#624]
It's not entirely clear to me how this works right now. E.g. does `keys()` always return clones? (The text for `keys()` is most certainly wrong.)

I think that perhaps we should introduce `RequestKey` or some such and introduce a mixin that `Request` and `RequestKey` can share. And ways to create a `RequestKey` from a `Request` (and vice versa?). That way caches never have to deal with request that has an associated body.

**Comment by wanderview** [comment]
Is it reasonable to leave off the Request body if we want to support POST methods in the Cache in the future?

See this previous comment from @jakearchibald:

https://github.com/slightlyoff/ServiceWorker/issues/550#issuecomment-62903942

**Comment by jakearchibald** [comment]
> does keys() always return clones?

Yeah. 

> That way caches never have to deal with request that has an associated body.

I've heard people ask for a way to store post requests, especially if (a clone) failed to complete, maybe indexedDB is a better place for these, although you run into the same clones issue.

**Comment by wanderview** [comment]
They just want to store the POST requests, but not match on them?

**Comment by jakearchibald** [comment]
Yeah, that's another reason for them to not be in the cache

**Comment by annevk** [comment]
Since the cache does not support anything but `GET` and `HEAD`, and `Request` does not support bodies for `GET` and `HEAD`, I think we would only need to revisit this issue if we ever change one of those invariants.
