### ISSUE TITLE
Use of Upon fulfillment/rejection in CacheStorage.match is incorrect

### ISSUE THREAD

**Issue by jyasskin** [slightlyoff/ServiceWorker#627]
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#cache-storage-match-method has:

> 1. Return the result of transforming ... with a fulfillment handler that ...:
>   1. For each key in keys:
>     1. Let q be [a promise returned by ...]
>     1. Upon fulfillment of q with value matchedResponse:
>       1. If matchedResponse is not undefined, return matchedResponse.
>     1. Upon rejection of q with value err:
>       1. Throw err.
>   1. Return undefined.

Upon Fulfillment/Rejection handlers call `q.then`, but they don't do anything with the returned promise, so the values returned and thrown in those handlers don't wind up getting used. This Else branch is always going to fulfill with `undefined`, which probably wasn't intended.

**Comment by jungkees** [comment]
Corrected the steps: 7751742c2aac7ea2bb764faee1accc16b7d4f4de. Now it intends to resolve with the first matching response (from the Cache object iterated in the key insertion order) from the promise chain. It resolves with undefined when there's no match.

**Comment by jyasskin** [comment]
50b805ff804f514dafba9d7a1630302a3e13c06e changes the steps, but I think they leave _p_ referring to the last matching response rather than the first. I don't see anything breaking out of the 'for each'.

You also don't need a rejection handler that throws its argument. That's the default.

**Comment by jungkees** [comment]
'For each' just builds the promise chain. And when one of the fulfillment handlers in the chain returns a promise which eventually resolves with a non-undefined value (i.e. a matched Response object), it makes all the following fulfillment handlers return the same value till the last one. So I think the first matched response will be the final value for the returned promise. Am I missing something?

> You also don't need a rejection handler that throws its argument. That's the default.

Yes. It's removed: 37064b621ff13da9c5f20b7cc0f3717dfb8a70a4.

**Comment by jyasskin** [comment]
Aha! Yes, "If v is not undefined, return v." covers this. Thanks!
