### ISSUE TITLE
Activate uses "Wait for X to settle" inside a synchronous task.

### ISSUE THREAD

**Issue by jyasskin** [slightlyoff/ServiceWorker#628]
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#activation-algorithm has:

1. ...
1. Queue a task to run the following substeps:
  1. ...
  1. Wait until p settles.

Tasks run in the main JS event loop, so they can't block.

**Comment by jungkees** [comment]
Fixed: 7751742c2aac7ea2bb764faee1accc16b7d4f4de. Thanks.
