### ISSUE TITLE
Should Request constructor be less destructive when it fails?

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#629]
@wanderview @nikhilm @jakearchibald should we try to make the constructor not nuke a passed in object if the constructor algorithm results in an error? It seems somewhat cleaner to do that.

**Comment by wanderview** [comment]
I think that would be nice for developers, yes.

**Comment by jakearchibald** [comment]
Agreed

**Comment by wanderview** [comment]
Tracked in gecko:  https://bugzilla.mozilla.org/show_bug.cgi?id=1134609
