### ISSUE TITLE
Passing a scope or scriptURL to register() with escaped '/' or '\  should fail

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#630]
Depending on the server configuration, it's possible for someone to easily break the path restriction: put a script at /users/~mattto/sw.js then register('/users%2f~mattto%2fsw.js', { scope: '/' }).

Of course, the path restriction is inherently not very secure, but this happened in the wild and Chrome now rejects register() calls with escaped slashes in scope or scriptURL.

**Comment by mattto** [comment]
(hit enter too early)

Depending on the server configuration, it's possible for someone to easily break the path restriction: put a script at /users/~mattto/sw.js then register('/', '/users%2f~mattto%2fsw.js') passes is accepted.

Of course, the path restriction is inherently not very secure, but this happened in the wild and Chrome now rejects register() calls escaped slashes in scope or scriptURL.

**Comment by annevk** [comment]
Sigh. I hate this path / scope thing so much.

**Comment by jakearchibald** [comment]
If we didn't have scope, this problem wouldn't go away, as we'd still need to enforce this for whatever boundary fetch got.

**Comment by wanderview** [comment]
I think rejecting is the easiest protection against these broken servers right now.  We can relax the restriction in the future if necessary.

**Comment by jakearchibald** [comment]
Agreed on reject if there's `%2f` in the pathname. Thanks broken servers.

**Comment by nhiroki** [comment]
Tracked in http://crbug.com/513622
(Current Blink implementation rejects such paths with SecurityError)

**Comment by jungkees** [comment]
I think it's more like a `TypeError` as we don't inspect the relative locations of the escaped strings in the paths of _scriptURL_ and _scope_. E.g, `register('/users%2f~mattto%2fsw.js', { scope: '/users%2f~mattto%2f' })` also rejects.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1187347

**Comment by annevk** [comment]
Yeah, `TypeError` seems better. No reason to branch on this.
