### ISSUE TITLE
Make FetchEvent.prototype.client nullable

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#631]
E.g. for `sendBeacon()` or `ping=""` there might no longer be a client environment to expose.

(Incidentally, those also do not really care about a response, do we want to expose that differently?)

**Comment by annevk** [comment]
Also consider the case of navigating to a URL controlled by the service worker. There's no client environment created to receive messages from until the service worker responds. In that case there cannot be a `Client` object either, right?

**Comment by jungkees** [comment]
> E.g. for sendBeacon() or ping="" there might no longer be a client environment to expose.

As the type of the _client_ concept is defined as an environment settings object. Either _null_ or _empty environment setting object_ seems to work here.

> Also consider the case of navigating to a URL controlled by the service worker. There's no client environment created to receive messages from until the service worker responds. In that case there cannot be a Client object either, right?

It's confusing. Although the client environment for this requested resource (client request) has not been created, shouldn't `FetchEvent.prototype.client` return a Client object that represents the event's request's client?

**Comment by annevk** [comment]
What is an empty environment settings object? And what does that mean for `client`?

> Although the client environment for this requested resource (client request) has not been created, shouldn't FetchEvent.prototype.client return a Client object that represents the event's request's client?

How does that work? What does `postMessage()` do? (I see in the specification you have linked `postMessage()` to the definition for window's `postMessage()`. That's bogus. You need to define it yourself.

**Comment by annevk** [comment]
Where does the specification define the steps to create a `Client` object? Surely you cannot create one before you have created the environment?

**Comment by jungkees** [comment]
> What is an empty environment settings object? And what does that mean for client?

Just an empty object in case it makes more sense to give it a symbolic name than null. It should mean null for `client` I think.

> How does that work? What does postMessage() do?
My question is not about how it works but what the `client` should be conceptually? And you can `postMessage()` to a Client object that represents the event's request's client like as you can with the Client objects gotten from `self.clients.matchAll({ includeUncontrolled: true })`.

> (I see in the specification you have linked postMessage() to the definition for window's postMessage(). That's bogus. You need to define it yourself.

Agreed.

> Where does the specification define the steps to create a Client object? Surely you cannot create one before you have created the environment?

Yes, you cannot create one before having a client environment. My thought for the 'FetchEvent.prototype.client`'s value for `client requests` was not about creating one without a client environment, but creating one for the event's request's client. (rather than the one for the requested resource.)

Re the steps to create `WindowClient`, [Capture Window Client](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#capture-windowclient-algorithm) does that.

For `Client` objects need to be created during Handle a Fetch, I found I need to update the related text.

**Comment by annevk** [comment]
We haven't really explored navigation in detail yet, but I guess across origins we can't reveal the client so request's client would be null. That's something that's not clearly defined at the moment of course...

**Comment by annevk** [comment]
(Conceptually `Client` objects are not an exact match for request's client, for one because the latter can be a service worker at the moment. Perhaps we should align that somehow, but I'm not sure how. Call mine request's environment?)

**Comment by jakearchibald** [comment]
Having a client for `sendBeacon()` or `ping=""` seems fine to me. Yes, the client may be gone, but that's always possible with clients. You can `clients.getAll(c => c[0].focus())` and have the client shut down before it works (meaning the promise rejects).

For navigations, I agree the client should be null. If you respond with a `Content-Disposition` header, a scriptable client isn't created.

**Comment by annevk** [comment]
That seems reasonable, but in the case of `sendBeacon()` et al you might have to synthesize it out of thing air. Might not be too hard though but at least some of the internal slots the `Client` object has now need some tweaking.

**Comment by jakearchibald** [comment]
Can a beacon request be initiated after https://html.spec.whatwg.org/#discard-a-document of the client?

**Comment by annevk** [comment]
Why not? That's the whole point no?

**Comment by jungkees** [comment]
F2F:
* Need change to nullable for navigation

**Comment by jungkees** [comment]
Closing this issue in favor of the resolution https://github.com/slightlyoff/ServiceWorker/issues/723#issuecomment-123516555. We'll not synchronously get the client in a newly designed API. The nullable state that the prospective async API will possibly return will be addressed during the algorithm work.
