### ISSUE TITLE
Why would `WindowClient` ever have `frameType` of `none`?

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#632]
"frame type" as defined in Fetch is meant for all environments, including works. That's why we have `none`. Or did I forget something?

**Comment by jakearchibald** [comment]
I can't think of a case where it would be 'none'.

Maybe we should move `frameType` to `Client`, where it can be `none`.

**Comment by jungkees** [comment]
Yeah, moving it to Client makes sense. Authors could filter out worker clients by that also.

**Comment by jungkees** [comment]
Fixed: 6dfce0aacceeef41c813c4680c7f67b96f80c4b6.

**Comment by KenjiBaheux** [comment]
Tracked in crbug.com/463800 for blink.
