### ISSUE TITLE
Capture Window Client cannot use attributes/methods directly

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#633]
You need to use the internal algorithms these attributes/methods are proxies for. Otherwise JavaScript manipulating them would influence your specification.

**Comment by jungkees** [comment]
You mean it can be influenced by `Function.prototype.call(this, ...)` or something like that?

Could you let me know what would be a good practice for example? Like for the `hadFocus()` method referred to in this algorithm, is it a right way to specify the same steps [defined in HTML](https://html.spec.whatwg.org/multipage/interaction.html#dom-document-hasfocus) as-is? Or any better way?

**Comment by annevk** [comment]
You should probably ask @Hixie if he can make that algorithm abstract so you can refer to it. There's also some way to capture the algorithm the moment the global is created before any scripts are executed, but that's rather cumbersome.

**Comment by jungkees** [comment]
Filed: https://www.w3.org/Bugs/Public/show_bug.cgi?id=28090
/cc @Hixie

**Comment by jungkees** [comment]
I'll make a PR for this in HTML.

**Comment by jungkees** [comment]
Made a PR: https://github.com/whatwg/html/pull/308.
