### ISSUE TITLE
client objects should have an .id

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#634]
`client.id` would be a guid allowing the ServiceWorker to track client objects between SW termination & restart.

**Comment by jungkees** [comment]
Spec'ed it as an internal slot belongs to a service worker client and `Client.id` returns that value: 445076da699c097d9ac08739e2b7902c0959bc55.

**Comment by kinu** [comment]
Tracked in crbug.com/464668 for blink.  /cc @KenjiBaheux

**Comment by slightlyoff** [comment]
LGTM.
