### ISSUE TITLE
ServiceWorker objects should have an .id

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#635]
`serviceWorker.id` would be a guid allowing the ServiceWorker to track other ServiceWorker objects between SW termination & restart.

**Comment by jakearchibald** [comment]
The GUID should remain the same for that ServiceWorker throughout its existence within the registration.  It shouldn't change when the SW is terminated and rerun.

**Comment by jungkees** [comment]
Spec'ed it as an internal slot belongs to a service worker and `ServiceWorker.id` returns that value: 445076da699c097d9ac08739e2b7902c0959bc55.

**Comment by slightlyoff** [comment]
LGTM.

**Comment by KenjiBaheux** [comment]
Tracked via crbug.com/470031 for Blink.
