### ISSUE TITLE
When exactly during unload does "Handle Service Worker Client Unload" run

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#636]
https://bugzilla.mozilla.org/show_bug.cgi?id=1136066

**Comment by jakearchibald** [comment]
The intent is for "Handle Service Worker Client Unload" to run once the document may no longer call fetch or interact with the ServiceWorker via script.

The "other applicable specifications" bit of step 2 https://html.spec.whatwg.org/#discard-a-document feels like a good fit.
