### ISSUE TITLE
FetchEvent.forwardTo is completely unspecced

### ISSUE THREAD

**Issue by jdm** [slightlyoff/ServiceWorker#637]
Why is it still listed in the WebIDL?

**Comment by slightlyoff** [comment]
It needs to be there because there's no other way to handle forwarding; but yes, it needs spec language.

**Comment by annevk** [comment]
If by forwarding you mean redirecting there is totally a way. It's called `Response.redirect()`...

**Comment by jakearchibald** [comment]
This was an oversight, thanks for catching it
