### ISSUE TITLE
client.focus() should reject if tab failed to focus

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#640]
Feels like an exceptional case.

**Comment by slightlyoff** [comment]
Agreed.

**Comment by jungkees** [comment]
I'm getting my head around to finding a point where the [focusing steps](https://html.spec.whatwg.org/multipage/interaction.html#focusing-steps) algorithm (invoked at [`client.focus()`](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#client-focus-method) step 3.2.1) can be said to have been failed. It seems it silently fails case by case by just aborting the steps. @annevk could you help? Any good way to get the failure from that?

**Comment by jakearchibald** [comment]
Would it open us up to race conditions if it was along the lines of:

1. Run focusing steps
2. If client hasFocus resolve true
2. Else resolve false

**Comment by annevk** [comment]
Resolve != reject, but something like that might work I think.

**Comment by jakearchibald** [comment]
Ugh, yes, I meant reject not resolve false. Stupid brain to hands error.

**Comment by jungkees** [comment]
Used the focus state internal slot to check the result. Thanks for comments!
