### ISSUE TITLE
FetchEvent not defined

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#645]
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#fetch-event-section does not seem to define the various attributes of the FetchEvent object.

**Comment by jungkees** [comment]
Right. I put them in my queue. Thanks for the reminder.

**Comment by jungkees** [comment]
Addressed: 02fa27ba05ab0901f24dfe08961a76fbbbbf817f.
