### ISSUE TITLE
openWindow(url)'s same origin check should be done against the origin of the final response's url?

### ISSUE THREAD

**Issue by jungkees** [slightlyoff/ServiceWorker#646]
Pointed out by @inexorabletash at https://codereview.chromium.org/984853003/diff/1/content/browser/service_worker/service_worker_version.cc#newcode1155:
> An on-origin request could end up redirecting to an off-origin location. An off-origin request could
end up redirecting to an on-origin - even controlled - location.

We're currently checking it against the origin of the original request's url. (step 5.4 of [openWindow](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#clients-openwindow)) Should we check it against the origin of the final response's url?

**Comment by annevk** [comment]
Even then you could get a redirect or what if that navigates through <a>.click()? Trying to restrict a Window to an origin seems like a rather novel primitive and discussion on blink-dev suggests it might go away. Might be best to just remove it from the specification.

**Comment by jungkees** [comment]
The title might make you confused. Let me clarify. The current spec actually allows cross-origin url for openWindow(url). The step 5.4 does the same-origin check (after the navigation is done - so after all the redirects, if any) just to resolve the returned promise with null rather than a WindowClient.

**Comment by annevk** [comment]
What if I navigate on a timer?

**Comment by inexorabletash** [comment]
FWIW, the way the blink impl worked was: when the newly opening window hit some step in the load process the SW backend was notified. At that arbitrary point, if the window was a controlled client, the promise is fulfilled with a client instance. Otherwise, the promise is fulfilled with null. That logic handled a redirect to another origin and/or out-of-scope, and IMHO was at least sane in the timer case (as in: similar to acquiring a client object, which is invalidated shortly thereafter by a timed navigation)

At the very least, that needs to be modified now that we have the notion of non-controlled clients.

Aside: should there be a 'controlled' bit on Client objects?

**Comment by jungkees** [comment]
> At the very least, that needs to be modified now that we have the notion of non-controlled clients.

Right. A `Client` object can capture any service worker client in the same-origin to the service worker. E.g. a `message` event posted by `registration.installing.postMessage` holds a non-controlled `Client` object in `e.source`.

> Aside: should there be a 'controlled' bit on Client objects?

Although we have a way to filter out non-controlled clients (`clients.matchAll`) already (that's the default behavior), adding `Client.activeWorker` can allow authors to check whether the retrieved clients are controlled or not and also which service worker those clients are controlled by. 

Not sure the use cases that need grasping uncontrolled clients are compelling tho.

cc/ @jakearchibald @slightlyoff

**Comment by jungkees** [comment]
F2F:
* Seems we need a hook from Navigate algorithm.
* Why can't we get a cross-origin client in this scenario?

**Comment by jungkees** [comment]
> Why can't we get a cross-origin client in this scenario?

The other existing methods like `clients.matchAll()` do not expose off-origin clients, either. Once a client navigates off-origin, it seems reasonable to not expose it for consistency.
