### ISSUE TITLE
Event queuing model for SW

### ISSUE THREAD

**Issue by jungkees** [slightlyoff/ServiceWorker#649]
@annevk has long been pointing out about the need for an external event queue to support SW lifecycle: https://github.com/slightlyoff/ServiceWorker/issues/290#issuecomment-44257645.

As the way I've spec'ed it is a bit different though, I'd like to have your feedback.

Here's the behavior:

1. Every lifecycle event or functional event triggers **Run Service Worker** algorithm
1. _Run Service Worker_ 
  1. If the service worker is already running, do nothing and abort the steps.
  1. Create separate execution context, environment settings object, global object, etc.
  1. Run the event loop specified by the environment settings object.
1. Queue a task to dispatch the event at the service worker

- So, it's not missing any event during a boot-up.
- The events are being queued up and handled while SW's running.
- All the events are extendable event (yeah FetchEvent will also be), so we can signal UAs to keep it up for those given promises' settlements. And have all the events queued up while it's alive.
- But we don't re-queue those events discarded when UA terminates a service worker.

WDYT?

**Comment by annevk** [comment]
Do you mean "abort the substeps" above?

Losing events seems really bad. We should not let that happen. One way could be to only handle new external tasks once the existing tasks have finished or resulted in service worker termination.

If someone creates a bunch of tasks in a running service worker that should not then lead to the next hundred network fetches getting lost if the UA decides upon termination.

**Comment by jungkees** [comment]
> Do you mean "abort the substeps" above?

Yes abort the rest of the steps in Run Service Worker. The steps in the above comment is just a snippet I put together to show the idea.

> Losing events seems really bad. We should not let that happen. 

Agreed on having to not let the events lost before getting dispatched. Curious to know whether the points you concern the events can be lost are before being dispatched or after queued in the service worker (in which case you might have meant lost by termination)?

> One way could be to only handle new external tasks once the existing tasks have finished or resulted in service worker termination.

By "the existing tasks" here, do you mean the tasks already queued in the service worker's responsible event loop's task queue? If so, what's the model in your mind that'd delay handling those new external tasks? Is that an external queue or trying to delay queuing a task somehow?

> If someone creates a bunch of tasks in a running service worker that should not then lead to the next hundred network fetches getting lost if the UA decides upon termination.

UA terminating a service worker seems it implies it's done with the tasks in the queue or met an abnormal operation. Should we really retain and requeue those bunch of tasks which may delay handling the new requests? Also backing up the dropped tasks by putting'em into the external queues again will get the order of the tasks tangled up.

On second thought, I'm open to the external queue idea if needed. An external queue associated with a service worker which persists the lifetime of it seems reasonable. But I'm not sure about whether we should requeue the dropped tasks when UA terminates the service worker. And also I'd like to mull over with all the possible models before coming to a conclusion.

**Comment by annevk** [comment]
The model I proposed was that the conceptual "queue external task" waits for a service worker's queue to be empty. However, that might be bad if a service worker supports task source, where e.g. the fetch task source has higher priority compared to everything else.

I'm not entirely sure what a good model would be. Perhaps just have some generic requirements if others cannot come up with something simple to say. But we cannot drop fetch tasks that have not been processed.

**Comment by jakearchibald** [comment]
Struggling to get a handle on this, so here's some use cases:

The browser has 100 fetch events queued, but the user navigates or hits "stop". Firing those 100 events would be wasteful, ideally the browser should be able to take them out of the queue. The SW may not be able to terminate, as the navigated-to page may also need the SW.

The browser has 100 fetch events queued, but the user closes the browser. Firing those 100 events is probably not possible, but they shouldn't be fired next time the browser opens - the reopening of the page will refire them.

The browser has fetches & push events queued while the activate event for the target ServiceWorker is underway. However the activation fails leaving the registration without an active worker. I guess the queue should remain at this point? Added this concern to https://github.com/slightlyoff/ServiceWorker/issues/659#issuecomment-87778808 - worried about a large buildup of events here.

The browser has 10 fetch events queued, 3 fired and awaiting response, and an additional push event with an unsettled waitUntil. The ServiceWorker crashes for reasons unknown. I think the three fetch events & push should be treated as if they were given a rejected promise. The SerivceWorker should restart and the queue should continue to process (the previously fired events are not rescheduled unless they typically do when their waitUntil/respondWith promise rejects, as is the case with one-off background sync).

Does that help any?

**Comment by jungkees** [comment]
There are two models that I can think of: (A) the discard-when-terminate model and (B) the external queue model.

(A) basically is this: https://github.com/slightlyoff/ServiceWorker/issues/649#issue-60629643. When terminate a worker is executed, it doesn't requeue the tasks. Those tasks are discarded as they are in dedicated workers / shared workers.

(B) needs task queue(s) associated with the registration. And the service worker's event loop should process the registration's task queue instead of its own task queue in a way. It'd be like:
A _service worker registration_ has an associated **task queue**.
A _service worker_'s _responsible event loop_ must process its _containing service worker registration_'s _task queue_ instead of its own _task queue_.
(I assumed the way it specifies makes sense. @annevk does it?)

(A) is simple. When terminate a worker is executed, the UAs can simply terminate those fetches and discard the tasks. Assuming the termination is an abnormal case (as we provide waitUntil, and all the operations are guided to be written async, etc), clients can easily recover by reload itself. Yeah, but the clients have to do that.

(B) The browsers (so and the clients) will not lose their events. But when the browser is closed and reopened, those unwanted events in the queue should be processed. (Maybe it can be an advantage to particular functional events like push?) Moreover, when the service worker's activation fails, a massive number of events may be piled up in the registration's task queue.

Thanks @jakearchibald for the use cases to think of. Here's my thought:
> The browser has 100 fetch events queued, but the user navigates or hits "stop". Firing those 100 events would be wasteful, ideally the browser should be able to take them out of the queue. The SW may not be able to terminate, as the navigated-to page may also need the SW.

(This issue seems orthogonal to both (A) and (B) I think.) Ideally yes. But I'm concerned that this requirement will add complexity like tasks having to maintain/access additional information about the request's client and the algorithm having to remove those corresponding tasks from random positions which may not be the top of the queue. Assuming all the queued tasks will do async jobs, I'm leaning to just let them be processed. The navigation or the user abort will terminate the ongoing fetches anyway.

> The browser has 100 fetch events queued, but the user closes the browser. Firing those 100 events is probably not possible, but they shouldn't be fired next time the browser opens - the reopening of the page will refire them.

Yes, this can be a disadvantage of (B). 

> The browser has fetches & push events queued while the activate event for the target ServiceWorker is underway. However the activation fails leaving the registration without an active worker. I guess the queue should remain at this point? Added this concern to #659 (comment) - worried about a large buildup of events here.

This is a disadvantage of (B). As @jakearchibald pointed, queuing (possibly) massive number of the functional events until the worker is successfully activated seems not plausible. (The current Handle Fetch (step 15.2) falls back to the network in this case.)

> The browser has 10 fetch events queued, 3 fired and awaiting response, and an additional push event with an unsettled waitUntil. The ServiceWorker crashes for reasons unknown. I think the three fetch events & push should be treated as if they were given a rejected promise. The SerivceWorker should restart and the queue should continue to process (the previously fired events are not rescheduled unless they typically do when their waitUntil/respondWith promise rejects, as is the case with one-off background sync).

(B) will do this. For (A), the clients should reload. (A push event should have been lost in this case.)

Thoughts?

**Comment by annevk** [comment]
I think (B) is still the better model, but you obviously need to GC some stuff and let other stuff be. If someone closes a client and that client has outstanding fetches, those fetches are terminated. We might need to have a check before we dispatch the `fetch` event to make sure that it has not been canceled.

**Comment by jungkees** [comment]
Implementers' feedback would also be appreciated.

/cc @mattto @coonsta @nikhilm @wanderview @slightlyoff @jakearchibald

**Comment by jungkees** [comment]
> (B) needs task queue(s) associated with the registration. And the service worker's event loop should process the registration's task queue instead of its own task queue in a way

I noticed a problem with the above. The service worker's event loop should also have to process its own task queue for `message` events. So, if we go with (B) external queue model, requeuing from/to between service worker's task queue and registration's task queue seems not avoidable.

**Comment by jungkees** [comment]
F2F:
* Define service worker registration queues (depending on each event)
* Service worker queues (depending on each event)

**Comment by bsittler** [comment]
F2F: queue may be too much ordering. Maybe a bag would be more appropriate?

**Comment by annevk** [comment]
Yeah, need to decide if it's the network layer that decides on ordering or if that happens between the document and the service worker.

**Comment by jungkees** [comment]
Updated this part: 7a8bc4223462f2e6000b2b2573a009f67c686be4.

- Added two task sources: the _handle fetch task source_ and the _handle functional event task source_.
- A registration owns its own _task queues_ that back up the tasks (having the above task sources) from the active worker's task queues.
- Defined Terminate Service Worker algorithm where back up the tasks to the registration's task queues as describe above.
- Run Service Worker algorithm re-queues the tasks from the registration's task queues to the service worker's event loop's task queues if the service worker is an active worker.

* As discussed in the f2f, tasks for message events are not re-queued as they are sent to specific service workers instead of an active worker.

@annevk @jakearchibald @slightlyoff Could you review it?

**Comment by jungkees** [comment]
Closing.
