### ISSUE TITLE
Association between a service worker and global objects

### ISSUE THREAD

**Issue by catalinb** [slightlyoff/ServiceWorker#652]
In section 4.2.4 step 9.4, the source of the MessageEvent is set to a ServiceWorker object that represents the service worker associated with the global object specified by the incumbent settings object.
How is a service worker associated to the global object?

cc @annevk

**Comment by annevk** [comment]
Also, it seems `.source` should be set to the `ServiceWorker` object that corresponds to the service worker where the message originated, which isn't really what this seems to define.

**Comment by jungkees** [comment]
> How is a service worker associated to the global object?

`ServiceWorkerGlobalScope` has an associated _service worker_: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#dfn-service-worker-global-scope-service-worker

Just missed the xref url to it. Fixed: cdb025b9f035fe6a660c5bc19896d77776b7fc57

> .source should be set to the ServiceWorker object that corresponds to the service worker where the message originated

It's set to the right one that corresponds to the service worker associated with the `ServiceWorkerGlobalScope` object, as just explained above, who's posting this message.

**Comment by jungkees** [comment]
Closing.

**Comment by KenjiBaheux** [comment]
Relevant blink bug: crbug.com/403693
