### ISSUE TITLE
Remove ignoreMethod

### ISSUE THREAD

**Issue by ehsan** [slightlyoff/ServiceWorker#653]
According to step 2.3.2.6.4 of the "Batch Cache Operations" algorithm, there is no way to store anything with a non-GET method in the cache database, as far as I can tell.  Therefore we should probably remove ignoreMethod for now.

**Comment by annevk** [comment]
Isn't that for when you want to reply to a POST request with a cached entry?

**Comment by wanderview** [comment]
That's a good point.  Step 4 from here:

  https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#query-cache-algorithm

I led Ehsan astray here.  Sorry for getting mixed up about this.
