### ISSUE TITLE
Navigate and redirects

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#654]
HTML's navigate algorithm invokes fetch and asks it to not follow redirects. Service workers however do not have this primitive so will follow redirects. This results in e.g. a request for `/foo` ending up with a response from some other origin potentially. I guess that's all okay?

**Comment by slightlyoff** [comment]
I think it's OK, but we need to understand how a developer might want to handle it. I've seen reports of OAuth redirect flows running afoul of this.

**Comment by annevk** [comment]
Actually, in some other ticket we ended up restricting this. A request for `/foo` needs a same-origin or synthetic response. See #590.

Of course, redirects still happen even though HTML sets redirect mode to "manual". This can be problematic if the URL redirected to is to be handled by the navigate algorithm in some manner rather than Fetch (e.g. a `skype` URL or some such).

**Comment by jakearchibald** [comment]
We fixed this with redirect "manual".
