### ISSUE TITLE
HEAD request on Cache API should not return response with body

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#655]
It should return a response without the underlying body to match HTTP semantics.

**Comment by wanderview** [comment]
Should it?  I mean, can't content decide not to read the body?  Should we prevent them from using a HEAD to get the full Response?

I guess ignoreMethod could bypass this logic as well.

**Comment by annevk** [comment]
An alternative would be for HEAD to behave the same way as other unknown methods. I don't think we should violate HTTP semantics when it can be easily avoided.

**Comment by jakearchibald** [comment]
@annevk does fetch filter out response bodies from `HEAD` responses?

**Comment by annevk** [comment]
That's a good question. Someone would have to test that with XMLHttpRequest and a server that allows that kind of thing.

**Comment by annevk** [comment]
I could not get a body for `HEAD` with XMLHttpRequest.

**Comment by jakearchibald** [comment]
Hah, I've just done the same. Here's the test for other's interested https://gist.github.com/jakearchibald/fffd22495c81e53e1b5e.

No modern browser populates `.responseText`, but I haven't tested IE yet (downloading VM)

**Comment by annevk** [comment]
Have you inspected the wire? I was wondering whether it might be the server that is doing some trickery or whether it's indeed something we'd need to define in Fetch.

**Comment by jakearchibald** [comment]
I've inspected the wire, the browser is the one doing the filtering. If you run the test above, then:

```
telnet localhost 8000
HEAD /test HTTP/1.1

```

…you'll get the body. That's why I had to use the socket directly, Node's usual HTTP stuff "protects" you from violating HTTP in that way.

**Comment by jakearchibald** [comment]
Firefox & Chrome's `fetch()` impl does the same. `fetch('/test', {method: 'HEAD'}).then(r => r.text()).then(t => console.log(t))` logs an empty string.

**Comment by jakearchibald** [comment]
Similarly with Chrome's streams implementation. `fetch('/test', {method: 'HEAD'}).then(function(r) { return r.body.getReader().read(); })` resolves to `{done: true, value: undefined}`

**Comment by annevk** [comment]
We should maybe talk to the network guys. Seems rather unusual for the networking code to protect the API in this way.

**Comment by jakearchibald** [comment]
Just tested IE11, `xhr.responseText` and `xhr.response` is `undefined`, making it slightly different from the other browsers that return an empty string.

**Comment by wanderview** [comment]
> We should maybe talk to the network guys. Seems rather unusual for the networking code to protect the API in this way.

It seems to me this is the browser following the principle of "be generous in what you accept and strict in what you expose".

Looking at the gecko code it appears that there are many cases where the content is explicitly ignored regardless of what the server does:

* HEAD method
* CONNECT method
* Responses with status codes 101, 204, 205, 304

See mNoContent in the code here:

https://dxr.mozilla.org/mozilla-central/source/netwerk/protocol/http/nsHttpTransaction.cpp#1523

**Comment by jakearchibald** [comment]
Node's `http.request` appears to be a little more strict. It throws if the line ends are `\n` rather than `\r\n`, it also throws if it receives a body in response to a HEAD request.

I think following the browser's leniency is fine here, but it should be in the fetch spec.

**Comment by annevk** [comment]
https://github.com/whatwg/fetch/issues/31 will solve this for Fetch. This issue can then be used to solve it for Cache.

**Comment by jakearchibald** [comment]
Agreed, the body should be removed before returning from the cache if the request is a HEAD.

**Comment by jungkees** [comment]
So, it seems `cache.match/matchAll` would need to filter out the body when request.method is "HEAD" and `ignoreMethod` is not true.

That considered, I imagine we won't care about a custom response returning body. It'll be filtered out in Fetch afterward, right?
`e.respondWith(new Response("body."));` // e.request.method == "HEAD"

**Comment by annevk** [comment]
@jungkees it seems reasonable for Fetch to handle the `respondWith()` case. I wonder if we need to update the `Response` constructor as well to disallow body when the status code is one of those listed by @wanderview.

**Comment by annevk** [comment]
Thinking about it a second more, I'm inclined to leave the `Response` constructor as-is, and only add filtering to Fetch. That seems to most closely match the existing infrastructure.

**Comment by jungkees** [comment]
> it seems reasonable for Fetch to handle the respondWith() case.

Great.

**Comment by jungkees** [comment]
> Agreed, the body should be removed before returning from the cache if the request is a HEAD.

Addressed: ebab43b31ddd1984850252c272c1ac3a4fc3094b.

**Comment by wanderview** [comment]
Gecko implementation bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1150001

**Comment by jungkees** [comment]
Closing.

**Comment by hallvors** [comment]
(Aside: IE11's behaviour sounds like a bug that will hurt them..)

**Comment by KenjiBaheux** [comment]
Filed crbug.com/476815
