### ISSUE TITLE
should Cache support VARY:*,otherheader or only VARY:*

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#656]
Right now it seems we support VARY:*,otherheader in step 9.5.1 here:

  https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#query-cache-algorithm

Here we continue looking at further VARY header values to see if there is a conflict.

In [RFC7231][], though, it states:

  The value consists of either a single asterisk ("*") or a list of header field names

Further, gecko's network stack allowed VARY:*,otherheader, but immediately considers the Response a match if it sees a * value.  (As opposed to continuing to look at other header values in SW spec.)

What does blink do?

Should we strictly match [RFC7231][]?  Or if we want web compat, should we match what browsers (gecko at least) are doing today by treating * as an auto-match even if there are other VARY headers?

@jakearchibald 

[RFC7231]: https://tools.ietf.org/html/rfc7231#section-7.1.4

**Comment by jakearchibald** [comment]
+@reschke +@mnot +@willchan your expert help is needed!

When matching a request to a response in the ServiceWorker cache, we're currently ignoring `*` because, well, it's scary. Should we:

* Pretend it isn't there
* Make `vary: *` requests match *nothing ever*
* Something else?

Additionally, what should we do with `vary: *, otherheader`?

**Comment by wanderview** [comment]
> Further, gecko's network stack allowed VARY:*,otherheader, but immediately considers the Response a match if it sees a * value. (As opposed to continuing to look at other header values in SW spec.)

FYI, I think I may have gotten the gecko logic wrong in my statement above.  It immediately considers the request as VARYing if it sees a *.  I now think that means "not a match".

**Comment by jakearchibald** [comment]
Yeah, that seems more sensible

**Comment by mnot** [comment]
Vary: * means "varies on things that I can't describe" -- i.e., it's not cacheable. 

See: http://httpwg.github.io/specs/rfc7234.html#caching.negotiated.responses

Note that we're working on a more fine-grained header, "Key" to increase general sanity. WIP, YMMV.

**Comment by wanderview** [comment]
> Vary: * means "varies on things that I can't describe" -- i.e., it's not cacheable. 

Given this definition I would be in favor of making cache.put() reject on responses with `VARY:*`.

**Comment by mnot** [comment]
Hm. I can imagine this surprising devs in some cases, e.g., if they were writing a generic cache component, and it works 99% of the time, but then fails when Vary: * is there.

What do you mean by 'reject' -- i.e., is that an exception, silent failure...?

**Comment by wanderview** [comment]
> What do you mean by 'reject' -- i.e., is that an exception, silent failure...?

Reject the promise.  This is something they can catch and handle.

If we make VARY:* act like normal http caching, then we can never pull it back out with .match() or .matchAll() without using the ignoreVary flag.

Or we keep the current behavior where we do VARY matching, but just ignore VARY:*.  This seems confusing to me (on top of an already confusing algorithm) because it behaves differently from other places VARY is used.

Rejecting the promise if a VARY:* response is put in the Cache keeps the "not cacheable" behavior and leaves open the possibility of relaxing this restriction in the future.

**Comment by jakearchibald** [comment]
I'm leaning heavily towards @wanderview's suggestion here: Reject on cache `add`/`addAll`/`put` if the response has `Vary: *` - the whole design of the cache API is to avoid entries that cannot be matched with `.match`.

**Comment by mnot** [comment]
SGTM.

**Comment by jungkees** [comment]
> Reject on cache add/addAll/put if the response has Vary: *

Is "Vary: *" commonly used in practice? Having them in cache `add/addAll/put` in `oninstall` will lead to installation failure.

**Comment by mnot** [comment]
Not terribly, but it's out there.

**Comment by jungkees** [comment]
Addressed: 8c3dbf19c2e0bf1aaf0f9e3b15b615913876f91d.

**Comment by wanderview** [comment]
@jungkees, I think you need to parse the VARY header in case the * is embedded in a single value like `VARY:*,foo`.  This was done in the existing spec language like this:

> Let varyHeaders be the array containing the elements corresponding to the field-values of the Vary header.

So I think we need to say if any of the field-values in any of the VARY headers is *, then reject.

**Comment by wanderview** [comment]
Gecko implementation bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1149987

**Comment by jungkees** [comment]
> need to parse the VARY header in case the * is embedded

Yeah right. Fixed: 383581e110cf1031b26542ff71bc3a72d15e71e0. Thanks.

**Comment by jungkees** [comment]
Closing.

**Comment by KenjiBaheux** [comment]
Filed http://crbug.com/476814
