### ISSUE TITLE
ServiceWorker constructor instead of navigator.serviceWorker

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#660]
Why doesn't Service Worker use Constructor instead of the current approach? Is this a matter of taste?

```
var sw = new ServiceWorker('/path/to/sw.js',{scope : '/'});
sw.onregister = function(evt){
      console.log('Service Worker is successfully registered');
};
sw.onerror = function(er){
     console.log(er.message);
};

**Comment by jakearchibald** [comment]
Yeah, taste and consistency. Also, a constructor shouldn't change state outside its own object. In the case of creating a new ServiceWorker registration, that's added to an underlying registry, so the effects persist even if the registration object on the page is garbage collected.

**Comment by annevk** [comment]
@jakearchibald that reasoning seems flawed as we have many constructors that have side effects. E.g. `new Worker()` does exactly that. And `new SharedWorker()` affects a registry.
