### ISSUE TITLE
Do we need InstallEvent's activeWorker?

### ISSUE THREAD

**Issue by KenjiBaheux** [slightlyoff/ServiceWorker#661]
I was going over Blink's IDLs and IDLs in the spec and just found out that InstallEvent had an activeWorker member for a while. Do we still need it? Can't we just use "registration.active" ?

Tentatively tracked via https://code.google.com/p/chromium/issues/detail?id=470032 for Blink

cc/ @jungkees @jakearchibald @slightlyoff

**Comment by jungkees** [comment]
I agree `registration.active` does the same role so we might want to drop `e.activeWorker`. In this case, we have a choice either use `ExtendableEvent` for `install` event as it doesn't have any attribute itself or still use `InstallEvent` for future extension.

Another thing is, the only use case for this attribute I remember is the messaging between an installing worker and an active worker. But `registration.active.postMessage()` from a service worker doesn't fit to our SW messaging model sorted out to date. `e.source` set to a `Client` object seems not working here. I think we need to sort out the communication method between service workers somehow.

**Comment by jakearchibald** [comment]
Agreed, we no longer need `installEvent.active`, good catch.

> But `registration.active.postMessage()` from a service worker doesn't fit to our SW messaging model sorted out to date

Hm, good point. Ideally `.source` should be a `ServiceWorker`.

**Comment by jungkees** [comment]
Removed `InstallEvent` interface and made it use `Extendable` interface for `install` events: 4d172287dc5f92530ac251f68a670f5f4de9540c.

> Hm, good point. Ideally .source should be a ServiceWorker.

Addressed: 5c715d1ccab03fa65b0b5a5c1de8fd4e63d5c8f2.

**Comment by jakearchibald** [comment]
Should this be closed?

**Comment by jungkees** [comment]
Yes. Closing.
