### ISSUE TITLE
Equivalent of Shared Worker Port in Service Worker?

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#662]
Shared Worker uses Message Port to send messages between parent worker and Shared Worker.

**Parent worker**
```
var port = new SharedWorker('/worker.js').port;
port.onmessage = function(e){
    console.log(e.data);
};
port.start();
port.postMessage("Hello Shared Worker. I'm Mr. Tab");
```
**Shared Worker (worker.js)**
```
onconnect = function(e){
    var port = e.ports[0];
    port.onmessage = function(e){
        console.log(e.data);
    };
    port.start();
    port.postMessage("Hello Mr. Tab. I'm Shared Worker.");
};
```
Is there anything similar to Shared Worker Port in Service Worker?

**Comment by jakearchibald** [comment]
Yep!

Messaging from page to ServiceWorker:

```js
// in the page:
navigator.serviceWorker.controller.postMessage("Hi!");

// in the ServiceWorker:
self.onmessage = function(event) {
  event.source; // instance of Client
  event.data; // "Hi!"
  // reply
  event.source.postMessage("Hey!");
};

// back in the page:

navigator.serviceWorker.onmessage = function(event) {
  event.source; // instance of ServiceWorker
  event.data; // "Hey!"
};
```

I think Chrome currently sends postmessages from ServiceWorker to Window to window.onmessage, based on an earlier spec.

**Comment by tresdin** [comment]
@jakearchibald My `navigator.serviceWorker.controller` is always `null`. Do you have any ideas about this strange behaviour?

**Comment by jakearchibald** [comment]
That means the page is not controlled by a ServiceWorker (so you won't get fetch events either). Look at chrome://serviceworker-internals and check for a successful registration & what its scope is

**Comment by tresdin** [comment]
@jakearchibald I've just found my issue. My scriptURL is `/app/sw.js`, and the page url is `/`. How can I make it work without moving the script to root? Thank you.

**Comment by mattto** [comment]
@tresdin You'd have to move the script to root or else use the Service-Worker-Allowed HTTP header. See #468 . BTW if you're using a recent version of Chrome, it has a message explaining this when you try to register for scope '/':

"DOMException: Failed to register a ServiceWorker: The path of the provided scope ('/') is not under the max scope allowed ('/app/'). Adjust the scope, move the Service Worker script, or use the Service-Worker-Allowed HTTP header to allow the scope."

**Comment by tresdin** [comment]
Thank you @mattto . I've added the header `Service-Worker-Allowed : /` but nothing changed.  I'm using Chrome 41.

BTW, I wonder how the `Service-Worker-Allowed` header can fix it since there is no http request sent to server once the error occured.

**Comment by mattto** [comment]
Sorry, that's because Service-Worker-Allowed is available in Chrome 42+. I'd recommend testing on Chrome Dev or Canary channel. Anyway this this getting pretty implementation-specific as opposed to a spec discussion, so if you have further questions about Chrome specifically, you can use https://groups.google.com/a/chromium.org/forum/#!forum/service-worker-discuss or file bugs at crbug.com.

**Comment by tresdin** [comment]
@mattto I've already asked few questions on stackoverflow. However, I finally found it's easier to receive useful replies on Github. :)

**Comment by jakearchibald** [comment]
@tresdin can you link me to your stackoverflow questions? I'll answer them there, and make sure they're picked up in my searches in future.

**Comment by tresdin** [comment]
@jakearchibald I just have these two questions.
- The one you've already answered here
http://stackoverflow.com/questions/29230470/equivalent-of-shared-worker-port-in-service-worker
- And the other if you're interested in.
http://stackoverflow.com/questions/28882289/service-worker-vs-shared-worker

**Comment by tresdin** [comment]
@jakearchibald I've just applied your solution on Chrome 43. And `event.source` is null on ServiceWorkerGlobalScope.

**Comment by jakearchibald** [comment]
@tresdin I guess that hasn't been implemented yet - that part of the design wasn't done until fairly recently. You can hack around it by passing in a channel https://jakearchibald.github.io/isserviceworkerready/demos/postMessage/

**Comment by tresdin** [comment]
@jakearchibald Actually, none of your solutions is an equivalent of Shared Worker Port. See my answer for more information. 
http://stackoverflow.com/questions/29230470/equivalent-of-shared-worker-port-in-service-worker/29320291#29320291

**Comment by tresdin** [comment]
@jakearchibald Actually, none of your solutions is an equivalent of Shared Worker Port. See my answer for more information. 
http://stackoverflow.com/questions/29230470/equivalent-of-shared-worker-port-in-service-worker/29320291#29320291

**Comment by wifiextender** [comment]
Thanks @jakearchibald (u have great blog btw), @tabatkins
