### ISSUE TITLE
Cache should sanitize the stored Request in put/add/addAll

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#664]
There are some values on the Request object that should not be persisted.  Fetch handles this by sanitizing the input Request.  See step 4 from here:

  https://fetch.spec.whatwg.org/#dom-request

@annevk suggests Cache should have a similar sanitize step.

The attributes I know about that should not be stored are:

* context (Cache should always produce a context of "fetch")
* synchronous flag

**Comment by ehsan** [comment]
I think we should store the context attribute if the Request is stored through Cache.put (which does not perform a "fetch").  As an author, I would find it quite surprising to Cache.put() something into the database and find its context value to have changed after reading it back.

Discussing this with @wanderview on IRC, he mentioned a good point about Cache not being able to filter based on the context value, so we can never store two Requests that only differ in their context side by side which I think is a good point, but I think it's better to extend Cache to add that functionality.  I can see use cases where you may want to store two different responses for requests differing only in context.  One example would be for example youtube video embeds, where you may want to store a different synthesized Response in the cache for Requests coming from iframes and requests loaded outside of an iframe.

**Comment by annevk** [comment]
`put()` storing as-is (and not sanitizing) might be okay. Making contexts part of the index seems much less okay though. They indicate where the request originated and affect CSP and such, not the network.

**Comment by ehsan** [comment]
I agree that the context doesn't affect anything that goes on over the network, but the point is that a service worker which synthesizes responses can choose to synthesize differently based on the context.

**Comment by jungkees** [comment]
FYI, currently requests in `USVString` type passed to `addAll/put` are sanitized and `Request` objects passed to them are not.

> synchronous flag

This is not exposed to the script surface.

**Comment by annevk** [comment]
> FYI, currently requests in `USVString` type passed to `addAll/put` are sanitized and `Request` objects passed to them are not.

That needs to be fixed. `addAll` performs fetching and cannot be more powerful than `fetch()` therefore.

**Comment by jungkees** [comment]
Addressed that comment: 0252170ab9c49bd7f24f06949e1fa0c497a5859c.

A question is what the request's context for a fetch performed in `addAll()` should be? I left it as an empty string for now.

**Comment by annevk** [comment]
> A question is what the request's context for a fetch performed in `addAll()` should be?

"cachefetch" or maybe just simply "fetch" since it is identical in terms of power. Definitely not the empty string, that is reserved for things that do not actually fetch.

**Comment by jungkees** [comment]
Let's use "fetch" until we find any specific need for "cachefetch": 0d6b44a997fe75846758fc4e078f579f5341e4ea.

**Comment by wanderview** [comment]
@jungkees Why do we use `clone()` for some cases, but the Request constructor for others?  I don't think those are equivalent, are they?

For example, I would expect clone() to preserve the context, but the Request constructor to default it back to empty string.

**Comment by wanderview** [comment]
@jungkees , I was talking @annevk on IRC and he pointed out we only want the sanitize step in .add() and .addAll().  So just removing the sanitize in the other methods I think removes the clone() calls I was concerned about.

Also, can we put the sanitize step in .add()/.addAll() after we check the request method?  That way if someone accidentally passes a PUT Request we won't drain the body stream when we error.

Thanks!

**Comment by jungkees** [comment]
@wanderview thanks for the clarification. I'd used the clone to avoid draining body in keys()/matchAll()/delete(). I think your suggestion will do!

**Comment by jungkees** [comment]
Addressed @wanderview's comment: 66586c1c078ea5393196b740a8573f2615696b13.

**Comment by wanderview** [comment]
Thank @jungkees!

It looks like maybe addAll() step 4.2 should be removed?  Its validating the request url scheme against 'http' and 'https' again, even though we do that now in step 3.2.

**Comment by jungkees** [comment]
The step 3.2 does so only for the arguments typed the `Request`. The step 4.2 is needed for the arguments typed a string.

**Comment by wanderview** [comment]
Since we check for method GET in 3.2, I think we're guaranteeing that we won't run the Request constructor and drain the body from a PUT.  So I think we can get away with just running the scheme check at 4.2.

Sorry for my confusion above.  Thanks!

**Comment by jungkees** [comment]
The scheme check at 4.2 should remain for string typed request argument. Closing.
