### ISSUE TITLE
what should Cache put operations do if the body errors out after resolving promise?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#665]
The spec text now says in Batch Cache Operations:

> The cache commit is allowed as long as the response's headers are available.

So the body would stream to disk in the background after promise resolved.

What should Cache do if there is a network error while writing the body?  Just truncate the body?  Remove the entry?

**Comment by wanderview** [comment]
I'd like to clarify this before we attempt to implement partial response commit in gecko.

**Comment by annevk** [comment]
We only know this if we check `Content-Length`, no? Which is known to not be reliable, though maybe HTTP/2 changes this a bit?

**Comment by wanderview** [comment]
We know in the implementation in some cases because we get an error code from the network library.  Or it could be because another internal error, like worker thread shutdown, truncated the stream.

But if the connection is terminated with a RST, then no, we cannot distinguish these errors.

**Comment by annevk** [comment]
So the current design seems somewhat problematic for developers. You think you successfully added an entry, but then it errors later on and there's no way to find out. Should a cache keep an error log of sorts?

**Comment by wanderview** [comment]
One idea is to resolve put/add/addAll with another object that exposes a promise representing the completion of the body.  That would at least give code a chance of detecting this.

**Comment by jungkees** [comment]
> So the body would stream to disk in the background after promise resolved.

The body would stream to disk in the background even after promise is **returned**. But the promise returned from `addAll()/put()` will resolve/reject only when the end-of-file is pushed to response's body or the response get a termination reason.

If the response gets a termination reason, the cache rolls back. That happens in [addAll()](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#cache-addAll) step 6.4.2.2.2 and [put()](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#cache-put) step 14.2.

**Comment by wanderview** [comment]
@jungkees thats how it used to work, but I thought we changed it.  I thought this note in BatchCacheOperations meant the UA could resolve the add/addAll/put promise before the body was complete:

> The cache commit is allowed as long as the response's headers are available.

Or are you saying we commit to Cache, so other cache.Match() calls will find the partial response, but we still don't resolve the add/addAll/put promise when we commit to the Cache?  That sounds confusing from an API perspective to me...

**Comment by jungkees** [comment]
> Or are you saying we commit to Cache, so other cache.Match() calls will find the partial response, but we still don't resolve the add/addAll/put promise when we commit to the Cache?

Yes, that was the decision. Here's the summary of the behavior from the discussion: https://github.com/slightlyoff/ServiceWorker/issues/573.

**Comment by jungkees** [comment]
Closing. History: https://github.com/slightlyoff/ServiceWorker/issues/362#issuecomment-119092324.
