### ISSUE TITLE
Not Found Error instead of undefined response

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#666]
I feel it's a little bit weird when `Not Found` caches return `undefined` response instead of a `Not Found` error since most of IO operations solve this situation with an error.
```
caches.match('/app.js').then(function(response){
     console.log("Resource found");
}).catch(function(er){
     if(er.code === 'NOT_FOUND'){
          console.log("Resource Not Found");
     }
});

**Comment by jakearchibald** [comment]
Yeaaahh, I figured this might cause confusion. See the argument about it over at https://github.com/slightlyoff/ServiceWorker/issues/374#issuecomment-53710621.

The argument boils down to consistency with other "getting" APIs. Eg `localStorage.get("doesNotExist")` does not throw an error, it returns undefined.

**Comment by inexorabletash** [comment]
Adding the explicit keyword `NotFoundError` to this issue for search-bait
