### ISSUE TITLE
Service Worker doesn't catch favicon requests

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#668]
Why doesn't Service Worker catch my favicon request?

```
<link rel="icon" type="image/png" href="/app/favicon-192x192.png" sizes="192x192">
```
**sw.js**
```
onfetch = function(e){
     //nothing happened
     console.log(e.request.url);
};

**Comment by mattto** [comment]
It should. I assume you're testing on Chrome? This is a Chrome implementation bug:
https://code.google.com/p/chromium/issues/detail?id=448427

**Comment by tresdin** [comment]
You've got the right point. From your link, it's hard to believe that Chrome deals with an issue by representing a new bug ~~. Thank you @mattto

**Comment by wanderview** [comment]
Closing since this appears not to be a spec issue.
