### ISSUE TITLE
Disable http URLs when there are no clients

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#671]
Per https://github.com/slightlyoff/BackgroundSync there is this idea that when a service worker is running in the background and there is no UI we should not allow insecure fetches.

Should we annotate the environment settings object in some way? Fetch can then check this new variable and return a network error in case of an http URL.

(Presumably we will disallow insecure `WebSocket` at all times?)

**Comment by KenjiBaheux** [comment]
I would prefer that the Fetch spec doesn't mandate the behavior here: surfacing this to the user even where there is no clients doesn't seem impossible.

cc/ @jakearchibald @slightlyoff

**Comment by annevk** [comment]
Showing mixed content warnings for an application running in the background? I'm intrigued.

**Comment by KenjiBaheux** [comment]
Does the presence of clients guarantee that there is something in the foreground the user is actively looking or at least able to notice?

**Comment by annevk** [comment]
They don't have to be looking at a browsing context for it to fetch mixed content but there is a reasonable chance they will notice the mixed content icon. However, we're also supposed to actively reduce mixed content. I see no reason why we'd allow it in the background. Background is strictly new functionality, we should have a higher bar there.

**Comment by jakearchibald** [comment]
How about `fetch('http://example.com', {mode: 'no-cors'})` always fails in a ServiceWorker, but `fetch(fetchEvent.request)` may work if `fetchEvent.request` originated from a window client?

**Comment by annevk** [comment]
I like that. Though I'm not sure how that would work for Cache.

**Comment by jakearchibald** [comment]
The cache would store the result (which would be opaque), whether using that response should show a broken padlock, I dunno.

**Comment by annevk** [comment]
Well that it should. I was mostly wondering about what should happen if we add a way for a Cache to refresh its resources.

**Comment by jakearchibald** [comment]
Updating as a ton of problems, I'm not sure we'll ever get it on normal caches.

**Comment by annevk** [comment]
Ah okay, sounds good then. Before `fetch()` invokes `new Request()` on the input we can figure out if the original client was a window which should be enough to enforce this.

**Comment by jakearchibald** [comment]
This has been defined by MIX
