### ISSUE TITLE
Unable to easily distinguish top-level navigations

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/ServiceWorker#673]
In previous iterations of the spec, a property of the `FetchEvent` type allowed the developer to easily understand if they were responding to a potential navigation; e.g. `if(e.isTopLevel) { ...  }`.

This is now gone, nominally replaced by the [`context` attribute of a Request](https://fetch.spec.whatwg.org/#requests).

This, however, doesn't actually provide the same information.

@jakearchibald has made the (cogent) case that a different `Content-Disposition` for a `Response` might not result in a navigation.

I'd like to untangle this and expose what we know about the request. I suggest that [`FetchEvent`](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#fetch-event-section) be extended with a property that describes if the event corresponds to a potential navigation; straman would be `e.isNavigation`.

*Bonus points*: the `Content-Disposition` handling is magical! It creates the ability for a response to not navigate a frame. This should be an API! In fact, it should be possible to `e.respondWith(/*something*/)` that _explicitly_ has this behavior in order to allow a SW to intercept navigations and drop them on the floor & `postMessage` to the client to effect an in-page transition.

**Comment by jakearchibald** [comment]
I think `isTopLevel` was something else, which we replaced with the client's frame type. I think you're thinking of `isNavigation`.

**Comment by slightlyoff** [comment]
I've slept since then = \

Regardless...how about a return of `isNavigation` (assuming we previously had it and then removed it)?

**Comment by jakearchibald** [comment]
I'm up for it, aside from bikeshedding the name. But this is a fetch thing.
+@annevk

**Comment by slightlyoff** [comment]
It's a property of `FetchEvent`, not anything in the fetch spec (to my mind). Although, obviously, want @annevk's input.

**Comment by jakearchibald** [comment]
Isn't it entirely dependent on the response's .context?

**Comment by jakearchibald** [comment]
Request, even

**Comment by slightlyoff** [comment]
There might be contexts for which `isNavigation` can't be true, but this is additional information that's specific to this event (it doesn't really belong on `Request` because passing it along to `fetch()` is meaningless).

**Comment by annevk** [comment]
`FetchEvent#client.frameType`?

**Comment by jakearchibald** [comment]
I don't think so, frames can also navigate

**Comment by annevk** [comment]
What about requests for workers? Should we expose "client request" instead (see Fetch)?

**Comment by jungkees** [comment]
Then I guess we also need to expose [ClientType](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#client-type-enum) on `Client` so devs can filter it out: `e.isClientRequest && e.client.clientType == 'window'`.

**Comment by jungkees** [comment]
Well.. We currently have `.frameType` on `Client` so it may work as well: `e.isClientRequest  && e.client.frameType != 'none'`.

**Comment by annevk** [comment]
I'm not sure. Client request is just a function of request's context. It would be weird for them not to be grouped together I think.

**Comment by annevk** [comment]
So how is `isNavigation` not https://fetch.spec.whatwg.org/#concept-request-context is what needs to be answered here. And if we want to have a shorthand for "client request" (e.g. `req.isForClient` or some such) that should be an issue against https://github.com/whatwg/fetch.

**Comment by jakearchibald** [comment]
Yeah, that's what I was thinking, it would be a shortcut like `response.ok`.

@slightlyoff is that what you're thinking? As in:

```js
Object.defineProperty(Request.prototype, 'canCreateClient', {
  get() {
    var clientCreatingContexts = [
      'embed', 'form', 'frame',
      'hyperlink', 'iframe', 'internal',
      'location', 'metarefresh', 'object',
      'serviceworker', 'sharedworker',
      'worker'
    ];
    return clientCreatingContexts.indexOf(this.context) != -1;
  }
});
```

**Comment by annevk** [comment]
By the way, re OP, "this should be an API", I don't disagree, but a Navigation API would be quite different from the Fetch API we have today. Fetching is a small part of navigation. If we really want to elaborate we probably need to dig deeper than a new `respondWidth()` parameter.

**Comment by jakearchibald** [comment]
*nudge* @slightlyoff - is the functionality described in https://github.com/slightlyoff/ServiceWorker/issues/673#issuecomment-92305399 what you're looking for?

**Comment by slightlyoff** [comment]
Yes, that'd do nicely. LGTM++

**Comment by jungkees** [comment]
F2F: go to Fetch spec. Will file it.

**Comment by annevk** [comment]
Also, this should be a property that returns one of "navigation", "worker", or "resource".

**Comment by annevk** [comment]
This is now https://github.com/whatwg/fetch/issues/93. Please help out bikeshed the name there.
