### ISSUE TITLE
Accessing service worker state from worker

### ISSUE THREAD

**Issue by catalinb** [slightlyoff/ServiceWorker#674]
Step 1 from the clients.claim() specification requires checking the associated service worker's state from the worker thread. This would require some sort of synchronization mechanism with the other parts of the spec that access/change a service worker's state.

I think the spec should give some clear direction on what the intended behaviour is. More specifically, should a claim() call from oninstall always fail?
If so, what should be the result of the claim promise in the following case:
oninstall = function() {
  var p = new Promise(function(res, rej) {
      onmessage = res;
  });
  p.then(self.claim);
}

**Comment by jungkees** [comment]
The [_service worker_](http://localhost/spec/service_worker/#dfn-service-worker-global-scope-service-worker) referenced in the step 1 of `clients.claim` is associated with the `ServiceWorkerGlobalScope` object in which the method is running. Although the state of the _service worker_ is being accessed/changed by other steps in the main thread and algorithm threads, the _service worker_'s state the method is checking is that of the one associated with the global object.

So, in your example, the `self.claim`'s success/failure depends on the current state of the _service worker_. For instance, if it was a fresh Register attempt, it'll fail as the state of the worker must be `installing`. On the other hand, it'll succeed if it was an Update attempt on an active worker.

**Comment by jungkees** [comment]
I was myself confused with the example. Basically `install` event is always dispatched at _installing worker_, so if `clients.claim()` is called on that state it'll fail. But if the service worker got to the activating/activated state (by e.g. skipWaiting()) when the method is called, it'll succeed. So, in your example, it depends on the state as such. If the service worker has been an active worker by the time the `message` event is dispatched, it'll succeed.

**Comment by jungkees** [comment]
Please feel free to reopen it if things are unclear. Thanks.

Closing.
