### ISSUE TITLE
waitUntil promise for Install/Activate

### ISSUE THREAD

**Issue by jungkees** [slightlyoff/ServiceWorker#675]
The current Install/Activate waits for the settlement of the `waitUntil` promise within the event handler. And it makes the installation/activation fail when the `waitUntil` promise rejects. 

I'm concerned whether this behavior is correct. It seems the `waitUntil`'s sole purpose should be to give the UA a signal to extend the lifetime (i.e. not to determine the success/failure of certain operations.)

Should the following code be considered an installation failure?
```js
oninstall = (e) => {
  e.waitUntil(caches.open("mysite-static").then(cache => { 
    return cache.addAll(['/css/basic.css', '/js/main.js']).then(() => {
      // some error in a post processing.
      throw new Error("err");
    }); 
  }));
};
```

**Comment by wanderview** [comment]
I thought this was an explicit goal from @jakearchibald to ensure that an installed SW is correct.

**Comment by jungkees** [comment]
Yes, right. I had forgotten that. The `install` event and the `activate` event added that semantic to the waitUntil(): https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#wait-until-method. Thanks for the reminder. Closing.
