### ISSUE TITLE
FetchEvent IDL issues

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#680]
`request` and `client` are initialized to null but are not nullable. It's not clear to me that `request` should be nullable, perhaps we should just require it to be always provided now that is possible?

Furthermore, the dictionary should offer default values (except if the member is required).

**Comment by jungkees** [comment]
Addressed: dba51f4b57472b03b80bbdc42c1e368cb44809d1. Thanks!

> It's not clear to me that request should be nullable, perhaps we should just require it to be always provided now that is possible?

Agreed. But `client` should still be nullable, right?

**Comment by annevk** [comment]
Hmm, is there a case where you have a fetch event but no client? I can't think of a scenario.

**Comment by jungkees** [comment]
But we don't provide a constructor for `Client` so devs are able to set it to nothing but null for custom objects. Also fetch allows `client` to be null, so conceptually aligned at least?

**Comment by annevk** [comment]
Well, fetch allows requests without a client, but those also don't go into a service worker as far as I can tell.

For custom events you could just grab an existing `Client` instance.

**Comment by jungkees** [comment]
Addressed: a143159791e6a835a06474d6ff3c128fb3d35409.

**Comment by wanderview** [comment]
> Hmm, is there a case where you have a fetch event but no client? I can't think of a scenario.

Page navigates away just before the FetchEvent is delivered?  Maybe that's handled elsewhere in the spec.

**Comment by annevk** [comment]
Yeah so that depends on the processing model.

**Comment by annevk** [comment]
Currently Fetch does not account for the environment settings object going away by the way. It's either there or not.

**Comment by ehsan** [comment]
I'm changing Gecko's `FetchEvent.request` to be nullable since I think that is the only reasonable thing to do here given the fact that there is nothing to guarantee that request will be passed in when constructing a new fetch event.  Without this, `(new FetchEvent("foo")).request` is essentially specced to cause a crash (which it indeed does in Gecko right now.)  See https://bugzilla.mozilla.org/show_bug.cgi?id=1218499.  Please update the spec accordingly.  Thanks!

**Comment by annevk** [comment]
We should just require `request` to be provided for `FetchEvent`.

**Comment by jungkees** [comment]
I'll define the `FetchEvent`'s constructor and init the request to null. (Should be nullable.)

**Comment by annevk** [comment]
Why not require it?

**Comment by jungkees** [comment]
Sorry to have missed to provide that option during the meeting. Requiring it makes sense.
