### ISSUE TITLE
Navigating clients from the SW context?

### ISSUE THREAD

**Issue by slightlyoff** [slightlyoff/ServiceWorker#681]
In discussions with the Google team, a question has come up regarding the ability to navigate client objects. This would be the moral equivalent of `window.location = ...` and/or `window.location.reload()`.

Would love to find a way to enable this.

**Comment by jakearchibald** [comment]
Not against this, but would like to know why postmessage isn't a good solution here

**Comment by slightlyoff** [comment]
because it means you need a client-side contract and can't "just do the
same thing" with regards to a server-sent document/redirect. This solution
makes it easier to keep documents ignorant of SWs and reduces duplicate
code paths.

**Comment by jakearchibald** [comment]
Does *not* being able to do this with (shared)workers pose a problem?

**Comment by jakearchibald** [comment]
We could have `windowClient.navigate(url)`, which returns a promise. `url` could be optional and default to the current url (eg reload). Promise would reject if client no longer exists.

@slightlyoff can you give us a better idea of the use-case? When would they be calling this?

**Comment by slightlyoff** [comment]
The use-case was a situation where you might otherwise want to do a
redirect, but from the perspective of the SW. In the case of document
creation, there's a step between starting the process of creation (which
generates a new name) and navigating to the actual named location;
`/create` -> `/generatedname`

**Comment by jakearchibald** [comment]
Another use-case for this: Say a site ships a broken ServiceWorker. It fixes it. The new version should be able to `skipWaiting`, `clients.claim()` and reload all the clients.

I'll spec `windowClient.navigate(url)`, where `url` defaults to the current url, so `windowClient.navigate()` reloads.

`url` is relative to the SW.

If `url` only differs in fragment, or does not differ at all, the page will still reload. Therefore calling `.navigate` will always cause a fetch of the url.

**Comment by jakearchibald** [comment]
I've taken a first stab at this, @jungkees, can you review?

I'm checking that the document hasn't been discarded (1.6.2), should `focus()` do the same?

I'm rejecting the promise if the client isn't controlled by this SW - else you can navigate parts of the origin "owned" by someone else.

I'm uncomfortable with the "source browsing context" bit, as it's a lie, but I think this is the first API that lets a non-browsing context navigate a browsing context.

I decided against:

> I'll spec windowClient.navigate(url), where url defaults to the current url, so windowClient.navigate() reloads.

…as that clashes with other APIs where the default url is "" (eg `getRegistration`).

**Comment by jungkees** [comment]
@jakearchibald Looks good. I just tweaked step 4 (links to concepts) and step 6.3.4 (variable). And added step 6.3.2 for https://github.com/slightlyoff/ServiceWorker/issues/694#issuecomment-103627523.

> I'm uncomfortable with the "source browsing context" bit, as it's a lie, but I think this is the first API that lets a non-browsing context navigate a browsing context.

This seems fine to me since the _browsingContext_ there is actually a browsing context gotten from a service worker client's global object.

> I'm checking that the document hasn't been discarded (1.6.2), should focus() do the same?

FWIW, `focus()` still should work even if the browsing context discards its document?

**Comment by jakearchibald** [comment]
> FWIW, focus() still should work even if the browsing context discards its document?

Does that mean this can happen:

1. SW js looks at clients, finds one with url `/chat/`, which is correct
2. User focuses that client & navigates it to another URL, perhaps even another origin
3. SW js calls `.focus` on the client, which works

Does that mean I just focused a tab that had been navigated away from `/chat/`, maybe even to another origin?

**Comment by nhiroki** [comment]
Tracked at http://crbug.com/500911 for Blink

**Comment by nhiroki** [comment]
From the step 4 on navigate():

> If the context object's associated service worker client's active worker is not the incumbent settings object's global object's service worker, return a promise rejected with a TypeError.

According to [jake's comment](https://github.com/slightlyoff/ServiceWorker/issues/681#issuecomment-103556480), a client to be navigated should be controlled by the incumbent service worker, so "service worker client's active worker" should be "service worker client's controller".

**Comment by jakearchibald** [comment]
@nhiroki I don't think "controller" is a defined thing, but active worker is [defined as](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#dfn-service-worker-client-active-worker):

> A service worker client has an associated active worker (an active worker) which currently controls it. It is initially set to null.

…which means the same.

**Comment by nhiroki** [comment]
@jakearchibald Thank you for the reply. That makes sense. I was thinking the case where a service worker is active but not a controller yet (eg. first load).

**Comment by jakearchibald** [comment]
We implemented this!
