### ISSUE TITLE
navigator.serviceWorker is not defined

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#689]
"The serviceWorker attribute must return the ServiceWorkerContainer object for the context object." seems fairly broken.

**Comment by jakearchibald** [comment]
The [geolocation spec](http://dev.w3.org/geo/api/spec-source-v2#api_description) goes with:

> Objects implementing the Navigator interface (e.g. the window.navigator object) must also implement the NavigatorGeolocation interface [NAVIGATOR]. An instance of NavigatorGeolocation would be then obtained by using binding-specific casting methods on an instance of Navigator.

Is that the correct way to do this (along with creating `NavigatorServiceWorker`)?

**Comment by annevk** [comment]
No, that's also broken. You need to define the object hierarchy. E.g. what objects hold references to other objects. And then simply return the correct object from the API that's on top.
