### ISSUE TITLE
should SW MessageEvents inherit ExtendableEvent?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#690]
The spec has been changed so that most events fired on ServiceWorker inherit from ExtendableEvent and therefore have a `.waitUntil()` method.  The one exception is MessageEvent.  Should we have some kind of ExtendedMessageEvent that inherits from ExtendableEvent and MessageEvent?  Right now one cannot do this:

```
addEventListener('message', function(event) {
  event.waitUntil(cache.add(event.data.request));
});
```

**Comment by jungkees** [comment]
Closing this issue in favor of https://github.com/slightlyoff/ServiceWorker/issues/669. Please feel free to reopen it if you've intended something else.
