### ISSUE TITLE
allow self-signed certificates 

### ISSUE THREAD

**Issue by matt-cook** [slightlyoff/ServiceWorker#691]
Follow up to #274 and #199 . 

Possible to add a whitelist or similar function (similar to the Chrome warning page presented during browsing) to allow self-signed certs? Would be useful for shared testing servers, or intranet (or other limited access). Often proper CA certs are not an option in these situations.

**Comment by annevk** [comment]
You can already configure these with your browser, no? This is not an issue for the specification.

**Comment by flaki** [comment]
Hi @matt-cook!
You could disable certificate checks [for development in Firefox already](https://github.com/slightlyoff/ServiceWorker/issues/658#issuecomment-87283965), and [the Chrome team is working](https://code.google.com/p/chromium/issues/detail?id=441605) on similar helper tooling.

**Comment by matt-cook** [comment]
Bummer. We currently have a Chromebox-based local (intranet) installation we'd love to use ServiceWorker-based caching on (http://www.livsreise.org/map-your-journey/). Sounds like we'll need to wait until browsers can handle those permissions, or get a proper CA cert. Thanks guys.

**Comment by annevk** [comment]
I recommend figuring out certificates. You'll need them for a host of new features soon and generally it's better for your users.

**Comment by redochka** [comment]
@flaki thanks for the chrome's link. Chrome team fixed it now you can use:

google-chrome --unsafely-treat-insecure-origin-as-secure --user-data-dir=tmp/chrome-dev-profile/

**Comment by 75lb** [comment]
@matt-cook it's trivial to create a self-signed cert for local use - no need for openssl, verification or *any* 3rd party.. follow [these steps](https://github.com/75lb/local-web-server#https-server).

**Comment by khiav223577** [comment]
> @flaki thanks for the chrome's link. Chrome team fixed it now you can use:
> 
> ./chrome --user-data-dir=/tmp/foo --unsafely-treat-insecure-origin-as-secure=http://your.insecure.site
> 

Now you can type `chrome://flags/#unsafely-treat-insecure-origin-as-secure` in the address bar of your chrome to open the settings' page.
