### ISSUE TITLE
add [NewObject] where appropriate

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#692]
There are a lot of methods in the spec that always return a new object.  For example, all the Cache and CacheStorage methods require returning a new Promise object.  It would be nice to flag these as [NewObject] to make the IDL more self-documenting.

For Cache:

```
[Exposed=(Window,Worker)]
interface CacheStorage {
  [NewObject] Promise<Response> match(RequestInfo request, optional CacheQueryOptions options);
  [NewObject] Promise<boolean> has(DOMString cacheName);
  [NewObject] Promise<Cache> open(DOMString cacheName);
  [NewObject] Promise<boolean> delete(DOMString cacheName);
  [NewObject] Promise<sequence<DOMString>> keys();
};
```

and

```
[Exposed=(Window,Worker)]
interface Cache {
  [NewObject] Promise<Response> match(RequestInfo request, optional CacheQueryOptions options);
  [NewObject] Promise<sequence<Response>> matchAll(optional RequestInfo request, optional CacheQueryOptions options);
  [NewObject] Promise<void> add(RequestInfo request);
  [NewObject] Promise<void> addAll(sequence<RequestInfo> requests);
  [NewObject] Promise<void> put(RequestInfo request, Response response);
  [NewObject] Promise<boolean> delete(RequestInfo request, optional CacheQueryOptions options);
  [NewObject] Promise<sequence<Request>> keys(optional RequestInfo request, optional CacheQueryOptions options);
};
```

**Comment by jungkees** [comment]
@wanderview Thanks for the suggestion. One thing to check before adding this is this rule specified in WebIDL: "The [NewObject] extended attribute must not be used on anything other than a regular or static operation **whose return type is an interface type**." (http://heycam.github.io/webidl/#NewObject)

I found @annevk used it for Promise type in fetch spec though. (https://fetch.spec.whatwg.org/#globalfetch)

/cc @annevk @heycam

**Comment by heycam** [comment]
I think we can safely allow [NewObject] on Promise-typed things.

**Comment by heycam** [comment]
https://github.com/heycam/webidl/commit/f0e58c36c912b142c7afc2aa4d135225442d0dd4

**Comment by jungkees** [comment]
Thanks for quick update @heycam.

Added [NewObject] and [SameObject] extended attribute: 655ededa26925c898721a741d81a1b483a1d8a07.

Here the discussion about the distinct objects and the same objects, which still has to be resolved. But I believe we basically reached a consensus on the behavior there.

**Comment by inexorabletash** [comment]
FWIW, I'd expect that most APIs that return a Promise would return a new object each time. To keep IDL fragments readable, maybe WebIDL's Promise<> definition should be [NewObject] by default, and specs can use [SameObject] for the rare case?

**Comment by domenic** [comment]
Promise getters should be the same object every time (or at least until something causes it to change). Promise methods can be either new every time or could return the same value, depending.

**Comment by annevk** [comment]
[NewObject] refers to the promise. There's no way to refer X (yet?).

**Comment by jungkees** [comment]
Yeah. An extended attribute for X would be useful. Something like:
`[NewObject] Promise<[SameObject] X>` ?

**Comment by jungkees** [comment]
Addressed: https://github.com/slightlyoff/ServiceWorker/issues/416. Closing.
