### ISSUE TITLE
Step 5.3 of openWindow does "exceptions enabled" which doesn't make sense

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/ServiceWorker#694]
This step is running async.  What's supposed to happen with this exception, exactly?

**Comment by jakearchibald** [comment]
@domenic see 5.3.1 of https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#clients-openwindow - the intention is for the promise to reject if Navigate throws, what's the spec language for this?

**Comment by jakearchibald** [comment]
`client.navigate(url)` has the same issue

**Comment by domenic** [comment]
I dunno, I guess given that this is all imprecise-style instead of ES-style, probably something like "If navigating throws an exception, reject promise with the exception and abort these steps"?

**Comment by jungkees** [comment]
Sounds good. I added that to `clients.openWindow()` and `client.navigate()`: 5b110193ad82fea52580ba2eb7d84207981c82c2.

**Comment by jakearchibald** [comment]
Thanks!
