### ISSUE TITLE
Step 5.4 of openWindow uses the incumbent settings object, which makes no sense

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/ServiceWorker#695]
This step is running async.  There might not even be an incumbent settings object at this point.

If the intent is to use the origin of the incumbent settings object at the point when openWindow was called, then you need to capture it before going async.

**Comment by jakearchibald** [comment]
This is now

> If the origin is not the same as the service worker's origin, then:

…which is used in other parts of the spec. This this async-safe? If the SW has terminated by this point, there's no promise to resolve.

Reopen if it's still a problem, and I'll change all similar references to capture origin to a var before going async.

**Comment by bzbarsky** [comment]
Seems fine, except it would make sense to link to the definition of "service worker's origin", not the generic definition of "origin".
