### ISSUE TITLE
Fallback to App Cache

### ISSUE THREAD

**Issue by andreev-artem** [slightlyoff/ServiceWorker#697]
Hi all,

as far as I understood the replacement of App Cache is one of the major reasons in implementing Service Workers ("Service Workers are meant to replace the (oft maligned) HTML5 Application Cache").

I think there will be a long way until all browsers will fully support Service Workers. So it would be good to have ability to fallback to App Cache in the case if Service Worker is not implemented in current browser. In that case I guess a page will contain both App Cache manifest and Service Worker registration declaration.

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorker_API contains a note "For backwards compatibility, you could choose to use service workers and AppCache on the same web app to do equivalent things (if the AppCache will support doing those things, of course.) What happens in such a case is that browsers that don’t support Service Workers will use AppCache, and those that do will ignore the AppCache and let the service worker take over."

But as far as I can see for Chrome 42 it's not the case. Both ServiceWorker and AppCache are used simultaneously.

I see 9.5.11 in the spec. But I'm not sure if that is sufficient. Does that make sense to specify explicitly when AppCache should be used if page has ```navigator.serviceWorker.register``` call? Or any way to prevent AppCache to be used (I tried ```window.applicationCache.abort()``` - no luck).

**Comment by jungkees** [comment]
Here's the ticket: https://github.com/slightlyoff/ServiceWorker/issues/275. (And the spec change needed was filed in HTML bug tracker, too: https://www.w3.org/Bugs/Public/show_bug.cgi?id=27482).

> But as far as I can see for Chrome 42 it's not the case. Both ServiceWorker and AppCache are used simultaneously.

AFAICT, it should be in Chrome 42: https://codereview.chromium.org/625433002/. Could you elaborate the case that went different than you expected?

**Comment by andreev-artem** [comment]
I need to improve my ticket's search skills :)

Thank you.

It seems it's yet not fully implemented in Chrome: [Issue 410665](https://code.google.com/p/chromium/issues/detail?id=410665). And will be only in Chrome 47.

**Comment by mattto** [comment]
It is effectively implemented in Chrome. The page load is performed by the Service Worker and AppCache is ignored. But even though the appcache is being ignored, it still is created and updated. Stopping that is the remaining work on that bug.
