### ISSUE TITLE
ServiceWorker registration fails inside an https-origin IFRAME when the top-level page is not secure (e.g. http or data URI)

### ISSUE THREAD

**Issue by bsittler** [slightlyoff/ServiceWorker#700]
ServiceWorker registration currently fails inside an https-origin IFRAME when the top-level page is not secure (e.g. http or data URI.) Is this intended behavior? It means a non-ServiceWorker version of the IFRAME functionality needs to be maintained in parallel so long as unsecured IFRAME embedders need to keep working, even when the browser does in fact implement ServiceWorker.

**Comment by slightlyoff** [comment]
Hey @kinu, @jakearchibald : I can't tell if this is intentional in Chrome. I suspect not. Thoughts?

**Comment by kinu** [comment]
I suspect it's a bug in Chrome, let me take a deeper look.

**Comment by jakearchibald** [comment]
This should work (depending on the value of `sandbox`, if it's present https://github.com/slightlyoff/ServiceWorker/issues/648)

**Comment by jakearchibald** [comment]
Yeah, this is a Chrome bug - moved to https://code.google.com/p/chromium/issues/detail?id=489670

**Comment by kinu** [comment]
Actually it looks like it's expected behavior: https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-secure
https://code.google.com/p/chromium/issues/detail?id=489670#c3

**Comment by annevk** [comment]
Right, this is intentional. So reopening in case @jakearchibald missed that.

**Comment by jakearchibald** [comment]
Seen it, concede on the point. I can't see a way to make this work unless we can isolate the iframe (preventing `postMessage` from parent frames). Either way, it's not something that needs changing within service worker.
