### ISSUE TITLE
Consider dropping initServiceWorkerMessageEvent()

### ISSUE THREAD

**Issue by bashi** [slightlyoff/ServiceWorker#701]
`ServiceWorkerMessageEvent` has `initServiceWorkerMessageEvent()` [1], but I think we should drop this method because as the note[2] says, `initEvent()` method only exists for historical reason and we can use constructor to initialize events.

[1] https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#serviceworkermessage-event-initserviceworkermessageevent-method
[2] https://dom.spec.whatwg.org/#dom-event-initeventtype-bubbles-cancelable

**Comment by jungkees** [comment]
Agreed. @jakearchibald @annevk Can there be any concern about dropping this method considering devs historically having used the `initMessageEvent()`? (Although they're now defined as unrelated interfaces.)

**Comment by domenic** [comment]
+1, new events should not have this

**Comment by jungkees** [comment]
Thanks!
