### ISSUE TITLE
How to deal with cookie bombing

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#704]
@sirdarckcat pointed out the following attack:

An attacker that can execute scripts on an origin (XSS) could add large cookies meaning the ServiceWorker fails to update, as the response would be 500 or similar.

We should try and work around this by doing something like this as part of the update:

1. Let `response` be the result of fetching the SW with credentials
1. If fetch fails & cookies header length is greater than some extreme number of bytes,
  1. Let `response` by the result of fetching the SW without credentials + `Service-Worker: script no-credential-fallback` header
1. (continue update)

+@slightlyoff

**Comment by sirdarckcat** [comment]
Made a small demo https://sirdarckcat.github.io/manifest/index.html

**Comment by jakearchibald** [comment]
There should be a platform-wide solution to cookie bombing.

Even if we fix this for ServiceWorker fetches, it'll fail install if any request carries credentials. Also, the ServiceWorker has no access to `document` therefore no access to `document.cookies`.

**Comment by annevk** [comment]
If you can XSS you can also do a number of other attacks, such as poisoning storage or confused deputy attacks, no?

**Comment by jakearchibald** [comment]
Yeah, but in those cases a new SW can come in and attempt cleanup. Cookie bombing prevents that happening.

I'm not sure we should do something specific in service worker for cookie bombing, but browsers should do something to combat it.

I suggested this to our security team:

> If the browser makes a GET request that fails, and the cookies look "well dodgy", could try a request to the same url without credentials, and if it 200s (or 300s?) could we suggest to the user that their local state may be broken, & do they want to clear it?

**Comment by jakearchibald** [comment]
This should be solved by http://w3c.github.io/webappsec-clear-site-data/ - servers should return this on too much cookies.
