### ISSUE TITLE
Limit Cache API to HTTPS

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#709]
We should not introduce new APIs that offer persistence without HTTPS. I guess as with service workers, `self.caches` would still be exposed but nothing would work.

**Comment by wanderview** [comment]
Given there are storage alternatives, I think being able to feature detect a working Cache implementation would be useful here.  So I would prefer to not expose on untrusted origins vs just having it always reject.

**Comment by jakearchibald** [comment]
Hmm, I see how it would be useful for `window.caches` to be `undefined` on http, but nothing else behaves like this.

**Comment by wanderview** [comment]
If we could make a decision on way or the other soon it would be helpful to me.  I'm getting ready to let Cache API ride the release train on gecko and would like to get this in if we're doing it.

**Comment by wanderview** [comment]
Just to be clear, I'm fine with just rejecting with SecurityError.

**Comment by annevk** [comment]
I think we should just reject. That's the pattern set by service workers and every other API that's restricted to date.

**Comment by wanderview** [comment]
Will this have the same restrictions as .register()?  For example, an untrusted parent document opens an https iframe.  Should the iframe have access to caches?

**Comment by annevk** [comment]
It would be better if it did not. Otherwise you can cheat and use some kind of HTTPS `<iframe>` service to get persistent state within HTTP. (Of course there's other ways to get that today, but hopefully at some point there won't be.)

**Comment by jakearchibald** [comment]
Agreed, an HTTPS iframe in an HTTP page shouldn't have access to the cache API (well, it'll have access, but it'll reject). I think we get this feature "for free" using https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-secure

**Comment by wanderview** [comment]
And are talking about making self.caches throw or caches.open() (.keys(), etc) reject?

**Comment by annevk** [comment]
The latter.

**Comment by mattto** [comment]
Tracked in http://crbug.com/501380

**Comment by jungkees** [comment]
Addressed: a26c8a642b4caf607fceb762eefff00f797ed816. Thanks https://w3c.github.io/webappsec/specs/powerfulfeatures/#settings-secure!

**Comment by annevk** [comment]
Thank you!

**Comment by jungkees** [comment]
Closing.

**Comment by slightlyoff** [comment]
I have a real problem with this. I don't understand why we wouldn't also remove IDB, LocalStorage, document.cookies and all the rest if the persistence argument is the motivation.

**Comment by annevk** [comment]
I think we should, long term. Or at least make them less useful without HTTPS.

**Comment by jakearchibald** [comment]
F2F result:

* Apple: This should work on HTTP
* Mozilla: This shouldn't work on HTTPS
* Google: No strong feelings
* Microsoft: This should work on HTTP, but not a deal breaker

All vendors share the goal to move everyone to HTTPS

**Comment by jungkees** [comment]
Closing. If we come up with a need to allow it to work on HTTP, please re-open this.

**Comment by inexorabletash** [comment]
FYI, change landed in Blink (canary/dev). We'll listen for complaints (and point them here...)
