### ISSUE TITLE
Service worker not receiving fetch events from iframe with Blob URL source.

### ISSUE THREAD

**Issue by noah-freitas** [slightlyoff/ServiceWorker#712]
I have a document under the scope of running service worker.  It contains an `<iframe>` with a Blob URL as a `src`.  The blob URL was constructed in the outer document context and should therefore be [of the same origin](https://w3c.github.io/FileAPI/#originOfBlobURL) as the Service Worker; however, the service worker does not receive any `fetch` events from the inner document.

My service worker is registered to a scope of `'/'`.

Is this the expected behavior (no fetch events for blob URL documents created at the service worker's origin) or a bug?

**Comment by mattto** [comment]
Sounds like a bug, please file a bug including a repro case at the bug tracker of the browser you're using. If it's Chrome, it may be related to https://code.google.com/p/chromium/issues/detail?id=439697

**Comment by annevk** [comment]
Actually, it's not clear this is defined in the specification. Probably in part because blob URLs do not have a scope, only an origin (yet another reason why we should not have added scopes).

**Comment by jungkees** [comment]
It has been spec'ed: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#selection. The iframe in the OP should use the parent frame's SW registration. Closing.
