### ISSUE TITLE
UA shouldn't be required to invoke Soft Update on every navigation

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#715]
I'm not sure the UA should be required to run Soft Update on each navigation. The UA may want to coalesce the updates, so a barrage of reload or opening new tabs etc only results in one Soft Update in some time period. In Chrome's current implementation, if two update requests are triggered within one second of each other, only one update occurs. In future implementations, we may make this more like 10 seconds or something, to be easier on battery/network.

**Comment by jungkees** [comment]
I think it's a fair point considering mobile resource usage. But IIRC, one of the points @jakearchibald concerned about was doing it less often seems to make devs hard. Is it still true? or devtools might resolve the concern?

**Comment by mattto** [comment]
Yes I expect DevTools would resolve that concern. Update on Navigate isn't even that useful for development since you have to disable the HTTP cache and also remember to close controllees or use skipWaiting.

**Comment by jakearchibald** [comment]
> Update on Navigate isn't even that useful for development since you have to disable the HTTP cache and also remember to close controllees or use skipWaiting

I've found update on navigate really useful during development for testing update handling. I tend to have `must-revalidate` on my SW scripts so HTTP caching isn't a problem.

But if we're talking one second as a coalescing period, that seems fair if it's worth it.

Curious to know how Mozilla feels about this @nikhilm @wanderview.

**Comment by wanderview** [comment]
To be honest, we haven't gotten to any kind of optimization work.  So we haven't really seen this yet.  Some amount of coalescing seems reasonable to me, though.

**Comment by jungkees** [comment]
We had a resolution for this issue in the f2f during TPAC: https://github.com/slightlyoff/ServiceWorker/issues/759#issuecomment-151379602.

In sum, the Update request is just being dropped if there's an ongoing Update execution already in the queue for this registration.

Closing.
