### ISSUE TITLE
Is Jake still a `ghost-author`?

### ISSUE THREAD

**Issue by AFBarstow** [slightlyoff/ServiceWorker#716]
Given Jake is now listed as an Editor of the spec, perhaps the acks section - where Jake is described as a "ghost-author" - should be updated accordingly. 

Perhaps: s/Jake Archibald is a ghost-author of this document./A very special thanks goes to Jake Archibald./ (If that change is agreeable, I'd be happy to submit a PR; just let me know.)

**Comment by jakearchibald** [comment]
Yeah, good point. I'll happily make this change or accept a PR.

**Comment by jakearchibald** [comment]
@slightlyoff I was bowled over by your kind words here, I've removed them now I'm an editor, but still really appreciate them!
