### ISSUE TITLE
Is fetchEvent.client a performance concern?

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#723]
From https://code.google.com/p/chromium/issues/detail?id=470036

@mattto: 

> It's fairly costly for our implementation to populate client.visibilityState and client.focused when dispatching the fetch event. We have to hop from the IO thread to the UI thread and back again. Doing that on every network fetch would surely make SW slower than non-SW. 

I'd like to hear Mozilla's take on this @nikhilm @wanderview. If there are similar concerns, I'm happy to change this to a client ID, or perhaps rethink how we get this information from clients.

Other options include `fetchEvent.getClient()` which returns a promise, or move the state properties on `client` into something like `client.getState()` - although this makes iterating over clients to find a focused one kinda tough.

**Comment by annevk** [comment]
Only giving asynchronous access to clients, including from events, seems reasonable.

**Comment by jakearchibald** [comment]
With `.clientID` you're guaranteed some information about the client. You can match it up with previous recordings in IDB. `.getClient()` may return null by the time you ask for it (client has closed). I'm not sure it's a big deal though.

**Comment by annevk** [comment]
We might want both. And we might need to name it `clientId` for consistency with `getElementById`, though waiting for @domenic on feedback on that one.

**Comment by wanderview** [comment]
The ergonomics suck, but it seems getState() might be more reasonable given the feedback.  It seems to me the original post is saying its hard to atomically get the right information here.

Should we be providing sync attributes like this if we can't keep them updating live?

**Comment by jakearchibald** [comment]
Resolution: `fetchEvent.client` is going away.

It'll be replaced by `.clientId` (or ID) or `.getClient()` which resolves to a client. That bit's to be decided.

**Comment by jakearchibald** [comment]
Shall we punt this to v2 and discuss it at the f2f?

**Comment by jungkees** [comment]
I recall a request with this use case: https://github.com/slightlyoff/ServiceWorker/issues/609#issuecomment-77479970. Do we have an alternative way to support this case?

**Comment by jungkees** [comment]
As per the [resolution](https://github.com/slightlyoff/ServiceWorker/issues/723#issuecomment-123516555), I removed `FetchEvent.client` for now: 5e13e97a61cb8ade87c0c0b9fe39d3cb00fb6a8a. Also move this to milestone 2.

**Comment by bpowers** [comment]
I also have a personal use-case for this - `clientId` would be perfect.  The biggest thing is that I need a unique identifier on a `FetchEvent` corresponding to the client.  Async would be workable, sync would be better (for me).

**Comment by jungkees** [comment]
@bpowers thanks for your feedback. As noted above, it's agreed that this is required but just moved to the next milestone. We're planning to discuss this f2f in the last week this month.

If you can, giving us any short snippet or any usage where sync would be preferred would help.

**Comment by jakearchibald** [comment]
Moved `clientId` to v1. But there are race conditions to sort in terms of `onmessage` listeners.

**Comment by bpowers** [comment]
aah, cool!

@jungkees Sorry for the delay.  So my use case is having shared state in the service worker, but I want each client to have a unique descriptor that isn't tied to the service-worker-internal name of the resource.  Sort of like a file descriptor, actually, and like FDs it would be nice to use something like small integers rather than something like long uncollidable cryptographic hashes.  What I need from the browser is an unforgable `clientId`, I don't need any of the other info I can imagine being populated by `getClient`.  And additionally because I want to get this `clientId` on almost every request, its a bit nicer that it is sync than async.  So, it sounds like I'm late to the party, but its neat to hear this is in v1.

@jakearchibald are these races in the spec or implementation?  I'd be interested in lending some eyes.

**Comment by jungkees** [comment]
So, it's time to add `FetchEvent.clientId`, a sync attribute's getter, and an API to get a `Client` object by id. How about:

```js
onfetch = e => {
  clients.getClient(e.clientId).then(c => {
    c.postMessage("to the request's client.");
  });
};
```

Open to another name for `.getClient(id)` method.

@jakearchibald could you give more info about "race conditions to sort in terms of onmessage listeners"? Is it a separate issue or directly related to defining these attribute/method?

**Comment by annevk** [comment]
Just do `clients.get()`. No need to name the thing twice.

**Comment by annevk** [comment]
And return undefined if there is no client (which requires IDL changes, so you might have to use any for now 😟).

**Comment by jungkees** [comment]
Added `FetchEvent.clientId`: https://github.com/slightlyoff/ServiceWorker/commit/10cf0361f7fdd77e97c8aab09b1cfa874c89f531 and `Clients.ger(id)`: https://github.com/slightlyoff/ServiceWorker/commit/71d3ca5e2345939d11af8cfdacbd04f2833adade.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1222464

**Comment by mitar** [comment]
What if client is not available anymore when you do `Client.get(clientId)`? This is really bad regression for us. Because we were relying on `event.client.url`.

**Comment by mitar** [comment]
Aaaa. And `Clients.get` is not yet implemented in Chrome. But they removed `event.client` in favor of `event.clientId`.

**Comment by dstockwell** [comment]
@mitar sorry I'm not sure why github thinks my fork is authoritative and I don't work on ServiceWorker. That said, I think you're looking for https://code.google.com/p/chromium/issues/detail?id=552310

**Comment by mitar** [comment]
Thanks!
