### ISSUE TITLE
Response or Promise<Response> is invalid Web IDL

### ISSUE THREAD

**Issue by domenic** [slightlyoff/ServiceWorker#724]
Should just be `Promise<Response>`

**Comment by jungkees** [comment]
Is the reason the following?

> Each pair of flattened member types in a union type, T and U, must be distinguishable.
> Promise types do not appear in the above table, and as a consequence are not distinguishable with any other type.

It may not be a big deal as fetch() and cache.match() return a promise but still affect some of the existing implementations. Is there any reason Promise types can't be distinguishable within union's member types?

**Comment by annevk** [comment]
How will it affect existing implementations? Note that passing `Response` will just cast to `Promise<Response>`, it won't reject.

**Comment by domenic** [comment]
> Is the reason the following?

Yes

> Is there any reason Promise types shouldn't be distinguishable within union's member types?

Because any other type that you pass will just be cast to a promise immediately (via `Promise.resolve`, basically). This happens automatically via Web IDL.

**Comment by jungkees** [comment]
Ah I see. Thanks for the clarification. Will address this.

**Comment by bzbarsky** [comment]
The fact that promises don't appear in the distinguishability table is a bug, imo. // cc @heycam

That said, per spec you can in fact just write `Promise<Response>` and an incoming `Response` will get wrapped in a `Promise` via `Promise.resolve`.  The only reason you'd want to use the union is if you actually wanted different processing of some sort in the `Promise` and non-`Promise` cases.

**Comment by wanderview** [comment]
For performance, it might be nice to avoid an extra async callback if the SW synthesizes a Response.  That's pretty minor, though.

**Comment by bzbarsky** [comment]
Hmm, I guess the non-distinguishability of `Promise` may in fact be intentional now that I try to recall the spec history here...

**Comment by annevk** [comment]
Yeah, pretty sure it's intentional. The idea behind promises is that everything is forced async, so you don't start to depend on it sometimes being synchronous.

Implementations could still have some optimization when it's non-observable, of course.

**Comment by jungkees** [comment]
Tracked in http://crbug.com/513972.
