### ISSUE TITLE
Remove client request requirement from respondWith()

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#725]
> If response.type is "opaque", and request's associated request is a client request, set the respond-with error flag.

This is already a requirement per Fetch and done somewhat better there. `respondWith()` should just passthrough any response.

**Comment by annevk** [comment]
Note that you still have a non-normative description of sorts that mentions this.

**Comment by jungkees** [comment]
Sorry for having missed it. Addressed: 5b3af5b6e0dc16e34365a5dfc653ef398d3b07d4.
