### ISSUE TITLE
Active function?

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#726]
> If the active function is not the callback of the event handler whose type is fetch, then: 

Active function of what? This is a specification algorithm that sits behind IDL and cannot just invoke JavaScript stuff. This is the wrong way to make this requirement.

**Comment by annevk** [comment]
The way this should work is that you set a flag, dispatch the event, then unset the flag. And only allow the method to be used while the flag is set. I think I mentioned this once.

**Comment by annevk** [comment]
Also, it needs to be a flag on the event object. We wouldn't want other event objects to suddenly become reusable.

**Comment by annevk** [comment]
Which means you can probably reuse the "dispatch flag" in some way.

**Comment by jungkees** [comment]
Yeah, "dispatch flag" seems a good fit here. Wanted this but didn't understand how to back then. ;) Thanks for revisiting it!
