### ISSUE TITLE
When does the openWindow promise resolve?

### ISSUE THREAD

**Issue by aykevl** [slightlyoff/ServiceWorker#728]
I am trying to send a message to a page from a serviceWorker. The goal is to let the page respond to the click (opening what the notification is about).

With this code inside a `notificationclick` event handler:

```javascript
clients.openWindow(url).then(function(client) {
    client.postMessage(message);
});
```

There is a race between delivering the message event and attaching the `message` event listener (while loading the page). Experimentally, I have found that the only way to receive the event is to add the `message` event listener before `<html>`, like so:

```html
<!DOCTYPE html>

<script>
navigator.serviceWorker.addEventListener('message', function (event) {
    console.log('got message:', event.data);
});
</script>

<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
    (...)
```

This appears very unreliable to me (tested in Chrome for Android version 44 and 45).

A possible solution is letting the promise resolve around the `DOMContentLoaded` or `load` events. Another option could be to let the service worker detect when the page is loaded (via an event).

I have used a workaround: sending the needed information in the URL fragment identifier and navigating to the proper URL using `history.replaceState` in the client (webpage). This works reliable so far.

**Comment by jungkees** [comment]
Isn't the sync between listener setup and sender's posting a message between different threads rather a general case? I'm not sure whether a snippet below could help? /cc @jakearchibald 

```js
// Page
navigator.serviceWorker.addEventListener('message', function (e) {
    console.log('got message:', e.data);
});

document.addEventListener('DOMContentLoaded', e => {
  var controller = navigator.serviceWorker.controller;
  if (controller)
    controller.postMessage('clientloaded');
})

// SW
var client_id;
clients.openWindow(url).then(c => { client_id = c.id; });

self.onmessage = e => {
  if (e.data == 'clientloaded') {
    clients.matchAll().then(clients => {
      clients.forEach(c => {
        if (c.id == client_id) {
          c.postMessage('fromnotificationclick');
        }
      });
    });
  }
};
```

**Comment by smaug----** [comment]
I think we need some kind of explicit ready() on window side, which would resolve the promise
and probably also implicit ready() at page 'load' event time if the explicit ready() hasn't been used.
The current setup is just way too racy and guaranteed to cause issues on slow networks etc.

**Comment by jakearchibald** [comment]
F2F:

We should buffer messages until:

* Page onload
* Assignment to `navigator.serviceWorker.onmessage`
* Invocation of `navigator.serviceWorker.startMessages()` // TODO: bikeshed

No change on when `openWindow` resolves.

**Comment by smaug----** [comment]
(I'm slightly against making yet another broken onfoo event handler, but I guess since MessagePort already has similarly broken onmessage, doesn't matter too much.)

**Comment by jakearchibald** [comment]
FWIW I didn't know about the `onmessage` assignment thing and I consider it to be batshit. I'd much rather we just admitted that in some cases listener adding can have side-effects.

**Comment by jakearchibald** [comment]
F2F resolution: `startMessages` it is.

**Comment by jakearchibald** [comment]
I'd like us to consider allowing `addEventListener` to also trigger `startMessages`, then we don't need to expose `startMessages`.

**Comment by mkruisselbrink** [comment]
If `addEventListener` triggers `startMessages` you can't have multiple event listeners anymore. A library setting an event listener will prevent a later (but before document load) added event listener from other code to receive messages that were send before the listener was added.

**Comment by aykevl** [comment]
Just an idea: triggering `startMessages` on `load` or `DOMContentLoaded`.
This may not be a good solution either: libraries may want to do initialization in `DOMContentLoaded` and `onload` may be too late.
Other ideas:
 * Do `startMessages` immediately after `DOMContentLoaded` without exposing `startMessages`.
 * Expose `startMessages`, but do it anyway after `onload` in case the web app hasn't requested for it specifically.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1263734

**Comment by wanderview** [comment]
We decided to keep the previous f2f decision.  Messages are automatically started on DOMContentLoaded, but if you want messages before that you need to call `startMessages()`.  The `onmessage` assignment also implicitly calls `startMessages()`.

**Comment by jungkees** [comment]
@annevk I'm thinking of defining a task source called _client message queue_ on `Window` object and `WorkerGlobalScope` object. Then, `client.postMessage()` add a task to the _client message queue_ which is consumed by the even loop of those globals when the task source is enabled (like what `MessagePort` does). Enabling the task source can be done by invoking the _start client message_ algorithm from the three call sites: on `DOMContentLoaded` (or `onload`?), `onmessage` assignment, and `navigator.serviceWorker.startMessages()`.

I was thinking of defining the task source in the _service worker client_ which is a type of environment settings object, but then it can't cover the `DOMContentLoaded` case.

If the above outline makes sense, I'll make a PR to HTML.

/cc @domenic

**Comment by annevk** [comment]
Sounds reasonable.

**Comment by jungkees** [comment]
I made patches as follows:
 - https://github.com/slightlyoff/ServiceWorker/commit/c2db88b6b529a1709f1ba6f502778b37f17b1746
 - https://github.com/jungkees/html/commit/bca15cfc4465e0269c97408ac847de55900609ef (didn't make a PR yet)

I defined the task source in ServiceWorkerContainer object instead of the global objects. I think it's better since a ServiceWorkerContainer object is the target object at which the message event is dispatched, and we don't pollute the globals. Please review them.

**Comment by jungkees** [comment]
Addressed by https://github.com/slightlyoff/ServiceWorker/commit/5c0ecaeb423d04df7429bfaa2e5fbde9e42038e1 and https://github.com/whatwg/html/commit/d61594754338b16bbc1b9e7233600f4f6667d834

Closing.
