### ISSUE TITLE
Handle Fetch needs to use new hooks

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#729]
We revamped context in https://github.com/whatwg/fetch/issues/93 so now service workers needs to be updated to use these terms instead: https://fetch.spec.whatwg.org/#subresource-request

**Comment by jungkees** [comment]
I didn't know whole this has been through already. Most of the things are clear.

I'm trying to understand how I can rewrite the current Handle Fetch step 12.2:

1. Else if request is a client request, then:
  1. If request's context is "iframe" ..

**Comment by jungkees** [comment]
So an old _client request_ would be replaced by a _non-subresource request_.. And then do I have a way to get the "iframe"?

**Comment by annevk** [comment]
Why exactly does the service worker specification need to know about nested browsing contexts?

**Comment by annevk** [comment]
That is, I don't understand what "If client's responsible browsing context's parent browsing context's Window object's service worker client's active worker activeWorker is not null, set registration to activeWorker's containing service worker registration." actually does.

**Comment by jungkees** [comment]
That is, when the iframe is navigated, the request's url is local, and its parent frame has an active worker, it'd use the parent frame's registration instead of matching SW registration.

**Comment by annevk** [comment]
If the URL is local, why would it go to the service worker? Only http/https goes to the service worker.

**Comment by jungkees** [comment]
Yeah, fetch will not call the Handle Fetch in that case, right? But here's the discussion we had for this: https://github.com/slightlyoff/ServiceWorker/issues/612. That considered, inheriting a parent's controller for local url's should be done in fetch instead of the Handle Fetch?

**Comment by jungkees** [comment]
Or fetch might want to route them through SW too?

**Comment by jakearchibald** [comment]
If an iframe is loaded with a blob url, it'd be great if it could use the parent window's SW, as in #612.

Is checking for a parent browsing context enough here?

**Comment by annevk** [comment]
I'm not entirely sure, I suspect hooking into the creation of the browsing context is the answer here. But what is currently in the specification is broken (with or without the changes in Fetch).

**Comment by jungkees** [comment]
If fetch could call the Handle Fetch for local urls, I think I could try something like:
> If request's client's responsible browsing context is a nested browsing context and request's url is local, use parent browsing context's Window object's service worker client's active worker if exists.

**Comment by annevk** [comment]
No. Fetch should not invoke service workers for local URLs. That doesn't make sense. What needs to happen is that environments created from local URLs inherit the service worker somehow. This should probably happen when such an environment is created. This applies to both browsing contexts and workers by the way, not just browsing contexts.

**Comment by jungkees** [comment]
Applied the new hooks and added a text that explains the selection of the registration for the local url (in a nested browsing context or a worker) case: 9e5e85e71b6da3c8fb851c2ea4a9d42a2b893f04.

**Comment by jungkees** [comment]
Added some missing bits: 09a01e34083211e42e446049b808912c3484ae48.

Closing.
