### ISSUE TITLE
Make importScripts() fail outside install

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#730]
I thought we had agreed that `importScripts()` should fail outside of installation? Otherwise we still have an unrestricted synchronous IO API...

**Comment by wanderview** [comment]
It seems maybe "imported scripts updated flag" should be set at the end of the top level worker script evaluation instead of at the end of the first importScripts() call?

**Comment by jungkees** [comment]
Sorry that I had missed this part of the work. Addressed it: 0e021ef91758f41690b9a713b26df83a14220693.

> It seems maybe "imported scripts updated flag" should be set at the end of the top level worker script evaluation instead of at the end of the first importScripts() call?

Thanks for spotting this. I think the flag should be set only when all the `importscripts(urls)` have been successfully run without any runtime errors. So I put this step in the [Install](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#installation-algorithm) algorithm step 17.

**Comment by jungkees** [comment]
Closing.
