### ISSUE TITLE
should scope matching do substring comparison within a path element?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#734]
Currently step 3 of [scope matching][https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#scope-match-algorithm] is:

> Let matchingScope be the longest [[key]] in scope to registration map starting with the value of clientURLString.

Currently this wording means that '/some/scope' would match '/some/scopeislong'.  These two scopes represent peers in the sites tree structure.

It seems very surprising that these two match because it prevents you from having separate service workers for separate parts of your tree simply due to one being a substring of the other.

**Comment by mkruisselbrink** [comment]
I don't understand the problem? If there are service workers for both those scopes, the scopeislong one will match every path that starts with /some/scopeislong while the other service worker will match every other path that matches /some/scope (including /some/scopeisalsolong). That seems perfectly reasonable to me.

Although I do agree that that step is confusingly written. It almost reads like it is asking for the longest scope where key.startsWith(clientURLString) is true, while it should be the longest scope where clientURLString.startsWith(key) is true.

**Comment by wanderview** [comment]
I guess the longest key does prevent what I am seeing.  I guess this might just be a gecko bug.

**Comment by nikhilm** [comment]
This was a bug in the way the service_worker_unregister_and_register() function is used in some SW tests. and can be closed.
