### ISSUE TITLE
Should FileReaderSync be exposed to service workers?

### ISSUE THREAD

**Issue by mattto** [slightlyoff/ServiceWorker#735]
FileReaderSync is an sync IO API, should service workers be allowed to use it?

**Comment by wanderview** [comment]
There is a non-normative note in the spec:

> Any type of synchronous requests must not be initiated inside of a service worker.

I guess we could take away the footgun by making things like FileReaderSync and sync XHR [Exposed=DedicatedWorker,SharedWorker].

**Comment by annevk** [comment]
XMLHttpRequest/ProgressEvent was changed earlier today. See: https://xhr.spec.whatwg.org/.
