### ISSUE TITLE
FetchEvent is non cancelable yet checks canceled flag

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#741]
Spec "Create a trusted event e that uses the FetchEvent interface, with the event type fetch, which does not bubble, is not cancelable, and has no default action."

But later "If event's canceled flag is set, then:

    Set eventCanceled to true.
"

The DOM spec says preventDefault() can only set the canceled flag if the event is cancelable. [1]

[1]: https://dom.spec.whatwg.org/#dom-event-preventdefault

So cancelable or not cancelable?

**Comment by nikhilm** [comment]
@jungkees @jakearchibald

**Comment by jungkees** [comment]
@nikhilm I'll respond it after checking our previous discussion in the repo. Thanks for spotting this!

**Comment by jungkees** [comment]
`FetchEvent` should be cancelable: https://github.com/slightlyoff/ServiceWorker/issues/51#issuecomment-51172079. Thanks!
