### ISSUE TITLE
Possible run-to-completion violation in "Handle Service Worker Client Unload"

### ISSUE THREAD

**Issue by nikhilm** [slightlyoff/ServiceWorker#746]
Consider the first test at https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/http/tests/serviceworker/unregister-then-register-new-script.html

In this big block:

    .then(function(r) {
          new_registration = r;
          assert_equals(registration.installing.scriptURL,
                        normalizeURL(new_worker_url),
                        'before activated registration.installing');
          assert_equals(registration.waiting, null,
                        'before activated registration.waiting');
          assert_equals(registration.active.scriptURL, normalizeURL(worker_url),
                        'before activated registration.active');
          assert_equals(new_registration.installing.scriptURL,
                        normalizeURL(new_worker_url),
                        'before activated new_registration.installing');
          assert_equals(new_registration.waiting, null,
                        'before activated new_registration.waiting');
          assert_equals(new_registration.active.scriptURL,
                        normalizeURL(worker_url),
                        'before activated new_registration.active');
          iframe.remove();
          return wait_for_state(t, registration.installing, 'activated');
        })

At `iframe.remove()`, "Handle Service Worker Client Unload" will run. Note that the call to `register(new_worker_url)` did not lead to the `uninstalling flag` being reset to `false` since the conditions are not satisfied in `[[Register]]` (Is this a bug at that point?).

This leads to the underlying registration being cleared (`[[Clear Registration]]`), so that the call to `registration.installing` will be null according to spec. Blink seems to pass the test due to asynchronicity between their processes, but according to spec this seems like a violation of run-to-completion with installing changing.

IMO this should not actually happen since the `reset uninstalling flag` conditions need to be relaxed. In either case this sounds like a BigDeal issue.

@jakearchibald @jungkees

**Comment by jungkees** [comment]
Good catch! Thanks for spotting this.

In this case, the registration should not be cleared as it's already under an update with its installing worker. To resolve this, I added a condition (ef4bff338f5808c0965d3d55c8800e35a79ddb90) checking whether a registration has a non-null newest worker before clearing the registration: [Handle Service Worker Client Unload](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#on-client-unload-algorithm) step 5. Indeed, this newest worker check was added to all the other part of the steps that try to clear a registration. (I think I missed it for this algorithm.)

**Comment by nikhilm** [comment]
Shouldn't uninstall flag also be reset to false though? register does not do that since the conditions are not satisfied. I think those conditions need to be relaxed.

**Comment by nikhilm** [comment]
Otherwise the next call to Match Service Worker Registration is going to return null because uninstalling flag is set.

**Comment by nikhilm** [comment]
Another option is to have Update reset the flag after it has successfully installed a new worker, but at this point I'm just shooting ideas and not thinking about this carefully.

**Comment by jungkees** [comment]
> Shouldn't uninstall flag also be reset to false though?

Yes, resetting it right away seems better to reflect that instant.

> Another option is to have Update reset the flag after it has successfully installed a new worker

We're already doing so in Install step 22.1.

> Otherwise the next call to Match Service Worker Registration is going to return null because uninstalling flag is set.

Even if we reset the flag in Handle Service Worker Client Unload and Install step 22.1, I think this still can happen when Match SWR is run while the Update/Install steps are running with the registration's uninstalling flag is set. But this seems fine as Match SWR returns the result reflecting that instant. That is, if the flag is reset by the installation success later on, the subsequent Match SWR will again return the registration.

A thought just came to my mind. With the current behavior, an installation failure doesn't have a chance to reset the uninstalling flag in this scenario, meaning that the registration will be cleared. Is this desirable? Or should we reset the flag at the beginning of Update? (i.e. interpreting the update attempt always should cancel the ongoing uninstallation regardless of the result.)

**Comment by jungkees** [comment]
To sum, how about the following change?

- Move Install step 22 to Update step 1 so it look like:
```
Update algorithm
1. If registration's uninstalling flag is set, unset it.
```
- Change Handle Service Worker Client Unload step 5 back to the previous state:

If registration's uninstalling flag is set removing ~~and the result of running Get Newest Worker algorithm passing registration as the argument is null~~, invoke Clear Registration algorithm passing registration as its argument and abort these steps.

This change still resolves the OP issue as by the time `iframe.remove()` is called, the registration's uninstalling flag has been unset by `register(new_worker_url)`. But this brings a change in behavior that the registration will not be cleared when:

1. Unregister
1. Update
1. Update above failed

I like this behavior as it's simpler to reason about. Yeah, the Update is followed (and just failed).

Thoughts?

**Comment by nikhilm** [comment]
I think it makes more sense to move Install step 22 to Register step 1 rather than Update step 1. This is because if a dev calls unregister(), but then the UA updates as part of the 24 hour cycle, it is unpredictable and non-reproducible across sessions, whereas Register is always triggered by JS invocation. Otherwise, I am happy with the suggestions in the comment above. The invariant then imposes linearity on the "is registration still around or is it cleared?" based on the order of calling unregister() and register().

**Comment by jungkees** [comment]
`registration.update()` doesn't get through Register, so Update seems the right place to cover all the update paths. For the SoftUpdate case, how about creating a flag passed to Update algorithm which when set by SoftUpdate will not unset the uninstalling flag? (i.e. SoftUpdate will not block uninstalling.) 

Also, I'd like to hear opinion from Blink side about this algorithm step change too. / cc @nhiroki @michael-nordman (Seems @mattto is ooo now.)

**Comment by nikhilm** [comment]
Rather than add a flag to Update, I'd rather Register and SWRegistration.update() modify the flag before calling Update.

**Comment by jungkees** [comment]
I thought the following: (as Update cancelling the uninstalling registration by default seems reasonable as we've done so far. Soft Update can choose whether the caller wants the cancellation or not.)

[Update](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#update-algorithm) has _cancel uninstallation flag_, an optional flag unset by default

Update

1. If registration's uninstalling flag is set and _cancel uninstallation flag_ is unset, then:
  1. Unset registration's uninstalling flag.

Soft Update
...
Invoke Update algorithm with its arguments and _cancel uninstallation flag_ set.

WDYT?

**Comment by nikhilm** [comment]
err, I should have been more clear about the use of 'flag' in my comment. I meant that I would rather have register() and SWRegistration.update() modify the *registration's uninstalling* flag before calling Update() instead of adding a default argument to Update and Soft Update. But that is pretty much my API design brain talking about making things explicit and not having default boolean flags. I don't know how it works for web platform algorithms.

**Comment by jungkees** [comment]
Your design sounds good to me. I found the current behavior as-is actually seems odd and needs clarification. It currently does:
 - register() does not cancel uninstall until it resolves with a registration (either resolves with the existing registration or successful installation of a new version).
 - [update() step 2](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#service-worker-registration-update) aborts the steps! meaning it doesn't cancel the uninstall. I think it should be fixed.

So, to sum again, we'd want:
 - register() method and update() method unset the uninstalling flag (i.e. cancel the uninstall).
  . This conforms to our earlier discussion that we don't want to aggressively uninstall registrations.
  . Devs will deal with any installation failure on those retaining registrations.
 - Soft Update will not unset the uninstalling flag (i.e. does not cancel the uninstall).
 - Remove [Install step 22](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#installation-algorithm) (i.e. the decision of the cancellation of the uninstall doesn't depend on whether the installation succeeds or fails. They are all done by the callers as @nikhilm suggested).

Is that clear?

**Comment by jungkees** [comment]
Sorry about this but as another option:

Soft Update is currently aborting at step 2: "If registration's uninstalling flag is set, abort these steps." So it does not update and let the registration be uninstalled. With this fact respected, if we encounter needing to add other callers of the Register and Update in the future, it'll be better to place the cancelling the uninstall step within the (Update) algorithm rather than in each caller side.

So, I'd like to hear your opinion.

**Comment by wanderview** [comment]
@jungkees Can the fix to this issue be included in the v1 CR?

**Comment by jungkees** [comment]
Yes, I agree that this should be included in the V1.

**Comment by wanderview** [comment]
I don't think @nikhilm will be able to help here any further.  I've asked @khuey to look at it since he's familiar with the problem on our end.

**Comment by jungkees** [comment]
Before the f2f on this Tue, I'm trying to sort out my thoughts on this. @nikhilm's original suggestion basically makes sense so it would be:

- Register algorithm unset the uninstalling flag (without any condition)
- `update()` will return early (as-is)
- Soft Update algorithm will not unset the flag (naturally as it’s moved to Register)

The only question myself as of now is the second item: `update()` should block uninstalling a registration and go ahead with an update instead?

**Comment by jungkees** [comment]
F2F: agreed on https://github.com/slightlyoff/ServiceWorker/issues/746#issuecomment-150904985.

**Comment by wanderview** [comment]
I believe gecko is already doing this, so no tracking bug on our side.

**Comment by wanderview** [comment]
Correction, we still need to fix it.
