### ISSUE TITLE
Typescript file and spec are not in sync

### ISSUE THREAD

**Issue by mkruisselbrink** [slightlyoff/ServiceWorker#750]
It doesn't seem like the typescript file and the spec are kept in sync as the README.md file seems to require. Is the typescript file just no longer used (and thus should it and the comment to keep it up-to-date be deleted), or is the file still supposed to reflect the current spec?

**Comment by jungkees** [comment]
Thanks for bringing this question. We discussed this and decided to drop the TS file as we have the full spec now. I removed the file and related text from the README.md: a0cc74ca242c56be78c25bbbc2db12ffc5d933ae.
