### ISSUE TITLE
how does SoftUpdate "force bypass cache flag" get set?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#753]
Currently the SoftUpdate algorithm takes a "force bypass cache flag".  How does this ever get set?  Is it needed any more?

**Comment by jungkees** [comment]
Currently no callers in the spec sets the _force bypass cache flag_ as pointed. I just left it there for some potential use from implementers (e.g. calls from devtools) as of now.

There's another aspect. Algorithms in other specs are supposed to dispatch their functional events by invoking [Handle Functional Event](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#handle-functional-event-algorithm) which calls Soft Update at its last step without setting the flag. I'm not sure whether it makes sense but some algorithms may want to call Soft Update directly and with the flag set on their own need.

Does the above usage make sense? Or should be drop the flag?

**Comment by wanderview** [comment]
That makes sense to me, but a note might help other people reading the spec.  Thanks.
