### ISSUE TITLE
seems possible to trigger many update fetches after 24 hour limit expires

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#759]
Step 7 of Handle Functional Event checks the last update time:

> If the time difference in seconds calculated by the current time minus registration's last update check time is greater than 86400, invoke Soft Update algorithm, or its equivalent, with registration.

Step 13 of the Update algorithm ultimately sets the last update time:

> If response's cache state is not "local", set registration's last update check time to the current time.

Of course, it only does this after the async step 11:

> Let response be the result of running fetch using r.

While waiting for the fetch you may end up with multiple update requests queued.

Now each update will run sequentially thanks to step 4.1 doing the CheckPriority step, but they will each attempt a network fetch.  I guess http cache may avoid the network hit here, but we're still doing a lot of extra work.

Can we somehow de-bounce these updates?  Like don't queue updates for the 24 hour expiration unless the queue is empty?  This would let .update() still force another update, but avoid a burst of events triggering a lot of soft updates.

**Comment by wanderview** [comment]
> Can we somehow de-bounce these updates? Like don't queue updates for the 24 hour expiration unless the queue is empty? This would let .update() still force another update, but avoid a burst of events triggering a lot of soft updates.

I guess I mean here a soft update should avoid queue an update if an update is already running or queued.

**Comment by jungkees** [comment]
Good point. I'm not sure whether this is kind of an optimization point for implementations or something we'd want to put in the spec though.

If we want to spec it, I think we can use the [registration queue](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#dfn-registration-queue-adt) to see if calling an update is needed (i.e. if the registration queue is not empty, the caller can just return).

Also, will it make sense to put that line in the Soft Update? Or in the caller of the Soft Update? (e.g. Handle Fetch, Handle Functional Event).

**Comment by jungkees** [comment]
I think the name, _registration queue_, is a bit misleading as it deals with the update jobs. Better to rename it to _update queue_?

**Comment by wanderview** [comment]
I think it has to be done in the update algorithm since the queue is handled there, right?  Soft update could set a flag as an argument to update.

**Comment by jungkees** [comment]
The Soft Update can also access the registration queue (as its per registration - keyed by its scope url) so can do it in its step 7 like:

> If the _registration queue_ for _registration_ is not empty, invoke Update algorithm, or its equivalent, passing client and registration as its argument with force bypass cache flag set only if its own force bypass cache flag is set.

And similarly we can do it in the callers of the Soft Update too.

**Comment by jungkees** [comment]
F2F: Agreed on https://github.com/slightlyoff/ServiceWorker/issues/759#issuecomment-147920039.
