### ISSUE TITLE
step 3 of 9.15 Match Service Worker Registration has a typo

### ISSUE THREAD

**Issue by bsittler** [slightlyoff/ServiceWorker#760]
In both versions of the spec this step currently reads:

```html
      <li>Let <var>matchingScope</var> be the longest [[key]] in <a href="#dfn-scope-to-registration-map">scope to registration map</a> starting with the value of <var>clientURLString</var>.</li>
```

Interpreted literally, this requires the clientURL to be a prefix or exact match of the matching scope, which means e.g. a single registered scope /foo/bar matches a client at /foo/qux but not a client at /foo/bar/baz. This also does not agree with behavior of current implementations.

Possible improvement, though a less awkward wording would be even better:

```html
      <li>Let <var>matchingScope</var> be the longest [[key]] in <a href="#dfn-scope-to-registration-map">scope to registration map</a> which is a prefix or exact match for the value of <var>clientURLString</var>.</li>
```

(Originally pointed out by @mkruisselbrink in a comment on #734 https://github.com/slightlyoff/ServiceWorker/issues/734#issuecomment-132336711 )

It also may be worth clarifying that client URL matching is prefix-based rather than path-structural, so for example in the absence of a more specific [[key]] in the scope-to-registration map and provided the origins match, a client URL with path /~evelyn/index.html will match a registration for a scope with path /~eve as discussed by @wanderview in #734

**Comment by jungkees** [comment]
Thanks for reminding, @bsittler!
