### ISSUE TITLE
getRegistrations is vague

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#762]
I cannot really parse "For each Record {[[key]], [[value]]} entry of its scope to registration map:". Does "its" mean the context object?

What happened to getting all registrations for an origin?

**Comment by wanderview** [comment]
I believe this means, "for each record in the origin's scope-to-registration map".  The map is per origin, not per scope.  The sentence is confusing, though.

**Comment by jungkees** [comment]
"its" was not clear in that text. A _scope to registration map_ is not per origin but a global data structure that a user agent maintains.
