### ISSUE TITLE
Unregister is broken

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#763]
This algorithm has this line "If no service worker client is using registration, then:", so it basically terminates if there is a client using registration. Which is pretty much always true since you just called `unregister()` on it.

**Comment by wanderview** [comment]
Step 4 of Unregister (before that conditional):

> Set registration's uninstalling flag.

And then in Handle Service Worker Client Unload:

> If registration's uninstalling flag is set, and the result of running Get Newest Worker algorithm passing registration as the argument is null, invoke Clear Registration algorithm passing registration as its argument and abort these steps.

**Comment by annevk** [comment]
Interesting. A note of that side effect would be useful.

**Comment by wanderview** [comment]
Sure, although arguably that's the main point of uninstalling flag.  If the worker is actively being used for a client, we can't just pull the rug out from under it.  We have to flag the requested state change and handle it when the resource is free.

A note would be nice, though.
