### ISSUE TITLE
getRegistration IDL is wrong

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#764]
It seems you require https://github.com/heycam/webidl/issues/60 to be fixed since you return undefined at times yet the IDL does not cover that.

**Comment by wanderview** [comment]
Is this really a problem since a Promise is always returned?  We're really talking about the promise resolved value type, right?

**Comment by annevk** [comment]
Yes and yes.

**Comment by jungkees** [comment]
We have no choice but to use `any` until heycam/webidl#60 is addressed?

**Comment by annevk** [comment]
Yeah...

**Comment by annevk** [comment]
That fix does not seem correct. "void" is fine for anything that returns undefined exclusively. A specific type however does not work for something that might return undefined. Only then do we need to use any.

**Comment by jungkees** [comment]
I thought that way too, but the IDL definition for void seems only be allowed to be used for return type (i.e. not for promise resolution value): https://heycam.github.io/webidl/#es-void.

> The only place that the void type may appear in IDL is as the return type of an operation.

**Comment by annevk** [comment]
Well, https://heycam.github.io/webidl/#es-promise handles void explicitly. So that is probably a simple bug.
