### ISSUE TITLE
should respondWith(undefined) be treated the same as not calling respondWith()

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#766]
@ehsan debugged the guardian's new service worker on firefox this morning:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1217501

It seems its calling respondWith(undefined) in some circumstances.  Firefox treats this as a NetworkError because undefined is not a Response.  It seems chrome treats respondWth(undefined) the same as not calling respondWith() at all.

What is the desired behavior?

The spec actually says that respondWith(undefined) should return an error.  In respondWith() step 6.3:

> 1) f response is a Response object, then:
>   ...
> 2) else:
>  1) Set the respond-with error flag.

I can see why maybe the chrome behavior would be desired, though.

cc / @jakearchibald

**Comment by jakearchibald** [comment]
Ohhh, no I think Firefox is doing the right thing here. Let me help The Guardian fix this, and file a bug with Chrome.

Thanks for spotting this!

**Comment by wanderview** [comment]
Actually, I'm now wondering how this would actually break the site, though.  It seems it only does this when fetch(event.request) has already failed...

Maybe our analysis is wrong.

**Comment by jakearchibald** [comment]
Yeah, I'm looking at their code now, and can't see when undefined is returned when it shouldn't be

**Comment by jakearchibald** [comment]
Undefined is returned to `respondWith` if all of the following is true:

* The original `fetch(event.request)` failed
* There's no match in the cache
* The request does not have `text/html` in its `Accept` header (this is sniffing for a navigation-like request)

Returning undefined seems reasonable here, and should be treated as a network failure.

**Comment by wanderview** [comment]
Sorry, I jumped the gun here.

I actually see a Promise.all().concat() which I think is a chrome-specific extension.

**Comment by jakearchibald** [comment]
Hm, we do have specific extensions (and I [hate that we do](https://code.google.com/p/v8/issues/detail?id=3237)), but I don't think concat is one.

**Comment by wanderview** [comment]
Yea.  I need more coffee.  I misread the code.  Its inside the Promise.all() on the array.  I'll stop "helping" here.

Sorry for the noise.  Mystery continues...

**Comment by jakearchibald** [comment]
Hah, I read the concat as being chained onto the `.all` too, for what it's worth.
