### ISSUE TITLE
Are the members of ServiceWorkerRegistration really [SameObject]?

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/ServiceWorker#767]
That is, does `installing`, for example, return the same value for the entire lifetime of the `ServiceWorkerRegistration`?  That seems quite odd to me, though I have not sorted through the processing model very carefully...

**Comment by ehsan** [comment]
These attributes can change their values from/to null, so they should not be `[SameObject]`.  I'm changing Gecko accordingly, I'd appreciate if you could update the spec.  Thanks!

**Comment by jungkees** [comment]
Yes. Noticed that. I'll do that. Thanks!
