### ISSUE TITLE
ServiceWorkerContainer.controller prose says to return undefined, but the IDL doesn't allow that

### ISSUE THREAD

**Issue by bzbarsky** [slightlyoff/ServiceWorker#769]
The IDL says:

    readonly attribute ServiceWorker? controller;

and undefined is not a valid `ServiceWorker?` value.

What you would probably want is for the property to not exist in a secure context at all, right?

**Comment by jungkees** [comment]
We plan to discuss this in web app security WG meeting what the expected behavior for getter in non-secure context should be. I'll update the spec depending on the result.

**Comment by jakearchibald** [comment]
F2F: update spec. Property won't exist in non-secure contexts

**Comment by jungkees** [comment]
Closed by 5264a72e5336b7440e3a3b3cc9e84c05d3dd3a89
