### ISSUE TITLE
The user agents?

### ISSUE THREAD

**Issue by marcoscaceres** [slightlyoff/ServiceWorker#774]
If there some reason why we talk about "user agents" in plural form?

If not, then maybe change: 

> The user agents must persistently keep a list of registered service worker registrations unless otherwise they are explicitly unregistered. 

To: 
> A user agent must persistently keep a list of registered service worker registrations, unless those registrations have been explicitly unregistered.

**Comment by jungkees** [comment]
@marcoscaceres thanks for review. I tried it: e7ddda2b4dbff797c4c801a9dd897034f90419e4. But regarding an article, I'm not quite sure I've done a right thing. Please review.
