### ISSUE TITLE
Add example for Service-Worker-Allowed

### ISSUE THREAD

**Issue by marcoscaceres** [slightlyoff/ServiceWorker#775]
I imagine a lot of people will want to do this: 

```JS
navigator.serviceWorker.register("/js/sw.js", {scope: "./"});
```
Because having a sw.js sitting in the root is just ugly. 

However, the `Service-Worker-Allowed` header is mega confusing to use, and the corresponding spec text is (for me?) very hard to understand. 

Can we please add an example for how to use this in the common case above... also, can we please add some examples for how the `{scope: "whatever"}` and the `Service-Worker-Allowed` header value are combined to come up with `maxScope`, etc.?

Thanks! :heart:

**Comment by marcoscaceres** [comment]
(FWIW, Chrome's error messages when using `Service-Worker-Allowed` are super helpful... I was trying to do this in Firefox and it currently provides little help apart from the security error :crying_cat_face:).

**Comment by wanderview** [comment]
gecko console reporting bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1220757
