### ISSUE TITLE
Add note that activate event cannot fail SW activation

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#776]
Currently the activate algorithm reports exceptions from the activate event handler, but still allows activation to complete.  In addition, it allows the activate event handler to be killed due to timeout with the SW still activating.

I see that this was intentional due to issue #447.

It would be nice, though, to add a note to the spec that this is intentional.  The reasoning behind this behavior is not immediately obvious when reading the spec.

**Comment by mattto** [comment]
For reference, more extensive discussion was in #659 (the original title was "A worker that fails to activate should relinquish its controllees" and later updated to reflect the decision).
