### ISSUE TITLE
should service worker still install if onerror event handle cancels error from uncaught exception?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#778]
In the wpt tests we're porting from the blink code base there are two tests that allow the SW installation to continue if an uncaught exception's resulting error event is canceled:

```
self.onerror = function(event) { return true; };

self.addEventListener('install', function(event) { throw new Error(); });
```

And:

```
// Ensure we can handle multiple error handlers. One error handler
// calling preventDefault should cause the event to be treated as
// handled.
self.addEventListener('error', function(event) {});
self.addEventListener('error', function(event) { event.preventDefault(); });
self.addEventListener('error', function(event) {});
self.addEventListener('install', function(event) { throw new Error(); });
```

I see nothing in the spec about allowing installation to continue if the onerror event handler "handles" the error:

> 1. If any uncaught runtime script error occurs, then:
>   1. Report the error for the script per the runtime script errors handling.
>   2. Run the Update State algorithm passing registration's installing worker and redundant as the arguments.
>   3. Set registration's installing worker to null.
>   4. Pop the top element from installation queue and installation result handle queue.
>   5. If the result of running Get Newest Worker algorithm is null, then:
>     1. Invoke Clear Registration algorithm passing registration as its argument.
>   6. Abort these steps.

If I understand things correctly, handling the error in a worker onerror handler is supposed to keep the error from bubbling to the parent document.  That seems different than life cycle management in the SW, though.  Also, the SW has no parent document for it to bubble to.

**Comment by jakearchibald** [comment]
Yeah, I think Chrome's getting this wrong.

http://jsbin.com/hokowi/edit?js,console - we don't allow an idb to be created if an error is thrown in its `upgradeneeded` event, even if `window.onerror` returns true. 

IDB uses the following language:

> If an exception was propagated out from any event handler while dispatching the event in the previous step, abort the transaction

This seems to make sense to me. The error *has* propagated out from the event, so it should abort the transaction even if the error is "handled" in `window.onerror`. I think service worker should follow this model.

**Comment by wanderview** [comment]
Ok, thanks!  I will amend the test on our side and I guess we just need some kind of similar logic in the spec here.

**Comment by wanderview** [comment]
I wrote a chrome issue here.  It probably needs to be triaged, though:

https://code.google.com/p/chromium/issues/detail?id=553558&thanks=553558&ts=1447096897
