### ISSUE TITLE
Disabling the secure origin check via flags

### ISSUE THREAD

**Issue by nolanlawson** [slightlyoff/ServiceWorker#779]
Not sure if this is appropriate to this repo, but just leaving some feedback here...

Being able to use localhost is great for quick debugging, but I like testing real devices on my local intranet, to see how they perform. Currently I have to deploy to my actual SSL-enabled production server in order to actually test ServiceWorkers.

It would be nice if there were a flag in `chrome://flags` to disable the secure origin check, or some other way client-side to handle this. Maybe a popup that says "this site is trying to do something malicious" - "get me out of here" / "add exception"?

**Comment by jakearchibald** [comment]
Checkout the --unsafely-treat-insecure-origin-as-secure command line flag. You also need to specify a new user profile location for it to work https://code.google.com/p/chromium/issues/detail?id=441605#c67

**Comment by nolanlawson** [comment]
Sweet, thanks!

**Comment by abubakarm** [comment]
how about doing this on android chrome.

**Comment by jakearchibald** [comment]
@abubakarm please request this at crbug.com if it's something you're interested in.
