### ISSUE TITLE
register() should not allow file://, wss://, etc

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#780]
Is it intended that .register() now allows file:// (and wss://, etc) URLs? It simply says:

> * If the result of running Is origin potentially trustworthy with the origin of scriptURL as the argument is Not Trusted, then:
>   * Return a promise rejected with a "SecurityError" exception.

But the Is origin potentially trustworthy algorithm now allows file schemes:

> If origin's scheme component is file, return "Potentially Trustworthy".

Note, Cache API still does explicitly requires http or https URLs for all Requests. So its not really feasible to load a site from file:// and have the service worker function correctly.

I spoke with @jakearchibald on IRC and he agreed we should block file://.  I think to be safest we should explicitly check for https:// or http:// after the security check.

**Comment by wanderview** [comment]
These scheme checks should also be performed on the script URL.  For example, a blob: URL may return an origin that matches the page, but we don't want to allow blob URLs as SW scripts.

**Comment by wanderview** [comment]
In this gecko bug I am adding an explicit http/https scheme check against the script URL after step 3 in the register algorithm.  I am throwing SecurityError if it fails.

https://bugzilla.mozilla.org/show_bug.cgi?id=1223378

**Comment by jungkees** [comment]
I recall this issue was discussed here: https://github.com/slightlyoff/ServiceWorker/issues/601#issuecomment-128635909.

file:// and wss:// are basically filtered out in fetch. blob: URL will be filtered out by checking the MIME type in Update step 4.13.

The reason I didn't explicitly add http/https requirement is just to defer to what secure contexts define for the forward conformance.

A note will do here? Or better to add the step?

**Comment by wanderview** [comment]
What do you mean filtered out during fetch?  The page will still have navigator.serviceWorker.controller set even if the network requests are not intercepted, right?

**Comment by jungkees** [comment]
A register attempt for a file:// url will return a network error from Fetch (in [basic fetch](https://fetch.spec.whatwg.org/#concept-basic-fetch) algorithm) which makes the navigator.serviceWorker.register(url) promise reject. So basically the script in file:// scheme cannot be installed.

**Comment by wanderview** [comment]
The spec says "For now, unfortunate as it is, file and ftp URLs are left as an exercise for the reader."  I don't know about blink, but gecko has done this exercise and supports network requests to file:// URLs.

I think rejecting with a NetworkError is not as nice as rejecting with a SecurityError for file://.

Anyway, I think at least a note needs to be here for intent.

**Comment by jungkees** [comment]
Sure. I'm still between adding a note and adding an explicit step.

**Comment by wanderview** [comment]
Thanks!

**Comment by wanderview** [comment]
Oh, I guess I would prefer an explicit step.  Particularly since fetch spec may grow support for file:// in the future, etc.  Its easier to just be explicit here than chase changes in the other specs.  In my opinion, anyway.

Thanks again.

**Comment by jungkees** [comment]
Agreed. One thing is the existing APIs throw/reject a TypeError as it sees it comes from a wrong parameter usage. For consistency, I plan to make `ServiceWorkerContainer.register(url, options)` (i.e. in the method steps before calling the Register) reject with a TypeError for both scriptURL and scopeURL that have non-http/https scheme. Does it work for you?

**Comment by wanderview** [comment]
TypeError sounds reasonable.  Thanks.
