### ISSUE TITLE
CacheStorage.has() should not reject to indicate there is no such cache with cacheName

### ISSUE THREAD

**Issue by delapuente** [slightlyoff/ServiceWorker#781]
Rejection in promises should be an error path but upon the question _has the cache storage a cache named `cacheName`_, possible values are both `true` or `false` so, IMHO, the promise should resolve with _exists_, a boolean value set to `true` if the cache exists or `false` elsewhere.

**Comment by wanderview** [comment]
This is already how the spec is written.  My quick test suggests both chrome and Firefox resolve false in this case.

Are you trying this in an http:// window?  Cache API requires HTTPS.

**Comment by delapuente** [comment]
Sorry. I was fooled by the MDN. Indeed, I'll change it there.
