### ISSUE TITLE
ServiceWorkerRegistration.update() is unclear when uninstalling flag set

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#784]
Step 2 of update() says:

> If registration's uninstalling flag is set, abort these steps.

Clearly the intention is to stop immediately.  This is a promise-returning function, though.  I assume we want to reject the promise here.

What error should we reject with?  InvalidStateError?  TypeError?

**Comment by jungkees** [comment]
This has long been in my TODO list since the return type was changed. Thanks for reminding!
