### ISSUE TITLE
pending fetch events may be dispatched to exiting worker

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#785]
In Handle Fetch we have:

```
14. Let activeWorker be registration's active worker.
15. If activeWorker's set of event types to handle does not contain fetch, return null.
16. If activeWorker's state is activating, then:
    1. Wait for activeWorker's state to become activated.
```

So we can get a queue of pending fetch events waiting for the active worker to finish activating.  Ok, good.

But in the Activate algorithm we have:

```
17. Run the Update State algorithm passing registration's active worker and activated
      as the arguments.
18. Pop the top element from activation queue.
```

Popping the element from activation queue can immediately cause the Activate algorithm to start over with the next worker in the activation queue.  This can make the original activate worker the exiting worker.

In this case it seems the queued fetch events get fired on the exiting worker.  I guess Activate says to wait for the exiting worker to finish processing events, but it is this the behavior we want?

Should the fetch events keep waiting until we have a stable activated worker?  Essentially an activated worker and an empty activation queue?

**Comment by wanderview** [comment]
Note, what is in the spec is certainly easier to implement.  Also, the condition I suggest above is probably a bit of a corner case.  It requires a window to be open doing a skipWaiting() while another navigation is occurring.

I guess the current spec behavior is ok in that condition.  I'd just like confirmation this is intentional and what chrome implements.

Thanks!

**Comment by mattto** [comment]
Chrome behavior is a bit wrong here: it immediately terminates an exiting worker instead of waiting for it to finish processing events. If we do get in a situation where we dispatch a fetch event and then immediately the next worker calls skipWaiting(), it looks like we'd forcibly kill the worker in the middle of onfetch().

We have a TODO to actually wait.

**Comment by jungkees** [comment]
Yeah, a client normally lives its whole life with a particular active worker. `.skipWaiting()` is the only API that breaks this behavior. Can I close this?

**Comment by wanderview** [comment]
Sounds good.

**Comment by mattto** [comment]
Just a nit: `claim()` can also change the active worker. A client could be controlled by the registration with scope `/a/b/` and then change to be controlled by the registration with scope `/a/b/c` if that reg's worker called `claim()`.

**Comment by jungkees** [comment]
Right. Thanks for the clarification!
