### ISSUE TITLE
How are non-secure context Clients observable?

### ISSUE THREAD

**Issue by ehsan** [slightlyoff/ServiceWorker#791]
As far as I can tell from reading the spec, a `Client` representing a non-secure context cannot be observed.  `Clients.matchAll()` when used with `includeUncontrolled: true` already excludes non-secure `Client`s.  And `Clients.get()` also excludes non-secure `Client`s (and it's impossible to observe such a `clientId` in the first place since we don't dispatch `FetchEvent`s for such clients anyways).

Does this mean that implementations are free to ignore the places in the spec where we're talking about `Client` objects being non-secure?

**Comment by jungkees** [comment]
> As far as I can tell from reading the spec, a Client representing a non-secure context cannot be observed.

Yes, that's the intention. Here's the summary how the APIs deal with the non-secure contexts: https://github.com/slightlyoff/ServiceWorker/issues/754#issuecomment-147584203.

> Does this mean that implementations are free to ignore the places in the spec where we're talking about Client objects being non-secure?

I'm not clear with this. Is there any such place in the spec I'm missing?

**Comment by jdm** [comment]
@jungkees Look for the phrase "not a secure context" in the spec.

**Comment by jungkees** [comment]
`clients.get(id)`, `clients.matchAll()`, `clients.claim()` can still deal with the non-secure context clients, e.g., the iframes running on the same origin with the service worker but embedded in an http top frame. Those clients should be filtered out, and the above APIs are exactly where that happens.

Re client's id, fetch events for a non-secure client is also filtered out in Handle Fetch, but a non-secure client's id can still be exposed if we don't filter it out in `matchAll()`, etc.

**Comment by jungkees** [comment]
Closing. Please let me know if more discussion is needed.

**Comment by ehsan** [comment]
My point was mostly about `Clients.get()`.  Per spec, there is no way to obtain a clientId belonging to a non-secure context.  `Clients.matchAll()` and `Clients.claim()` don't work for non-secure clients, and we will never dispatch a `FetchEvent` for a non-secure non-subresource load, so the behavior of `Clinets.get()` would be the same whether or not the check for the secure context exists in the spec.
