### ISSUE TITLE
The prose for Clients.matchAll() distinguishes an omitted dictionary type argument

### ISSUE THREAD

**Issue by ehsan** [slightlyoff/ServiceWorker#792]
According to the [WebIDL spec](http://heycam.github.io/webidl/#idl-operations), an optional argument with a dictionary type should always be considered to have a default value:

> If the type of an argument is a dictionary type or a union type that has a dictionary type as one of its flattened member types, and that dictionary type and its ancestors have no required members, and the argument is either the final argument or is followed only by optional arguments, then the argument MUST be specified as optional. Such arguments are always considered to have a default value of an empty dictionary, unless otherwise specified.

Section 4.3.2 step 1.2 of `Clients.matchAll()` currently specifies a different behavior for when the argument is omitted, which probably needs to be changed accordingly:

> If the optional argument options is omitted, then:

**Comment by ehsan** [comment]
Implementor's feedback:  In Gecko, our binding machinery doesn't even expose whether the dictionary type argument was passed in or not.  I'm going to implement as if the step 1.2 of section 4.3.2 and everything under it was deleted.

**Comment by jungkees** [comment]
Thanks!
