### ISSUE TITLE
Editorial: Reword normative uses of "can"

### ISSUE THREAD

**Issue by inexorabletash** [slightlyoff/ServiceWorker#795]
In appendix B there is normative text reading:

> An HTTP request to fetch a service worker's script resource can include the following header:

> An HTTP response to a service worker's script resource request can include the following header:

Those should follow RFC2119 and be phrased as MUST or SHOULD or MAY,

**Comment by jungkees** [comment]
Thanks!

**Comment by annevk** [comment]
Hmm, shouldn't that be described in the algorithm responsible for the fetch?

**Comment by mkruisselbrink** [comment]
It was already described in the algorithm for those fetches. And the original "can include" text was just confusing in that it didn't make it clear at all that the Service-Worker header is always included for those requests.

**Comment by annevk** [comment]
It seems "can include" should then say "will include". You shouldn't make normative requirements twice.
