### ISSUE TITLE
Implement API to reject PUSH_PROMISEs sent by the server over HTTP/2

### ISSUE THREAD

**Issue by mariusGundersen** [slightlyoff/ServiceWorker#796]
[HTTP/2](http://http2.github.io/http2-spec/index.html) has support for the server pushing content to the client before the client requests it. This is specified as the server sending a [PUSH_PROMISE](http://http2.github.io/http2-spec/index.html#PUSH_PROMISE) to the client with (at least) the `method` and `url` to the resource. The server can then start sending the response to the client before the client has requested it. 

The spec does not specify how long the server should wait until it starts sending the response, so it can send it right away or it can choose to wait for a little while. If, while waiting, the server receives a [RST_STREAM](http://http2.github.io/http2-spec/index.html#RST_STREAM) message from the client on the (stream of the) resource, then the server should [interpret that as the client having rejected the content](http://http2.github.io/http2-spec/index.html#StreamStatesFigure). This can be done for example if the client already has the content in it's cache, and therefore doesn't need it. 

It would be useful if this could be handled by the ServiceWorker, since the ServiceWorker has a cache. The ServiceWorker could have a `pushPromise` event with the url as part of the event object, and a `reject` method that sends the `RST_STREAM` to the server. This could then be used to check if the url is in the ServiceWorkers cache, for example:

```js
this.oninstalled = function(){
  caches.set('myCache', new Cache());
}

this.addEventListener('pushPromise', function(event){
  //if the request url is in the cache,
  //then we don't need the server to send it to us,
  //so we reject it
  caches.match('myCache', event.request.url).then(event.reject);
});
```

**Comment by annevk** [comment]
I think we want a more generic API and not require service workers to be able to deal with H2 push. https://github.com/whatwg/fetch/issues/51 has some discussion and ideas, but not much progress yet.

**Comment by jungkees** [comment]
Tagging it Future ideas in favor of https://github.com/whatwg/fetch/issues/51 until we see some concrete proposal.

**Comment by jakearchibald** [comment]
Closing for now, can reopen if it comes back to us
