### ISSUE TITLE
Can we add some options to ClientQueryOptions?

### ISSUE THREAD

**Issue by romandev** [slightlyoff/ServiceWorker#801]
Hi all,

I'm Jinho Bang and Blink contributor. (I'm interested in service worker.)

Can we add some options to ClientQueryOptions?

For example, if there is a FrameType option in ClientQueryOptions, we can simplify the following code.

Before:
```
// Imagine that we have to do something to client if frameType == 'nested'.
clients.matchAll().then(function(client_list) {
  client_list.forEach(function(client) {
    if (client.frameType == 'nested')
      // do something
  });
});
```

After:
```
// If we have FrameType option,
clients.matchAll({ frameType : 'nested' }).then(function(client_list) {
  // do something
});
```

We will add other options such as id, url and other things.

Also, we can add clients.match() method as well. (I think)

```
clients.match({ frameType : 'nested' }).then(function(client) {
  // do something to first nested client.
});
```

I think it's simpler and more convenient.

What do you think?

/cc @jungkees, @jakearchibald, @nhiroki

**Comment by domenic** [comment]
IMO we should not be pursuing such sugary conveniences at this stage, and leaving them to service worker libraries such as sw-toolbox.

**Comment by jakearchibald** [comment]
Agreed, we should look to add things like this based on real world usage.

**Comment by jungkees** [comment]
Agreed. Thanks for the suggestion though @romandev.

Closing.
