### ISSUE TITLE
Should soft update algorithm be run when handling any kind of functional event?

### ISSUE THREAD

**Issue by delapuente** [slightlyoff/ServiceWorker#802]
Use case: I want to update a web application without navigating to it.

Instead os using sync or push and launch custom installation / activation steps, it could be easier if a soft update would happen after handling the functional event so the SW could be automatically updated retriggering install and activate events.

**Comment by jungkees** [comment]
[Handle Functional Event](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#handle-functional-event-algorithm) (step 8) does so. It invokes Soft Update if the last update check was more than 24 hours ago.

**Comment by delapuente** [comment]
I was looking at http://www.w3.org/TR/service-workers/#handle-functional-event-algorithm
Thank you!
