### ISSUE TITLE
Can create caches in the persistent storage?

### ISSUE THREAD

**Issue by delapuente** [slightlyoff/ServiceWorker#803]
AFAIK, caches can be evicted under storage pressure so they are temporary storage. I'm not sure the UA should evict the content in the offline caches without the user explicit consent. Could we add an extension to the spec to require some offline caches to be considered as persistent storage?

Use case: I want my favourite game always available. If there is storage pressure, I want to decide which content I want to remove and which not.

**Comment by jungkees** [comment]
SW cache is a persistent storage. Unless explicitly deleted by the API, the resources will persist. Detecting and handling a storage pressure is supposed to be handled by `beforeevicted` and `evicted` events defined in Quota Management API: https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#storage-considerations.

**Comment by delapuente** [comment]
According to http://www.w3.org/TR/quota-api/#widl-ServiceWorkerGlobalScope-onbeforeevicted

>  If the service worker that received this event did not give back enough space the UA may evict its content entirely. 

So it does not seems to match with the requirement ot be persistent storage. Or am I missing something?

**Comment by wanderview** [comment]
The idea is to use the storage spec to request persistence:

  https://storage.spec.whatwg.org/

We don't implement this in gecko yet, but I thought I saw some blink intent emails for this API.

There is still debate about whether to do something like the `beforeevicted` event or provide a storage API for controlling eviction.  In gecko we strongly prefer something through the storage API and not an event like `beforeevicted`.

**Comment by jungkees** [comment]
So we may defer to what the Storage API provides and the decision between that and `beforeevicted`.

**Comment by jakearchibald** [comment]
I don't think there's any action for us here, it's all in-progress in the storage spec.
