### ISSUE TITLE
Create F2F agenda

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#806]
I'll convert this to a wiki page once we have something more concrete, but an issue seems easier for discussion.

Things I'd like to cover (in priority order)

* Outstanding V1 issues, as we did in Sapporo, but hopefully won't take as long
* Cache API enhancements (since we're likely to have @wanderview around), especially transactions & making `addAll` more useful
* Foreign fetch
* Navigation handling (how to launch as-homescreen from `openWindow` & native apps, and how to manage "single" vs "multi" window sessions)

## Agenda

* V1 issues (see below)
* [Cache transactions & saving `cache.addAll`](https://github.com/slightlyoff/ServiceWorker/issues/823)
* [Foreign fetch](https://github.com/slightlyoff/ServiceWorker/pull/751)
* [A header-based installation](https://github.com/slightlyoff/ServiceWorker/issues/685)
* Who's hosting the next meeting & when?

## V1 Issues need discussion

* ~~https://github.com/slightlyoff/ServiceWorker/issues/814~~
* https://github.com/slightlyoff/ServiceWorker/issues/813
* ~~https://github.com/slightlyoff/ServiceWorker/issues/808~~
* https://github.com/slightlyoff/ServiceWorker/issues/800
* ~~https://github.com/slightlyoff/ServiceWorker/issues/788~~
* https://github.com/slightlyoff/ServiceWorker/issues/787
* https://github.com/slightlyoff/ServiceWorker/issues/783
* https://github.com/slightlyoff/ServiceWorker/issues/771
* https://github.com/slightlyoff/ServiceWorker/issues/757
* https://github.com/slightlyoff/ServiceWorker/issues/737
* https://github.com/slightlyoff/ServiceWorker/issues/728
* https://github.com/slightlyoff/ServiceWorker/issues/718
* ~~https://github.com/slightlyoff/ServiceWorker/issues/704~~
* https://github.com/slightlyoff/ServiceWorker/issues/703
* https://github.com/slightlyoff/ServiceWorker/issues/699
* https://github.com/slightlyoff/ServiceWorker/issues/688
* https://github.com/slightlyoff/ServiceWorker/issues/677
* Issues deferring to [SecureContext] IDL proposal (https://github.com/heycam/webidl/pull/65)
  * https://github.com/slightlyoff/ServiceWorker/issues/769
  * https://github.com/slightlyoff/ServiceWorker/issues/754
  * https://github.com/slightlyoff/ServiceWorker/issues/687

## Attendees:

* Ali Alabbas (Microsoft)
* Jake Archibald (Google)
* Ilya Grigorik (Google)
* Conrad Irwin
* Anne van Kesteren (Mozilla)
* Marijn Kruisselbrink (Google)
* Jatinder Mann (Microsoft)
* Edward O'Connor (Apple) - unconfirmed
* Alex Russell (Google)
* Jungkee Song (Samsung)
* Kinuko Yasuda (Google)

We'll also post updates to #serviceworker on freenode, for anyone wanting to follow along remotely.

**Comment by annevk** [comment]
Perhaps @jungkees could round up the v1 issues he thinks need discussing so we can have a go at the simpler ones now.

**Comment by jakearchibald** [comment]
I'm up for that. Eat our greens ahead of the meeting so we can concentrate on the fun stuff. I'll also put together a rough proposal for the cache API stuff, so we're starting from somewhere.

**Comment by wanderview** [comment]
I would like to review the recent changes to the lifecycle job queue stuff.  In particular, I'd like to walk through some test cases and get agreement on what should actually happen.  I'll try to send the list of tests in advance so people can look at them.

**Comment by wanderview** [comment]
Also, I'd like to make sure we answer the base URI question in #787.

**Comment by jungkees** [comment]
> Perhaps @jungkees could round up the v1 issues he thinks need discussing so we can have a go at the simpler ones now.

Alright. Good idea. I'll do so although most of the remaining V1 issues here seem not trivial.

**Comment by jungkees** [comment]
I added "V1 Issues need discussion" in the OP. Those are basically the issues that I don't have any concrete answer yet. I may add a few more but other issues not listed are just in my TODO.

Hope we can tackle as many issues as we can here so we can spend more time on non-V1 issues this time.

**Comment by wanderview** [comment]
Might be a low priority at this point, but there are some questions about allowing some mixed content in #813.

**Comment by mattto** [comment]
> I added "V1 Issues need discussion" in the OP. 

Where is this list?

**Comment by jungkees** [comment]
I noticed the list that I added in the OP has gone. I'll add it again with some more updates.

**Comment by jungkees** [comment]
I updated the OP with the list of V1 issues to discuss. Some of them may be easy ones that one can answer. If so, please give comments.

@annevk, here are two more issues that I want to discuss with you: 
* https://github.com/slightlyoff/ServiceWorker/issues/811
  * A common definition for the _client_ concept seems needed for sw and fetch
  * Fetch may need a target client internal slot on a request? (for a navigation)
* https://github.com/slightlyoff/ServiceWorker/issues/672 (Algorithm review for the part)
