### ISSUE TITLE
Service worker state on system restart

### ISSUE THREAD

**Issue by r-nathan** [slightlyoff/ServiceWorker#812]
Can we retain the cache even after quitting the browser completely and accessing the application?

The scenario: I access the application and then cache all the static files with service worker. Till I don't quit the application (or chrome running in background), since the service worker thread is running, service worker is serving files from cache. If I quit the completely and restart the service worker when offline, it is not able to provide files from cache.

**Comment by jakearchibald** [comment]
The cache is already retained across browser restarts, this is how things like https://jakearchibald.github.io/svgomg/ work offline.

If you're using Chrome, Check out the resources panel in Chrome's devtools to see what's in the cache API.
