### ISSUE TITLE
should subresource FetchEvents trigger an update if 24-hours since last check?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#814]
Currently the spec indicates we should trigger a soft update in these conditions:

1) After a non-subresource FetchEvent is handle regardless of last check time.  This is done in Handle Fetch.
2) After a functional event is handled if its been more than 24 hours since last check time.  This is done in Handle Functional Event.

FetchEvents extend ExtendableEvent like other functional events.

Should subresource FetchEvents be treated like other ExtendableEvents with the 24-hour-checked update?  It seems like they should.

**Comment by jakearchibald** [comment]
Are you suggesting the SW shouldn't update after each navigate? If so, I disagree. If I shipped a SW that served broken pages, users would be stuck with it for 24 hours? We added the 24hr max-age limit because the longer the max-age, the more trouble you're getting yourself into.

If you're saying that we should perform an update after a fetch event if it's >24hr since an update, even if the fetch is for a subresource, then yeah, that makes sense.

**Comment by wanderview** [comment]
>  If you're saying that we should perform an update after a fetch event if it's >24hr since an update, even if the fetch is for a subresource, then yeah, that makes sense.

Yea, this one.  All FetchEvents might trigger an update.  Navigations bypass the 24-hour check for starting the update (although http cache might still be in effect), while sub-resources only actually start the update if its >24 hours.

**Comment by mattto** [comment]
Sounds good. How about postMessage, should that also trigger 24-hour-checked update? (Chrome does a 24-hour-checked Soft Update whenever the worker stops or has been running for a while, which I guess falls more into "The user agent may call this as often as it likes to check for updates." than the Handle Functional Event algorithm.)

**Comment by jungkees** [comment]
Alright. So we agree to invoking Soft Update for a subresource request when it's >24hr since an update. I'll add it.

> How about postMessage, should that also trigger 24-hour-checked update?

I don't think a message event is a functional event. Devs already have `registration.update()` if they want to trigger update at certain point.

**Comment by jungkees** [comment]
Addressed: 1413c06cc42156f58d06d6de2ca077f369169883
