### ISSUE TITLE
FetchEvent's constructor's second argument must be optional

### ISSUE THREAD

**Issue by ehsan** [slightlyoff/ServiceWorker#815]
This is the convention for defining new Events.  Both Chrome and Firefox implement this correctly.

**Comment by domenic** [comment]
I think the consensus was for EventInitDicts with required members, the eventInit argument should not be optional.

**Comment by jungkees** [comment]
That's right. It was decided that `FetchEventInit.request` is required. I plan to address this change in Chrome via https://codereview.chromium.org/1435633002.

**Comment by ehsan** [comment]
That'd make sense!

**Comment by ehsan** [comment]
Argh, except that I cannot reopen!

**Comment by ehsan** [comment]
(And the spec is incorrect anyways, please reopen!)

**Comment by domenic** [comment]
No, you misunderstood. The second argument is required, when it is a dictionary that contains required members. Which is the case for FetchEvent.

**Comment by ehsan** [comment]
Oh you're right, I misread your original comment!

I modified Gecko accordingly.  Thanks!
