### ISSUE TITLE
Browser Cache and ServiceWorker

### ISSUE THREAD

**Issue by andreapernici** [slightlyoff/ServiceWorker#824]
I've implemented ServiceWorker cache on one of my website combined with expire headers for static resources so JS included.

Now I have a strange behaviour. It looks impossible to invalidate the cache on the user browser.

It is related to the ServiceWorker or to the Long Lasting expire headers.

Using CTRL+F5 works only on the first refresh. If I reopen the page it looks like the previous version.

Can you address to some documentation on cache invalidation?

**Comment by petkaantonov** [comment]
ServiceWorker isn't for traditional caching exactly but for making your app work offline. For offline case you need to version your service worker with your assets like in this tutorial http://www.html5rocks.com/en/tutorials/service-worker/introduction/. 

Then when your app updates, you just bump the version which forces a service worker update and a new install. In the new install you add new assets to the cache keyed with the new version identifier and remove old caches that are based on key that is older than the current version identifier.

There is probably a full featured offline app service worker tutorial somewhere but I forgot where.

**Comment by petkaantonov** [comment]
Also, for development I'd have an `if` inside the worker to not do any caching while in development.

**Comment by jakearchibald** [comment]
Cache control is provided by https://fetch.spec.whatwg.org/#requestcache, but hasn't been implemented by Chrome yet.

However, if you find yourself cache-busting here, it's often the sign that you should just fix your cache headers.
