### ISSUE TITLE
clarify Request.isReload for sub-resources

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#827]
Current the spec text for .isReload is a bit vague.  Step 18.4 of Handle Fetch says:

> Let the isReload attribute of e be initialized to true if request's client is a window client and the event was dispatched with the user's intention for the page reload, and false otherwise.

Obviously a lot of hand waving in "user's intention" here.

Both chrome and firefox only set this for the top level navigation that is triggered from a refresh.  All sub-resources get .isReload=false.

Over in this chrome issue devs are asking that to change:

  https://code.google.com/p/chromium/issues/detail?id=579866

But its unclear to me what this means for subresources.  I see some possibilities:

1) All sub-resources loaded synchronously during reload get .isReload = true
2) Sub-resources loaded sync and async before load event get .isReload = true
3) Sub-resources from a reloaded document always get .isReload = true even if they are async requested an hour later, etc.

I think (1) or (2) make the most sense for developers.  Thoughts?

**Comment by mitar** [comment]
I agree, 1) or 2) would be great. My main view here is that user reload the whole page, not just the HTML content. So they would expect that the all resources on that page (can) react to the reload (in a special way).

**Comment by jakearchibald** [comment]
Closing this as we're dropping `isReload` https://github.com/slightlyoff/ServiceWorker/issues/873
