### ISSUE TITLE
"javascript global environment" and related terms were removed from HTML

### ISSUE THREAD

**Issue by mkruisselbrink** [slightlyoff/ServiceWorker#832]
whatwg/html@cf0355d7e0e229b98f7fbd51b8c7608010c787f5 removed definitions of "document environment", "worker environment" and "javascript global environment", which this spec still links to.

@domenic Not sure what best to replace them with (but maybe fixing #831 is partly related to this?)

**Comment by domenic** [comment]
Let's see...

> A service worker client is an environment settings object that specifies various settings for its JavaScript global environment.

This can just be "A service worker client is a type of environment settings object".

> In the newly created execution environment, create a JavaScript global environment whose global object is workerGlobalScope. (The JavaScript global environment whose global object is a ServiceWorkerGlobalScope object is defined as the service worker environment, which is a type of worker environments.)

Yeah, this is related to #831 and the updates described therein.

> Multiple separate objects implementing the ServiceWorker interface across document environments and worker environments can all be associated with the same service worker simultaneously.

> [several more like this]

These could just be "documents and workers", without even linking anywhere.

> Else, let it be initialized to a new Client object that represents globalObject's worker environment.

Not really sure what "represents" is supposed to mean here, so unclear what this should be changed to.

> (The JavaScript global environment whose global object is a ServiceWorkerGlobalScope object is defined as the service worker environment, which is a type of worker environments.)

This can just be deleted.
