### ISSUE TITLE
Fetch API respondWith's implicit RETURN

### ISSUE THREAD

**Issue by RichardMaher** [slightlyoff/ServiceWorker#844]
I have looked at https://www.w3.org/TR/service-workers/#respond-with-method trying to establish the architected  behaviour of respondWith() and I cannot find anything regarding an implicit RETURN.

Can anyone here please clarify this and the behaviour of the respondWith-entered and wait-to-respond flags?

**Comment by jdm** [comment]
That's an old version of the specification. Does https://slightlyoff.github.io/ServiceWorker/spec/service_worker/ clarify anything for you?

**Comment by jungkees** [comment]
Thanks for the pointer. Please refer to that version. And here's some explanation to the question:

The steps in `respondWith(r)` are synchronized with the steps in [Handle Fetch](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/index.html#on-fetch-request-algorithm) where this event's listener was invoked.

respond-with entered flag is being checked in Handle Fetch step 18.6.3, and if not set, the original request goes to the network. wait-to-respond flag is used to synchronize those steps such that Handle Fetch can wait until the promise given to respondWith settles.

**Comment by RichardMaher** [comment]
My mistake. Looks like an implementation bug (Chrome) rather than the spec:-

	function reply(result){
		console.log("In reply", replied);
		if (replied) return;
		console.log("After reply", replied);
		
		replied = true;
		event.respondWith(result);
		console.log("Replied : ", replied);
	}

If I stick "replied = true" after the respondWith call then the PC never gets there. It's like the SP gets set to caller - 1 rather than caller. Anyway, I'll check with the Chrome people.

BTW Are any of those flags (fetchEvent.repondedTo would be useful) exposed? bodyUsed is good for request/response but event state could be good? Having said that I'm still not comfortable doing a FETCH in a FETCH event and not expecting recursion but I'm a beginner at the FETCH API.

And what happened to FetchEvent.ClientId?

**Comment by jakearchibald** [comment]
> If I stick "replied = true" after the respondWith call then the PC never gets there. It's like the SP gets set to caller - 1 rather than caller.

I don't know what PC and SP stand for here. Your code example looks like it's relying on global state (where is `replied` coming from?), if it is, that's likely your source of bugs.

> BTW Are any of those flags (fetchEvent.repondedTo would be useful) exposed?

Out of curiosity, what would you use it for?

> Having said that I'm still not comfortable doing a FETCH in a FETCH event and not expecting recursion but I'm a beginner at the FETCH API.

Fetches within a service worker do not trigger fetch events within the same service worker.

**Comment by RichardMaher** [comment]
Sorry registers Program Counter (PC) and Stack Pointer (SP) betray my age and are pretty useless in OO interpretive programming but it was a metaphor.

Here's the code:


'use strict';

console.log("Started", self);

function optimusConor(event)
{			
	console.log(Date(), 'Handling fetch event for', event.request.url);

	const	MAXDETENT	= 300,
			NOCACHE		= {cache : "no-cache"},
			WORKCACHE   = "FAC$CACHE";
			
	var 	timerId		= 0,
			replied     = false;
			
	function reply(result){
		console.log("In reply", replied);
		if (replied) return;
		console.log("After reply", replied);
		
		replied = true;
		event.respondWith(result);
		console.log("Replied : ", replied);
	}

	function wait(ms){
		return new Promise(
			function(resolve){
				timerId = setTimeout(function(){resolve()}, ms);
			});
	}

	var inBuff =
        new Promise(
			function(resolve,reject){				
				caches.match(event.request.clone())
					.then(response => response === undefined ? reject() : resolve(response));
			}
		).catch(()=>{});

	event.waitUntil(new Promise(
		function(allDone){
			console.log("in promise");
					
			fetch(event.request.clone(), NOCACHE)
				.then(response =>
					{
						console.log('Response from network is:', response);
						if (response.ok) {
							clearTimeout(timerId);
							console.log("Storing cache");
							reply(response);
							caches.open(WORKCACHE).then(cache => {
								cache.put(event.request, response.clone());
							})
						}
						allDone();
					})
				.catch(function(error) {
						console.log('Fetching failed:', error);
						allDone();
						inBuff.then(response => reply(response))
							.catch(() => {console.log("Error3 is: ", error)});
					  })
			;

			wait(MAXDETENT).then(inBuff.then(response => reply(response)));
			
		}));
}

self.addEventListener('install', function(event) {
  self.skipWaiting();
  console.log('Installed', event);
});

self.addEventListener('activate', function(event) {
  self.addEventListener('fetch', optimusConor);
  console.log('Activated', event);
});

**Comment by jakearchibald** [comment]
@RichardMaher Service workers spin up to call event listener callbacks. Once the event has been handled, the SW may terminate. You're adding a fetch listener in your 'activate' event, but once the service worker terminates that listener is gone, as it isn't reattached when the SW next runs.

All service worker events should be attached in the initial execution of the worker.

**Comment by RichardMaher** [comment]
Not sure what you mean here have you run it?

1) The FETCH event listener gets called (for a IMG fetch from a different tab)
2) The event optimusConor has not been completely handled
3) The atomic code is wrapped in an event.waitUntil

and most importantly . . .

My reply function does get called several times (check your console) but the respondWith acts like a 

RespondWith(); + RETURN;

Is that clear?

**Comment by jakearchibald** [comment]
There's a few things wrong with your code that will cause it to fail or behave unreliably:

```js
self.addEventListener('activate', function(event) {
  self.addEventListener('fetch', optimusConor);
  console.log('Activated', event);
});
```

You shouldn't add event listeners inside other event listeners. Once the service worker is terminated (which happens after a period of not being used, or when the browser shuts down) your fetch listener is gone, because next time the SW runs the activate event isn't fired.

Also, if you want to intercept a fetch request, you must call `event.respondWith` within the event callback.

Check out the [offline cookbook](https://jakearchibald.com/2014/offline-cookbook/), there's also a [Udacity course](https://www.udacity.com/course/offline-web-applications--ud899) which guides you through taking an online-only web app to full offline-first.

This is also an excellent article https://ponyfoo.com/articles/serviceworker-revolution

**Comment by RichardMaher** [comment]
> You shouldn't add event listeners inside other event listeners. Once the service worker is terminated (which happens after a period of not being used, or when the browser shuts down) your fetch listener is gone, because next time the SW runs the activate event isn't fired.

Good tip! I'll make the change and keep that in mind. Fetch->Idle and Terminated->Idle  -  gotcha.

Please indulge me that the latent bug has not manifested in the test case as yet.

> Also, if you want to intercept a fetch request, you must call event.respondWith within the event callback.

I thought I was. Could you please define/scope ***"within the event callback"***? In-line?

**Comment by jakearchibald** [comment]
By "within the callback" I mean it's called before the callback returns. Does this explain it? http://jsbin.com/wowevi/edit?js,console

**Comment by RichardMaher** [comment]
Outrageous! Or as we speak a common language, that is absolute bollocks!

Please show me where that little chestnut is in the spec please?

**Comment by jakearchibald** [comment]
https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#on-fetch-request-algorithm 18.6.3

This flag is set after dispatch (18.5), so if it isn't called by then, it's ignored.

**Comment by jakearchibald** [comment]
Also see the dispatch flag in step 5 https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#fetch-event-respondwith-method

**Comment by wanderview** [comment]
Should we just make `self.addEventListener()` throw outside top level script execution?  I feel like we've discussed that before.  I think we do that for importScripts() for similar footgun reasons.

**Comment by jakearchibald** [comment]
I'm in favour of that. We already show a console warning apparently https://bugs.chromium.org/p/chromium/issues/detail?id=401870

**Comment by jakearchibald** [comment]
…but it doesn't appear to be working https://bugs.chromium.org/p/chromium/issues/detail?id=594160

**Comment by RichardMaher** [comment]
Sorry, I've one child throwing up all night and another going to rowing in 25 mins so not 100% on the latest, but back on the "before the callback returns" (Jake's example http://jsbin.com/wowevi/edit?js,console )

If I can use a promise like this: -

function wait(ms) {
  return new Promise(resolve => {
    setTimeout(resolve, ms);
  });
}

Then surely: - wait(22).then(console.log(***'this is not called within the callback'***) ?

You bypassed promises with their logical in-lining and went to back to straight Events so I just want to clear up if your "within the callback" context is effected?

> This flag is set after dispatch (18.5), so if it isn't called by then, it's ignored.

Wow, thanks for the reference and I stand corrected. (.20 seemed to be definitive)

So later today I'll : -

1) New-up a new promise immediately in the FetchEvent
2) Call fetchEvent.respondWith(myNewPromise)
3) In my reply function, instead of calling respondWith I'll call myPromise.resolve()

Would that be kosher now? Is my use of the waitUntil appropriate or is the repondWithEntered flag now achieving the same thing for me?

**Comment by inexorabletash** [comment]
> 1) New-up a new promise immediately in the FetchEvent
> 2) Call fetchEvent.respondWith(myNewPromise)
> 3) In my reply function, instead of calling respondWith I'll call myPromise.resolve()

Bingo - that's indeed the pattern you want. (Well, not literally `myPromise.resolve()` of course...)

(Good luck with the sick offspring!)

**Comment by RichardMaher** [comment]
Thanks Joshua, I'm going for this: -

`
        var		ioResolve, ioReject;

	var		pong		= 
			new Promise(function(res, rej){
							ioResolve = res;
							ioReject  = rej;
						});

	event.respondWith(pong);
	console.log("After respondWith()");

    function reply(result){
        console.log("In reply", replied, result);
        if (replied) return;
		
		ioResolve.call(null, result);
        console.log("After reply", replied);

        replied = true;
    }
`

I'm debugging in it now but I've had to go back to my Promises 101 notes because this is driving me nuts: -

`    var inBuff =
        new Promise(
            function(resolve,reject){               
                caches.match(event.request.clone())
                      .then(response => {
						  console.log("*"+response+"*");
						  if (response == undefined) console.log("yes sir");
                          reject(new Error("Not Found"));						  
					  })
            }
        ).catch((error)=>{console.log("nomatch" + error)});
` 

Even though there's no match in the cache and all the correct logging occurs and reject() has been called, later, when I try inBuff.then() the THEN happens rather than the ELSE. The debugger says inBuff is in state "resolved" with an undefined value. I'll sort it out.

BTW. Kids are good, thanks for asking. Linda Blair's head stopped spinning and the boy only had one dry reach after the first race and that was through effort.

**Comment by jakearchibald** [comment]
@RichardMaher I've tried to clean up the formatting in your code, hope I didn't lose any of the intent.

I'm not sure where `replied` comes from in your first example, and it doesn't look like `reply` is ever called. What's the intent?

**Comment by RichardMaher** [comment]
Hi Jake, If you scroll up to the "Here's the code" example (and thanks for tidying up) you'll see that REPLIED is a boolean that was there to prevent respondWith() being called more than once. REPLY is called by each thread when it decides it has a response contender.

This logic is redundant now that I've had to move to a Promise (probably better anyway). That is, the Promise is settled once and forever so the late comers can knock themselves out without any exceptions thrown.

Now if I can just apply that Promise logic to why inBuff ends up resolved after it's REJECT has been called then I'll be done.

**Comment by jakearchibald** [comment]
`inBuf` always resolves because it has a catch handler right at the end which doesn't re-throw.

I'm still not clear on the intent of the code. Can you tell me what the goal is? Eg "I want all requests with URLs that end `.jpg` to come from the cache, and all other requests to go to the network" - I know that's not *your* goal, but can you describe your goal in that form?

**Comment by RichardMaher** [comment]
Jake, in a nutshell it does what it says on the tin "Best Endeavour". I haven't put any request filtering logic in yet but I was impressed was someone else's idea of trying for a network fetch but if it took longer than Xms then respond with a cached copy (if available).

As a training exercise (Promises, Fetch API) I decided to code a solution that would start 3 "threads" in motion per fetch: -

1) Check cache for a hit and retrieve it
2) Fetch from network Request URL, if error go to cache-hit
3) Start off a timer that if gets in first will respond with a cache-hit

It is also makes sure to update the cache even after the request has been responded to with a cache-hit. So, to me, the cache should be as up to date as possible.

Personally I'm more interested in seeing what I can achieve with Google Map tiles and KML caching but I needed training and that's where I'm up to. Below is the code: -

FWIW, I have to admit to being ambivalent about where this language is going :-( You were right about the CATCH forcing a resolve but for the life of me WHY? The reject() method was called the answer is settled-rejected not some rubbish "Oh he didn't let the 'exception?' bubble up so maybe he really meant RESOLVE'. Is there an ELSE on the way?  Why are you mandating an ELSE when we don't care?

And at the risk of over-sharing with people who wouldn't know me if I stood up in their corn flakes, the vomiting has turned into a lumbar punch, cat scan, chest-x-ray, 2 intravenous antibiotic drips and a saline drip and more blood tests than I can count :-( Money's on meningitis but we have to wait. As a rule don't jump into still water after a Perth summer unless you hold your nose.

	'use strict';

	function optimusConor(event)
	{           
		const   MAXDETENT   = 300,
				NOCACHE     = {cache : "no-cache"},
				WORKCACHE   = "FAC$CACHE"
				;

		var     timerId     = 0;
		var		ioResolve   , 
				ioReject
				;

		var		pong		= 
				new Promise(function(res, rej){
								ioResolve = res;
								ioReject  = rej;
							});

		event.respondWith(pong);

		function wait(ms){
			return new Promise(
				function(resolve){
					timerId = setTimeout(function(){resolve()}, ms);
				});
		}

		var inBuff =
			new Promise(
				function(resolve, reject){  
					caches.match(event.request.clone())
						  .then(response => response === undefined ? reject() : resolve(response));
				});

		event.waitUntil(new Promise(
			function(allDone){
				fetch(event.request.clone(), NOCACHE)
					.then(response =>
						{
							if (response.ok) {
								clearTimeout(timerId);
								ioResolve.call(null, response.clone());
								caches.open(WORKCACHE).then(cache => {
									cache.put(event.request.clone(), response);
								})
							}
							allDone();
						})
					.catch(function(error) {
							allDone();
							inBuff.then(response => ioResolve.call(null, response))
								.catch(()=>{ioReject.call(null, error)});
						  })
				;

				wait(MAXDETENT)
					.then(inBuff
							.then(response => ioResolve.call(null, response))
							.catch(()=>{})
						);
		   }));
	}

	self.addEventListener('install', function(event) {
	  self.skipWaiting();
	  console.log('Installed', event);
	});

	self.addEventListener('activate', function(event) {
	  console.log('Activated', event);
	});

	self.addEventListener('fetch', optimusConor);

**Comment by jakearchibald** [comment]
> 1) Check cache for a hit and retrieve it
> 2) Fetch from network Request URL, if error go to cache-hit
> 3) Start off a timer that if gets in first will respond with a cache-hit
>
> It is also makes sure to update the cache even after the request has been responded to with a cache-hit. So, to me, the cache should be as up to date as possible.

I think this achieves what you're trying to do:

```js
self.addEventListener('fetch', event => {
  const cacheResponsePromise = caches.match(event.request);
  const networkFetchPromise = fetch(event.request);

  // # Populating the cache from the network
  // WARNING: by adding all responses into the cache like this, you'll run out
  // of space pretty quickly, you should restrict the URLs you do this for, or clean
  // the cache at some points
  event.waitUntil(
    networkFetchPromise.then(response => {
      // clone the response, because we're going to use it twice
      const responseClone = response.clone();
      
      return caches.open('my-cache-name').then(cache => {
        return cache.put(event.request, responseClone);
      });
    })
  );

  // # Responding to the request
  event.respondWith(
    // race the network and a timeout
    Promise.race([
      networkFetchPromise,
      new Promise((_, reject) => {
        setTimeout(() => reject(Error('Timeout')), 2000);
      })
      // if this times out or rejects, try the cache…
    ]).catch(() => cacheResponsePromise).then(response => {
      // if the cache has no match, defer to the network (without a timeout)
      // Note: you didn't say you wanted this, but it seems to make sense,
      // a slow network response is better than no response.
      return response || networkFetchPromise;
    })
  );
});
```

> You were right about the CATCH forcing a resolve but for the life of me WHY?

A promise is a async representation of try/catch, and this is how try/catch works. See http://jsbin.com/vuhawa/edit?js,console - the function returns undefined rather than throwing, because the error has been caught by a catch clause.

The same thing happens with promises: 

```js
const a = Promise.reject(Error('Broken'));
const b = a.catch(() => "Hello");
```

`a` rejects with an error, but `b` resolves with `"Hello"`.

> Money's on meningitis

Ooof, here's hoping for a speedy recovery.

**Comment by RichardMaher** [comment]
At first glance the level of parallelism appears to be a distinguishing factor in the two strategies, as does the time-to-respond for a cache-hit. But I'll look more tomorrow.

Cheers

**Comment by jakearchibald** [comment]
Everything's parallel in my example. The network fetch and the cache lookup happen at the same time.

> as does the time-to-respond for a cache-hit.

You suggested only going to the cache if the network request failed or timed out. Did I misunderstand?

**Comment by RichardMaher** [comment]
Sorry, the waitUntil threw me semantically. It looks good, but don't you want to go to cache even if the networkFetchPromise was thenable but respons.ok was false?

**Comment by jakearchibald** [comment]
> don't you want to go to cache even if the networkFetchPromise was thenable but respons.ok was false?

Sure thing. Probably want to avoid those going into the cache too…

```js
self.addEventListener('fetch', event => {
  const cacheResponsePromise = caches.match(event.request);
  const networkFetchPromise = fetch(event.request);

  // # Populating the cache from the network
  // WARNING: by adding all responses into the cache like this, you'll run out
  // of space pretty quickly, you should restrict the URLs you do this for, or clean
  // the cache at some points
  event.waitUntil(
    networkFetchPromise.then(response => {
      // If the response wasn't ok, we're not interested
      if (!response.ok) return;
      // clone the response, because we're going to use it twice
      const responseClone = response.clone();

      return caches.open('my-cache-name')
        .then(cache => cache.put(event.request, responseClone));
    })
  );

  // # Responding to the request
  event.respondWith(
    // race the network and a timeout
    Promise.race([
      networkFetchPromise,
      new Promise((_, reject) => {
        setTimeout(() => reject(Error('Timeout')), 2000);
      })
    ]).then(response => {
      // Prefer the cache if the response is not ok
      if (!response.ok) throw Error('Not ok');
      return response;
      // if this times out or rejects, see if the cache came up with anything…
    }).catch(() => cacheResponsePromise).then(response => {
      // if the cache has no match, defer to the network (without a timeout)
      // Note: you didn't say you wanted this, but it seems to make sense,
      // a slow network response is better than no response.
      return response || networkFetchPromise;
    })
  );
});
```

> is the network-hit response delayed until after you've updated the cache?

It works the same as this http://jsbin.com/lidoda/edit?js,console. The first attached `then` executes first, but async actions within a `then` handler don't block other handlers on the same promise. I'm relying on the ordering for the response cloning.

> doesn't event.request have to be cloned in there somewhere?

It is, see `const responseClone = response.clone()`.

Although we're using a timeout, this approach still suffers from being online-first. A better approach is offline-first https://jakearchibald.com/2014/offline-cookbook/#cache-then-network
