### ISSUE TITLE
HTML5's Offline-first Council of Trent

### ISSUE THREAD

**Issue by RichardMaher** [slightlyoff/ServiceWorker#845]
I was going to post this as a reply to https://github.com/slightlyoff/ServiceWorker/issues/844 but it is a far greater and more of an all-encompassing issue than a single thread can serve.

We (all HTML5 Web-App developers) desperately need a schism from the heretical forces of "Offline First" and the Spartan, austere, featureless world, of minimalism!

If you want to hamstring yourselves and live a primitive pre-telecommunications lifestyle, or something more akin to life after a Road-Warrior Apocalypse, then good for you; just stop white-anting people who wish to take full advantage of modern technology! 

For most "cashed-up"  consumers, Lack of Connectivity is the exception an NOT the norm. (And I live in the most isolated capital city in the world so cop that!) Sure we'll failback gracefully but we WILL NOT target the bean-tins-and-string deployment option.

Your Client-Based GeoFences are a joke :-( You willingness, nay preference, to serve up stale, outdated data, is an exercise in self-flagellation that only a fellow sicko could understand.

But let us wicked technologists not sway you from your life-was-meant-to-be-hard, God-would've-given-us-wings fanaticism. All we want is a fair share of the Chrome, Mozilla, Opera, and Safari development budgets for expanding the Feature List rather than censoring it.

**Comment by jakearchibald** [comment]
I replied on public-webapps
