### ISSUE TITLE
"Wait for all the tasks queued by Update State" language is problematic

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#848]
The end of the "Install" algorithm contains this step:

> 21) Wait for all the tasks queued by Update State invoked in this algorithm have executed. 

Note that "Update State" says this about the tasks:

> The task must use serviceWorker’s service worker client’s responsible event loop and the DOM manipulation task source.

So these tasks may be running on different threads from the "Install" algorithm itself.

Implementing the "Wait for all the tasks" language in step 21 is essentially saying to block the main thread until, for example, a task queued against a worker thread has fired.  I don't think we want to do this.

The reason this was added was to ensure that state change events fire before we start activating the worker.

I propose that instead of the "wait for all tasks" language we instead just make Activate run asynchronously.  If we "queue a task to run the Activate algorithm" then it should begin activating after any same-thread state change events have fired.

We may need to make Activate a job type, though, to avoid having the async Activate race with other jobs.

**Comment by wanderview** [comment]
So, I've thought about this some more and changed my mind.

I forgot that our "wait" language in the spec means an async wait.  So its not really blocking the main thread.

Also, we really should have consistent state change events even on workers.  So we really do need to wait for these.

I now wonder if we should have more "wait for state change events to fire" steps in the lifecycle steps.  For example, whenever we change the registration .installing, .waiting, and .active we may want to ensure all state change events have been flushed to content first.

**Comment by wanderview** [comment]
See https://github.com/slightlyoff/ServiceWorker/issues/851#issuecomment-199324636 for why we might want to wait for statechange events in more places.  Basically the current spec will provide a consistent state view for DOM objects in windows, but workers will see inconsistent state.

**Comment by jakearchibald** [comment]
F2F: queue a task to update these values per context.

In the `updatefound` listener, `reg.installing` should always be the new worker.

In the `statechange` listener, the registration should be updated.

**Comment by wanderview** [comment]
This will be covered by gecko bug https://bugzilla.mozilla.org/show_bug.cgi?id=1257977
