### ISSUE TITLE
FetchEvent.respondWith does something weird with the body of a response

### ISSUE THREAD

**Issue by mkruisselbrink** [slightlyoff/ServiceWorker#850]
In the algorithm describing respondWith the following steps exist:

1. Set the _potential response_ to _response_’s associated response.
2. If _response_’s body is non-null, run these substeps:
  1. Let dummyStream be an empty ReadableStream object.
  2. Set _response_’s body to a new body whose stream is dummyStream.
  3. Let reader be the result of getting a reader from dummyStream.
  4. Read all bytes from dummyStream with reader.

I think this is incorrect, although I'm not entirely sure what it is trying to do.

What it seems to say it is doing is assigning a new body to response's body (not sure how that is possible, _response_'s body is defined as being the body of _response_'s associated response. There doesn't seem to be a way to change the body of just the `Response` object while leaving the body of the underlying response alone). It then goes and reads all the bytes from this newly created empty body.

I'm guessing the intended effect is to leave the javascript `Response` object with a disturbed body, which happens to be an empty stream, while leaving the underlying response alone. But the fetch spec doesn't allow decoupling the body of the `Response` object from the body of the associated response, so what is written doesn't actually work.

**Comment by yutakahirano** [comment]
cc: @jungkees, the author of https://github.com/slightlyoff/ServiceWorker/commit/ccff1f16d376ced3ef0544df9a942bbf6fc49494.

I guess the description is from the bottom of https://fetch.spec.whatwg.org/#dom-request. That works because Request is not exposing `body` property, but it's not true for Response.

**Comment by jungkees** [comment]
Basically, I wanted to avoid cloning the body not to require additional memory space. I still want to find a way. Do the following steps make sense?

response: a Response object (resolved from a promise) passed to respondWith(r)

1. Let newResponse be a copy of response’s associated response, except for its body.
1. If response’s body is non-null, run these substeps:
  1. Set newResponse's body to response's body.
  1. Let dummyStream be an empty ReadableStream object.
  1. Set response’s body to a new body whose stream is dummyStream.
  1. Let reader be the result of getting a reader from dummyStream.
  1. Read all bytes from dummyStream with reader.
1. Set the potential response to newResponse.

`response.body` from the script surface seems okay since by the time `responseWith(r)` returns r's body should be disturbed already.

Or, set the newResponse's body to the result of extracting the package data out of response's body's stream will do?

**Comment by annevk** [comment]
If you want to clone a response, use the algorithms provided in Fetch.

If we take a step back and look at how this maps to JavaScript, I think `respondWith()` is pretty much required to "structured clone" and message that clone to the environment making the fetch. What exactly "structured clone" means here is not really defined and what it means for streaming is even less understood. (And of course, user agents might not have to "structured clone" and be able to share memory more efficiently if developers avoid poking the painful bits, but we don't have to define the fast paths in the specification, just encourage them.)

**Comment by wanderview** [comment]
I'm confused.  (As usual.)  Why do we need to clone at all?  Can't respondWith() just be spec'd to read the stream from the response per normal?  It seems this should leave the stream disturbed/locked just as if javascript had read the stream.

**Comment by annevk** [comment]
How do you get the bytes read across realms (and the `Response` object itself), from a JavaScript perspective?

**Comment by yutakahirano** [comment]
My understanding is our plan is to use pipe. Something like this.

1. Let _response2_ be a response copied from _response_ except for its body.
1. If _response_'s body is non-null:
 1. Let {_rs_, _ws_} be an identical transform stream.
 1. Call pipeTo on _response_'s body's stream with _ws_.
 1. Set _response2_'s body to a new body with _rs_, _response_'s body's transmitted bytes and _response_'s body's total bytes.
1. Set the potential response to _response2_.

**Comment by wanderview** [comment]
From an implementation perspective we effectively serialize the Response into a C++ representation.  That may or may not become another Response object depending on what initiated the request.

So I guess in spec language I would say you need to create a new internal response (lower case r) with a pipe for a body.  Then the original body stream is .pipeTo()'d the new response's body.  (Which I think what @yutakahirano just posted.)

**Comment by annevk** [comment]
Yeah, that sounds reasonable. (And would indeed map to some kind of structured clone operation in an all-JavaScript-world.)

**Comment by wanderview** [comment]
> Yeah, that sounds reasonable. (And would indeed map to some kind of structured clone operation in an all-JavaScript-world.)

Except that "cloning" implies that the original object is still usable.  This is consuming the original object.  Maybe I'm splitting hairs, but I think its an important distinction and differs from what structured cloning normally does AFAIK.

**Comment by jungkees** [comment]
[pipeTo](https://streams.spec.whatwg.org/#rs-pipe-to) says the method is still in some flux. So, I just temporarily changed the steps to https://github.com/slightlyoff/ServiceWorker/issues/850#issuecomment-197705711 with leaving an issue note to use https://github.com/slightlyoff/ServiceWorker/issues/850#issuecomment-197893295 when it's ready.

Also, it'll be great if you can make the pipeTo an extracted algorithm so other algorithms can directly invoke. (/cc @yutakahirano, @domenic)

**Comment by annevk** [comment]
@wanderview "structured cloning" has a concept of transfering and detaching the original object, sure, and that happens for body, but e.g., `Headers` is still fully functional (and therefore cloned).

**Comment by jakearchibald** [comment]
Pre F2F notes: I think this is just spec work remaining.

**Comment by jungkees** [comment]
F2F: @yutakahirano  is working on https://github.com/slightlyoff/ServiceWorker/pull/934. I think the PR will resolve this issue.

**Comment by jungkees** [comment]
I'll backport https://github.com/slightlyoff/ServiceWorker/pull/934/commits/6c2b3f18c5aad509635bd81f4931132c26514bb6 to V1.
