### ISSUE TITLE
Unregister algorithm step 6.1 is no longer necessary

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#855]
Step 6.1 of the Unregister algorithm is:

> If registration’s uninstalling flag is unset, invoke Finish Job with job and abort these steps. 

I don't think this can ever be true now, though.  The uninstalling flag is now cleared in the Register algorithm which executes within a job.  Since we have a single job queue the flag cannot be cleared until the Unregister job completes.

**Comment by jakearchibald** [comment]
Pre F2F notes: Confirm this. Seems right.
