### ISSUE TITLE
if service-worker-allowed header changes should active worker be potentially unregistered?

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#857]
Consider the case where we have an existing service worker installed and active at `/app/sw.js`.

An update is then triggered which downloads the `/app/sw.js` again, but now the server has started serving a `Service-Worker-Allowed: disableallserviceworkers` header.  This value is a bit arbitrary such that it won't match any valid scope.

The Update algorithm will now start rejecting with a SecurityError, but the current existing service worker is still installed.

Should the installed service worker be unregistered if the Service-Worker-Allowed header changes such that its script is no longer valid?  Or should we allow a unique string to be recognized there to force an uninstall?

Sorry if there is already an issue on this.  I seem to recall that a "kill switch" has been discussed in the past.

**Comment by mattto** [comment]
There was some back and forth in #604 . Eventually we settled on not unregistering. That was partly to be consistent with other HTTP response changes like MIME type becoming invalid or response code becoming 4**, which don't unregister.

I think there's still interest in a easier kill switch than skipWaiting() + unregister(). That's tracked at #614

**Comment by wanderview** [comment]
Is there a potentially bad situation here:

1) Service worker script installed that offline's all pages for the site as cache-first.
2) Site disables service workers with Service-Worker-Allowed because of some problem.
3) Active installed script can now not be removed because updates always fail due to the header.

I guess maybe the answer is "just don't do that", but it seems to make the header less useful.  It seems you have to avoid the header block so you can ship your "uninstall uourseflf " SW update.

Anyway, I'll read that other issue in the morning.  Sorry if I'm retreading old ground.

**Comment by delapuente** [comment]
We came up with a similar situation while developing our WordPress suite for progressivizing blogs. It turned out we are generating the service worker [by collaboration](https://github.com/mozilla/wp-sw-manager/#usage). As one plugin is enabled, it adds its contents to the worker but what happen when all are disabled is a little bit surprising. The dynamic sw is no more generated but [the service worker does not get unregistered](https://github.com/mozilla/wp-sw-manager/issues/2).

The solution is to check the response from the sw itself and let the sw to unregister itself. Maybe the solution is similar for this case.

**Comment by jakearchibald** [comment]
The best thing to do in this case is to serve a service worker that unregisters itself. We should discuss the kill switch at the f2f.

**Comment by slightlyoff** [comment]
Clear Site Data is the kill-switch of choice; @mkwst is developing it here: https://w3c.github.io/webappsec-clear-site-data/

**Comment by jakearchibald** [comment]
F2F: https://github.com/slightlyoff/ServiceWorker/issues/877 reporting URL

**Comment by mattto** [comment]
To clarify, the F2F decision was to *not* unregister due to the service-worker-allowed header.
