### ISSUE TITLE
`caches.match` search order

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#862]
`caches.match` currently searches for files in insertion order. This behaviour makes it impossible to search for the latest files in the entire Cache Storage. For example:
```
Promise.all([
  caches.open('v0.1.0').then(cache => cache.put('/a/b.txt',new Response('1'))),
  caches.open('v0.1.2').then(cache => cache.put('/a/b.txt',new Response('2')))
]).then(() => {
  caches.match('/a/b.txt').then(response => {
    response.text().then(text => console.log(text)); //1, it should be 2 instead.
  });
});
```

**Comment by wanderview** [comment]
Does this do what you need?

```
caches.keys().then(function(cacheList) {
  return caches.open(cacheList[cacheList.length - 1]);
}).then(function(cache) {
  return cache.match('/a/b.txt');
});
```

**Comment by jakearchibald** [comment]
It isn't impossible, as `caches.matchAll` will give you them.

The current behaviour is ideal for updates.

1. V1 is running, taking cached assets from cache named "static-v1"
2. V2 installs, adding updated content to "static-v1", and becomes waiting
3. Page controlled by V1 requests "/"
4. V1 `respondWith(caches.match(event.request))`

Without the current behaviour, step 4 may result in V1 receiving V2's assets.

**Comment by tresdin** [comment]
@wanderview It's not a good idea since there are files which are only available in the older one. You're gonna need more code in this case.

@jakearchibald 
> step 4 may result in V1 receiving V2's assets.

Shouldn't it be the expected behaviour? If developers are afraid of breaking the page, then why don't they use `Cache.match` instead? This behaviour makes `caches.match` much less useful, indeed.

I might be wrong about the "impossible" part. But I think it will be more useful if we reverve the search order. It's would be fine with another flag in the second argument in the worst case.

**Comment by jakearchibald** [comment]
> Shouldn't it be the expected behaviour?

No, it would break sites if V1 starts getting V2's assets. If I explicitly wanted this behaviour, I could delete the old cache, but I've never wanted that behaviour.

> If developers are afraid of breaking the page, then why don't they use Cache.match instead?

You could also do that to get the latest version.

If you really want a reverse cache search, here it is:

```js
function reverseCacheSearch(request) {
  return caches.keys().then(cacheNames => {
    return cacheNames.reverse().reduce((chain, cacheName) => {
      return chain.then(response => {
        return response || cache.open(cacheName).then(c => c.match(request));
      })
    }, Promise.resolve())
  })
}
```

In most cases, you may even get away with:

```js
caches.matchAll(request).then(r => r && r[r.length-1]);
```

**Comment by tresdin** [comment]
I'm now ok with `matchAll` though. Thanks for the clarification @jakearchibald
