### ISSUE TITLE
Provide a convenience method to run code outside event handler

### ISSUE THREAD

**Issue by AshleyScirra** [slightlyoff/ServiceWorker#866]
If you want to do something like respond to a fetch event ASAP, but kick off some background work like an update check, you don't have a direct way to do that without running code outside a SW event handler (which appears to be disallowed).

I think the workaround is to post a message to a client, which then posts back, and then you do the work in the message handler. This seems unnecessarily bureaucratic and is quite a problem if there isn't actually a client available (particularly noting that there does not appear to be a client available in the "navigate" fetch request).

So why not provide something like a `self.run(promise)` method that provides a way for a SW to run more code without risking it being terminated?

**Comment by jakearchibald** [comment]
Isn't this `fetchEvent.waitUntil`?

**Comment by AshleyScirra** [comment]
No, because you may want to respond to the fetch event immediately, then kick off some long-running process in the background. If you put the long-running process in `waitUntil`, then the fetch request will be unnecessarily delayed until the long-running process completes.

**Comment by jakearchibald** [comment]
Promises passed to `fetchEvent.waitUntil` don't delay response delivery.

**Comment by AshleyScirra** [comment]
Oh - so you can use both `respondWidth` and `waitUntil` together in parallel? I didn't realise that.

**Comment by wanderview** [comment]
> Oh - so you can use both respondWidth and waitUntil together in parallel? I didn't realise that.

You can.  This is how I do it for my blog:

  https://github.com/wanderview/wanderview.github.com/blob/master/sw.js#L97

It appears, though, there might be an issue with `FetchEvent.waitUntil` in chrome at the moment:

  https://bugs.chromium.org/p/chromium/issues/detail?id=601095

Also note that currently you have to call `waitUntil` synchronously in the event handler, although the spec has changed to allow it to be called asynchronously any time up until the `respondWith` promise settles.  I don't think FF or chrome implement that yet.  It will make using `FetchEvent.waitUntil` much easier to use once we loosen that restriction.

**Comment by jakearchibald** [comment]
@AshleyScirra I also do it in the example I sent earlier https://github.com/jakearchibald/sw-cache-update-example/blob/master/with-separate-list/sw.js#L89

**Comment by jakearchibald** [comment]
Closing this, as `waitUntil` is already there, and https://github.com/slightlyoff/ServiceWorker/issues/771 will make it easier to use.
