### ISSUE TITLE
Where are ServiceWorker data stored?

### ISSUE THREAD

**Issue by wklm** [slightlyoff/ServiceWorker#883]
Hey, 
I'm playing with ServiceWorker api for quite a while, but cannot figure out, where are the cached files stored on my hard drive and if they're accessible from outside of browser context. Any tips highly appreciated! Here's also a link to SO, if you'd like to earn some points :) http://stackoverflow.com/questions/36597140/where-are-serviceworker-data-stored

Cheers, Wojtek

**Comment by wanderview** [comment]
This is completely dependent on the browser implementation and may change over time.  In Firefox it's something like:

  <profile dir>/storage/default/<origin>/cache

You really should not touch these files externally, though.  All bets are off on the browser working if you do. (Please don't.)

**Comment by wanderview** [comment]
That path was supposed to be:

  [Profile dir]/storage/default/[origin]/cache

**Comment by wklm** [comment]
hi @wanderview thanks for your answer. I'm just curious if that files are stored in clear text, so if they are readable outside of browser.

**Comment by wanderview** [comment]
They're not really in plaintext.  Various files are in sqlite or compressed format.  We don't normally encrypt profile data, though.  If an attacker has access to the file system then all bets are off.  They can modify the firefox executable itself.

Again, the format of these files may change at any time.
