### ISSUE TITLE
clarify that Clients.matchAll() only returns Window Client objects with active documents

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#888]
The `Clients.matchAll()` spec depends on their being an active document in the browsing context in a couple steps, but isn't really clear what to do if there is no active document.  I think we should be more explicit these windows are excluded from the list.

Related: https://github.com/whatwg/html/issues/1073

**Comment by annevk** [comment]
Just active or fully active?

**Comment by jakearchibald** [comment]
Pre F2F notes: seems like just a spec wording issue.

**Comment by jakearchibald** [comment]
F2F: What Ben says. So bf cache pages & unloaded tabs shouldn't appear in this list.
