### ISSUE TITLE
caches.match() rejection on missing name is a footgun

### ISSUE THREAD

**Issue by wanderview** [slightlyoff/ServiceWorker#891]
Currently we offer `caches.match()` as a shorthand for looking for a request in all the Cache objects.  An optional name can be passed to look in a specific Cache object.  Currently, if that named Cache does not exist we reject `caches.match()`.

I've seen this trip up a few people now.  It seems most people expect `caches.match(url, { name: 'foo' })` to be a shorthand for:

```
caches.open('foo').then(function(cache) {
  return cache.match(url);
});
```

But what we actually implement is:

```
caches.has('foo').then(function(result) {
  if (!result) {
    return Promise.reject(NotFoundErr);
  }
  return caches.open('foo');
}).then(function(cache) {
  return cache.match(url);
});
```

Since `cache.match()` does not normally reject its very surprising to people that `caches.match()` can reject.  Its also the kind of thing that can work in many cases, but then start rejecting when your CacheStorage state changes.

I'd like to propose we just resolve `undefined` if the named cache is not present.

**Comment by inexorabletash** [comment]
Just to confirm, resolve `undefined` but not implicitly create the cache (i.e. still smarter than the shorthand) ?

**Comment by wanderview** [comment]
Either way would work for me.  Not creating the cache object seems good.

**Comment by jakearchibald** [comment]
Agreed

**Comment by NekR** [comment]
Just (for some time actually) shoot my foot with it.

**Comment by wanderview** [comment]
Gecko bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1271069

**Comment by inexorabletash** [comment]
Blink bug: https://bugs.chromium.org/p/chromium/issues/detail?id=610349
