### ISSUE TITLE
Why are so many things [Unforgeable]?

### ISSUE THREAD

**Issue by domenic** [slightlyoff/ServiceWorker#897]
It's very un-idiomatic for the web. [Unforgeable] should be used very rarely; `window.location` is one of the few legit uses.

What was the motivation behind this? Could it be removed? Or, could the motivation be documented, if it's a good one?

**Comment by jungkees** [comment]
When I used [Unforgeable] for them, I thought them should be non-configurable as they even don't have a ctor but just capture the internal states.

```js
navigator.serviceWorker.getRegistration().then(registration => {
  Object.defineProperty(registration, 'active', { value: registration.installing });
});
```

I'm not sure whether changing the value of those make sense. If so and that happens with other features often, I can remove them.

**Comment by annevk** [comment]
It's normal you can do that with other features, yes. Note that [Unforgeable] also makes properties own properties, rather than live on the prototype, which is also a little weird.

**Comment by jungkees** [comment]
> Note that [Unforgeable] also makes properties own properties, rather than live on the prototype, which is also a little weird.

@domenic @annevk do you have any concern about this? `registration.installing/.waiting/.active` and `navigator.serviceWorker.controller` are all the attributes that use [Unforgeable]. That is, `ServiceWorkerContainer` and `ServiceWorkerRegistration` have them as there own properties. Will they have any negative effects in working on libraries or something?

**Comment by annevk** [comment]
I just don't see the point. We have `[Unforgeable]` to explain certain legacy bits, that's it. @heycam, maybe rename `[Unforgeable]` to `[LegacyUnforgeable]`?

**Comment by domenic** [comment]
> Will they have any negative effects in working on libraries or something?

It is generally unexpected, and means that usual techniques libraries use for interfacing with platform objects will fail. That is necessary for legacy cases like Location, but shouldn't be necessary for new features like service workers.

**Comment by jungkees** [comment]
Understood. I'll remove them.
