### ISSUE TITLE
why cant i register a embedded function as for shared worker?

### ISSUE THREAD

**Issue by publicocean0** [slightlyoff/ServiceWorker#902]
why cant i register a embedded function as for shared worker?

**Comment by jakearchibald** [comment]
What's an embedded function?

**Comment by wanderview** [comment]
A data: URL containing a script?

**Comment by publicocean0** [comment]
yes exactly ... as i can do with shared worker :) it would be easy to write
all in a page ... not putting js file in the path of html pages

2016-05-23 18:57 GMT+02:00 Ben Kelly <notifications@github.com>:

**Comment by wanderview** [comment]
If you registered a bad data: URL script, how would the browser check for updates to get a fixed one installed?

**Comment by publicocean0** [comment]
If you register a bad url , you cam remove manually or programatically. For updates you can verify a new script using md5 of blob function for example. It is trial.

**Comment by asutherland** [comment]
It seems like this would enable persistent XSS attacks.  Being able to execute code once in the origin allows you to control everything that happens in the future on the origin.  In contrast, by requiring a URL, you need to be able to host code on the origin which is a significantly higher bar and requires some intent on the part of the origin.  This is especially relevant in a world where many sites may load third-party JS like ad scripts or analytics.

**Comment by jakearchibald** [comment]
Yeah this is exactly why we made this restriction.

**Comment by publicocean0** [comment]
If you are able to execute a XSS attack in a domain , you can execute code non only inside the worker. It seams a tautology. The body is a function , if you can modify a function you can modify also the remaining scripts on the page.

**Comment by asutherland** [comment]
The point is that Service Workers are:
1. Cached.
2. Able to modify all future network requests issued by the origin in question, including: future JS loads, stripping requests by the site to register its own service worker, or just redirecting all traffic to the attacker's own site, etc.

It is indeed a problem in the first case if an attacker is able to execute JS in an origin they should not be able to.  But what you're requesting allows the attack to perpetuate itself after the original intrusion mechanism may have been fixed.  In my previous comment I used the term XSS as a shorthand for cases that are not strictly XSS; the attacker could also compromise JS hosted on third-party domains.

It's a reality of the web and net that:
- Sites will have security flaws that allow XSS attacks, despite new technologies like CSP that make it easier to prevent them.
- Sites will get hacked.
- Dangerous functionality implemented in standards for the benefit of a few reduces the security of all.
- Complicating standards and thereby implementations to make potentially dangerous things safer for niche use-cases also reduces the security of all.

In any event, it's not clear what your actual use-case is.  What is it you are trying to do that needs service worker functionality but cannot host a single JS file?  Your use-case may actually want something more "app" like as offered by browser extensions/add-ons.

**Comment by publicocean0** [comment]
The solutions are generated by men, not by HTML. If you introduce intelligent FORM field purging , you solve really the problem evoiding to introduce a thousands to tricks that dont solve the problem, but just limiting. 
Service worker is with HTM5, you introduce also what i told above and all solved. It is useless if you limiting service worker if the remaining of page is attacked. It is just a tautology. You have to solve the cause not the conseguences. 

I know that service worker is a critical point, but all is based if xss is prevented or not. If it is not prevented a hacker will found a trick for evoiding your tricks anyway.
