### ISSUE TITLE
what is the best way to save Request while offline ?

### ISSUE THREAD

**Issue by Jxck** [slightlyoff/ServiceWorker#904]
if I wanna send data to sever from page, but wanna also support offline using background sync.

```js
// sending body 'a=b' to server
self.addEventListener('fetch', (e) => {
  let req = e.request;
  // delegate to background sync
  self.addEventListener('sync', (e) => {
    fetch(req).then(/*....*/)
  });
  e.respondTo(new Response('dummy'));
});
```

but in this case, `req` are at local memory, so this will remove when service worker process are down before sync event fired (in my understanding).

so I need to save `req` to somewhere.
but I don't have response, for saving this to caches.
(saving request with dummy response to caches seems bad hack.)

should I keep body in this request to indexed db ?
it seems heavy for me to initialise / saving / getting IDB for saving only **"a=b"**.

localStorage seems fit with this, 
it's handy to save body 'a=b' with some key and grab this when 'sync' event.
but I know that I can't touch it in sw because of sync api.

is there any other way to save body or request ?
or localStorage will have Async API (returning promise) are welcome !!

**Comment by wanderview** [comment]
Personally I think having a Cache object with "pending requests" and empty responses would be fine.  It won't let you store requests with methods other than GET or HEAD, though.  So if you need store a POST you must convert to IDB.

**Comment by Jxck** [comment]
> you must convert to IDB

thanks, but this `must` means, we don't have other way.

if I have Async localStorage, it better to use in this case I think.
or say same thing in other words,
if cache api is more general as kvs, it'll fits for this case.

for example

```
class AsyncStorage // async localStorage
class Cache extends AsyncStorage // which specialized for Request/Response
class LocalStorage // sync wrapper for AsyncStorage
```

how do you think about it ?

**Comment by Jxck** [comment]
move to #906

**Comment by delapuente** [comment]
@Jxck take a look at [Request Deferrer](https://serviceworke.rs/request-deferrer_service-worker_doc.html).
