### ISSUE TITLE
need AsyncLocalStorage (was #904)

### ISSUE THREAD

**Issue by Jxck** [slightlyoff/ServiceWorker#906]
localStorage is handy for much usecases, but unfortunately it's api based on Sync.
so in service worker we need to use Indexed DB for every kind of data, only if you need to store 1byte flag.

I think if we don't need index for large data search, and don't wanna preparing ceremony for storing data,
it's better to have a localStorage witch having Async API.

or other sight of view, Cache API is much handy than IDB, but it's specialised for Request/Response.
AsyncLocalStorage will looks something like CacheAPI witch is generalised for generic javascript object.
(we may say it as parent class of Cache API class)

this will solve may use case I think, for example..

- every use case for localStorage at window context
- saving request data for sync event (I described it at #904)
- saving simple/single/small data like flag, counter etc
- case for preparing scheme at install/activate are over kill

will seems..

localStorage with AsyncAPI (returning promise)

```js
asyncStorage.setItem('key', 'value').then();
asyncStorage.getItem('key').then(console.log.bind(console)); // 'value'
// etc
```

generalised cache api

```js
asyncStorage.open('v-1').then((store) => {
  store.put('key', {data:'value'}).then();
  store.match('key').then(console.log.bind(cosnole)); // { data: 'value' }
  // etc but, no add/addAll
});
```

**Comment by delapuente** [comment]
@Jxck despite the proposal for adding an async API to localStorage is good and IDB API sucks, you can use [localForage](https://github.com/mozilla/localForage).

**Comment by jakearchibald** [comment]
This isn't the right repo for this, but it might be worth proposing at the [WICG](https://discourse.wicg.io/).

In the mean time, little libs like https://github.com/jakearchibald/indexeddb-promised make IDB a lot easier. Includes async localstorage example.

**Comment by domenic** [comment]
FWIW, I've got a proposal for this that I think is pretty complete: https://domenic.github.io/async-local-storage/. Feel free to file issues on the tracker there, or chime in on existing discussions!

**Comment by Jxck** [comment]
@domenic :+1:
