### ISSUE TITLE
New Push API Capable of handling and/or matching Facebook Message and Apple iMessage 

### ISSUE THREAD

**Issue by RichardMaher** [slightlyoff/ServiceWorker#911]
Can we please *expand* the scope of the Push API and Web Push protocol so that it can even begin to compete with native apps? Make no mistake that Messaging is the killer app that could bury Web Apps once and for all. I absolutely weep as the HTML5 death knell is sounding while you're all off to Amsterdam for a Heineken jolly to wax bollocks on progressive web apps. There will be no Web Apps without messaging! 

You all must be so proud of your zealous preoccupation with "hostile" Push Service providers :-(

Apple's vote is in: -

Apple's changes to its iMessage system drew the biggest reaction at the conference. Developers will be able to incorporate apps into iMessage so users can do more tasks like make payments or order take-away. 

...

Apple is following the lead of Facebook chief executive officer Mark Zuckerberg, who sees messaging applications as the tools people will use to do everything from chatting with customer service representatives and getting sports updates to booking taxis or paying restaurant bills. This model has been popular for years in China, where Tencent's WeChat app is used by millions of consumers for banking,

Read more: http://www.smh.com.au/technology/technology-news/wwdc-2016-wrap-apples-siri-could-soon-hail-you-an-uber-20160613-gpibc6.html#ixzz4BVmq5Qdf 
Follow us: @smh on Twitter | sydneymorningherald on Facebook

**Comment by jakearchibald** [comment]
This is not the push repo. Final warning.
