### ISSUE TITLE
ServiceWorkerContainer spec lists `onerror` as an event handler

### ISSUE THREAD

**Issue by tony19** [slightlyoff/ServiceWorker#912]
I think the `ServiceWorkerContainer` spec should not list event handlers.

[*Service Workers 1*](https://slightlyoff.github.io/ServiceWorker/spec/service_worker_1/#service-worker-container-event-handlers) and [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer/onerror) list `onerror` as an attribute of `ServiceWorkerContainer`. My tests show that Chrome 51/53, Firefox 47, and Opera 38/39 do not actually support `navigator.serviceWorker.onerror`, contrary to the *Browser Compatibility* table in MDN; and that `onerror` is only available from within a service worker object.

I later discovered a [comment in #199] (https://github.com/slightlyoff/ServiceWorker/issues/104#issuecomment-39488270)  from @jakearchibald and a [comment in #198](https://github.com/slightlyoff/ServiceWorker/issues/198#issuecomment-39410922) from @kinu that indicate `onerror` was moved from the container, so I'm assuming the `ServiceWorkerContainer` spec just needs to be updated. Correct?

[StackOverflow ref](http://stackoverflow.com/a/37784386/6277151)

**Comment by wanderview** [comment]
I can't find any place we fire this error event in gecko.  Are we sure no other specs like push or background sync use it, though?

**Comment by amiq11** [comment]
FYI: Blink looks the same with gecko. onerror isn't defined at [the idl file](https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/serviceworkers/ServiceWorkerContainer.idl?sq=package:chromium&dr=CSs&l=41), and I couldn't find any log that onerror has been implemented.

**Comment by jakearchibald** [comment]
Pre F2F notes: Seems like this is a hangover from early API sketches. Probably should be removed. We should come up with a plan for error handling.

**Comment by jakearchibald** [comment]
F2F: We should remove this

**Comment by slightlyoff** [comment]
LGTM.
