### ISSUE TITLE
Service worker not working when tested on mobile using local ip.

### ISSUE THREAD

**Issue by sp1rs** [slightlyoff/ServiceWorker#914]
Service worker works fine, when test locally ( because it allows http://localhost ) , but if i have to test the same app on mobile using my computer IP, it pops up error in console saying undefined:1 Uncaught (in promise) DOMException: Only secure origins are allowed.
How to test that service worker works fine in mobile?

**Comment by jakearchibald** [comment]
Use devtools port forwarding https://developer.chrome.com/devtools/docs/remote-debugging
