### ISSUE TITLE
service worker not working for localhost

### ISSUE THREAD

**Issue by sp1rs** [slightlyoff/ServiceWorker#915]
When i used http://localhost , and put sw.js file in root directory it works fine. But if i put sw.js file in http://localhost/app_name/ then it says net::ERR_INSECURE_RESPONSE in console and undefined:1 Uncaught (in promise) DOMException: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/html').

**Comment by wanderview** [comment]
You have to serve your service worker script with a mimetype of text/javascript or similar.  Things like python -mSimpleHTTPServer should do this automatically for files ending in .js.

**Comment by sp1rs** [comment]
@wanderview the file at root directory, its mime type is text/plain, and the file in app/ is also of same mime type text/plain.

**Comment by delapuente** [comment]
What's the scope for your service worker? You can not register a sw in `/app_name` with scope `/`. The max scope for a worker is the worker location.

**Comment by delapuente** [comment]
(Well, actually you can but you need to set `Service-Worker-Allowed` header).

**Comment by sp1rs** [comment]
This is the structure of the code:
--- main_app
    -- app1
    --app2
        --static/js/main.js ( where i am registring my sw.js) ( register('/app2/sw.js',{ scope: '/app2/' })
        -- sw.js
but if i put sw.js in main dir, then it works fine.

**Comment by mattto** [comment]
The error message says sw.js is served with the MIME type text/html.  It must be served with  text/javascript or similar. It looks like your server is changing the MIME type based on the path.

(Also this GitHub repository is not a good place for this issue, since it's not a spec issue.)

**Comment by sp1rs** [comment]
Closing the issue, the problem was my route was not correctly configured in django app. ** Thanks for the help **

**Comment by delapuente** [comment]
I don't get the structure of your site. Is `app2` a folder? Is `sw.js` inside that folder?
