### ISSUE TITLE
Why doesn't cache.match support `cacheName`

### ISSUE THREAD

**Issue by remy** [slightlyoff/ServiceWorker#917]
Going by the [docs on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Cache/match) it reads regarding the `options.cacheName` to the `cache.match()` method:

> Note that this option is ignored by Cache.match

It seems odd that I can't filter the cache that I'm searching for the `.match()`, but I can filter when I use `.matchAll()`. Without the filtering, I have to open the specific cache, and then run the match against the specific cache.

Have I misunderstood or does it actually make sense to add the support to `.match()`?

**Comment by NekR** [comment]
`Cache.match()` runs `Cache.matchAll()` internally.
`Cache.matchAll()` uses `Query Cache` algorithm which doesn't use `CacheQueryOptions.cacheName` in it.

I don't know why you may want to filter by cache name inside **a cache**, plus, `Cache` doesn't know its name and doesn't have `name` property, so it's actually impossible at this moment.

I guess you just confused `Cache` and `CacheStorage`. The last uses `CacheQueryOptions.cacheName` to match in specified cache instead in all caches in the storage.

**Comment by wanderview** [comment]
Yea, the spec defines a single `CacheQueryOptions` that can be used with:

* `caches.match()`
* `cache.match()`
* `cache.matchAll()`
* `cache.delete()`
* `cache.keys()`

The `cacheName` field only applies to the `caches.match()` though because in all other cases you are calling the method on a specific cache object already.

Also note that `cacheName` was recently changed to simply return `undefined` if the cache object cannot be found.  Previously this threw a TypeError.  Right now there are probably browsers in the wild that do both, so you want to be careful with `cacheName`.

**Comment by remy** [comment]
Okay, so if I've understood the replies correctly, firstly the MDN docs are wrong, but in particular, **instead** of writing this:

```js
return caches.open('special-assets').then(cache => cache.match(request));
```

I can write this:

```js
return caches.match(request, { cacheName: 'special-assets' });
```

Is that right?

**Comment by NekR** [comment]
Yes, seems correct. But also add `.catch(...)` to the end of `caches.match(...)` because older versions of browsers reject that promise if cache doesn't exist (_new versions should just fulfill with `undefined`_). So it should be like this:

```js
return caches.match(request, { cacheName: 'special-assets' }).catch(function() {});
```

**Comment by wanderview** [comment]
I think the MDN docs are correct, if confusing.  If you are doing caches.match, then you want this page;

https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage/match

Where cacheName has an effect.

If you are using Cache.match (different object type from CacheStorage) then cacheName has no effect.

**Comment by jakearchibald** [comment]
Seems like this isn't an issue. Reopen if I'm wrong.
