### ISSUE TITLE
Stop monkeypatching event dispatch

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#924]
I thought I already filed an issue on this, but I could not find it. I noticed that the Install process monkey patches event dispatch acting as if it has some kind of control over how event listeners are invoked. That seems wrong and unlikely to be needed.

**Comment by jungkees** [comment]
Agreed. That monkey patching seems not needed. I'm looking at the related steps to get them more precise before removing the unnecessary text.
