### ISSUE TITLE
Should Cache-Control: private be respected?

### ISSUE THREAD

**Issue by RReverser** [slightlyoff/ServiceWorker#926]
Currently it looks like `Cache-Control: private` is being ignored by Cache API, while in HTTP it 

> Indicates that all or part of the response message is intended for a single user and MUST NOT be cached by a shared cache, such as a proxy server.

This behavior is probably more flexible, but on the other hand, it enables ability to accidentally (and very easily) cache resources which were meant to be private (user-specific) and not intended to be shared between various requests (or even stored on the disk in the first place).

Would it make sense to reject attempts to put such responses into the cache from security perspective?

**Comment by wanderview** [comment]
It does seem developers reason about service worker and Cache API like a "proxy server in the browser".  So this might be reasonable.

**Comment by annevk** [comment]
Hmmmm. We ignore most HTTP logic thus far. Importing some of it and not all seems rather brittle.

**Comment by jakearchibald** [comment]
We deliberately don't support other `Cache-Control` things like `max-age`, so I don't think we should support this.

If `inbox.json` contained emails for the logged in user, it's totally valid to want to cache this locally despite it being `Cache-Control: private`.

**Comment by wanderview** [comment]
Works for me.  I guess we can revisit it if its becomes "best practice" in the dev community to block cache-control:private via a library or something.

**Comment by RReverser** [comment]
Yeah, works for me, but mostly worried about lots of developers who might just include "caching service worker" code from popular samples and be unaware of potential risk for their clients - none of the cache SW examples / articles handled nor mentioned this, and folks tend to be used to HTTP cache behavior, so thought it might be worth at least clarifying.

**Comment by jakearchibald** [comment]
The "cache everything" examples bother me too. I somewhat warn against it at https://jakearchibald.com/2014/offline-cookbook/#on-network-response, but I probably should make it louder.
