### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by DavidScales** [slightlyoff/ServiceWorker#927]
In the [Getting started] section of explainer.md, when discussing service worker registration, the documentation states that *The scope is optional, and defaults to /*. My understanding is that the default scope of a service worker is the location of the service worker file? E.g. if the service worker is at **/my-app/sw.js**, then the scope will be **/my-app/**, unless specified otherwise. 

[Getting started]:<https://github.com/slightlyoff/ServiceWorker/blob/master/explainer.md#getting-started>

**Comment by jakearchibald** [comment]
Thanks!
