### ISSUE TITLE
Firing an event when service worker wakes up 

### ISSUE THREAD

**Issue by tresdin** [slightlyoff/ServiceWorker#928]
As far as I know, ServiceWorker will fall into *sleep state* when there is no other task to handle. That means all the data stored in memory will be wiped out at that time. I'm thinking about reinitializing that data every time ServiceWorker wakes up. May be something like this:
```
self.onwakeup = () => reinitializeInmemoryData();

**Comment by jakearchibald** [comment]
It isn't really a sleep state, the worker is terminated. When it's needed again, it's run again. If you need to do somewhen when the service worker runs, just write code in the root of the SW.
