### ISSUE TITLE
ServiceWorkers doesn't update in Chrome of subscribers after 24 hours (even after 5 days)

### ISSUE THREAD

**Issue by barvetal** [slightlyoff/ServiceWorker#930]
Hello,

We've deployed new verison of service worker to our server about 5 days ago.

We expected about 4 days ago that service worker would be updated by Chrome at our subscriber's PCs. But subscribers still have the old version of service worker (we see it because service worker sends requests to our server in previous format). So, service worker cached for about 5 days instead of 24 hours as specified in service worker specification. And service worker is not updated after 24 hours.

Which kind of additional information can I provide to you?

Thank you

**Comment by jakearchibald** [comment]
Closing this as it doesn't appear to be a spec issue, but I'll continue to help.

> Which kind of additional information can I provide to you?

A URL showing the problem. It could be something like caching headers, or a SW out of scope so updates don't get triggered, or the new SW is broken… without seeing any code I can only guess.
