### ISSUE TITLE
Create F2F agenda - 28-29 July 2016

### ISSUE THREAD

**Issue by jakearchibald** [slightlyoff/ServiceWorker#932]
https://github.com/w3c/WebPlatformWG/blob/gh-pages/meetings/16-07-28-29SW.md is the official place for the agenda, but I find it much easier to group-discuss these things in an issue.

Once things settle, I'll move the details into the official doc.

The structure last time seemed to work well, so I don't see any reason to change it.

# Day 1

* Hellos & updates/questions from vendors - This may be longer than usual as we have some new faces from Apple joining
* [Outstanding v1 issues](https://github.com/slightlyoff/ServiceWorker/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Version+1%22)
  * [#936 Should waitUntil() fast fail if a single extension promise rejects?](https://github.com/slightlyoff/ServiceWorker/issues/936)
  * [#935 should async waitUntil() work in .then() handler of promise passed to previous waitUntil()?](https://github.com/slightlyoff/ServiceWorker/issues/935)
  * [#931 Does accessing ExtendableEvent's extend lifetime promises race?](https://github.com/slightlyoff/ServiceWorker/issues/931)
  * [#922 Eliminate usage of entry and incumbent settings objects](https://github.com/slightlyoff/ServiceWorker/issues/922)
  * [#919 Need to review the algorithms for creating a new environment settings object](https://github.com/slightlyoff/ServiceWorker/issues/919)
  * [#918 Should WindowClient.navigate(url) navigate with "replacement enabled"?](https://github.com/slightlyoff/ServiceWorker/issues/918)
  * [#916 More clarity around waiting for an active worker to finish](https://github.com/slightlyoff/ServiceWorker/issues/916)
  * [#912 ServiceWorkerContainer spec lists `onerror` as an event handler](https://github.com/slightlyoff/ServiceWorker/issues/912)
  * [#905 should UA check for updates on navigate when there is no fetch event?](https://github.com/slightlyoff/ServiceWorker/issues/905)
  * [#896 clarify behavior when fetch event handler throws](https://github.com/slightlyoff/ServiceWorker/issues/896)
  * [#894 potential http cache issues with importScripts()](https://github.com/slightlyoff/ServiceWorker/issues/894)
  * [#893 consider fetching service worker scripts with no-cache by default](https://github.com/slightlyoff/ServiceWorker/issues/893)
  * [#892 Never fail for navigation requests](https://github.com/slightlyoff/ServiceWorker/issues/892)
  * [#890 clarify secure context requirements in Handle Fetch](https://github.com/slightlyoff/ServiceWorker/issues/890)
  * [#888 clarify that Clients.matchAll() only returns Window Client objects with active documents](https://github.com/slightlyoff/ServiceWorker/issues/888)
  * [#887 spec exactly how to order non-window Client objects](https://github.com/slightlyoff/ServiceWorker/issues/887)
  * [#884 addAll should resolve when the cache is fully & successfully written](https://github.com/slightlyoff/ServiceWorker/issues/884)
  * [#882 ServiceWorker lifetime and respondWith() with a user-constructed ReadableStream](https://github.com/slightlyoff/ServiceWorker/issues/882)
  * [#881 Move service worker spec into w3c](https://github.com/slightlyoff/ServiceWorker/issues/881) (decided)
  * [#879 Split the cache API into its own spec](https://github.com/slightlyoff/ServiceWorker/issues/879)
  * [#875 should FetchEvent.request.cache reflect non-fetch browser cache controls?](https://github.com/slightlyoff/ServiceWorker/issues/875) (decided)
  * [#873 Drop isReload](https://github.com/slightlyoff/ServiceWorker/issues/873) (decided)
  * [#870 Inconsistencies due to when clients are created](https://github.com/slightlyoff/ServiceWorker/issues/870)
  * [#856 why does Register algorithm step 5.3.1 check for an active worker?](https://github.com/slightlyoff/ServiceWorker/issues/856)
  * [#855 Unregister algorithm step 6.1 is no longer necessary](https://github.com/slightlyoff/ServiceWorker/issues/855)
  * [#850 FetchEvent.respondWith does something weird with the body of a response](https://github.com/slightlyoff/ServiceWorker/issues/850) (decided)
  * [#834 html no longer defines "referrer source"](https://github.com/slightlyoff/ServiceWorker/issues/834)
  * [#829 Resolve Job Promise can resolve jobs with an incorrect value](https://github.com/slightlyoff/ServiceWorker/issues/829)
  * [#816 ExtendableMessageEvent.source cannot be SameObject](https://github.com/slightlyoff/ServiceWorker/issues/816) (decided)
  * [#813 Should mixed content always be blocked?](https://github.com/slightlyoff/ServiceWorker/issues/813)
  * [#811 Should the active worker move to environment settings object?](https://github.com/slightlyoff/ServiceWorker/issues/811)
  * [#793 navigations that are not intercepted should still allow interception on further redirects](https://github.com/slightlyoff/ServiceWorker/issues/793) (decided)
  * [#777 spec behavior when ServiceWorkerContainer parent client is dead](https://github.com/slightlyoff/ServiceWorker/issues/777)
  * [#765 serviceworker for iframes with srcdoc](https://github.com/slightlyoff/ServiceWorker/issues/765) (decided)
  * [#732 Remove frameType, maybe add ancestorOrigins](https://github.com/slightlyoff/ServiceWorker/issues/732)
  * [#710 spec should be more explicit about accessing internal body on opaque Responses](https://github.com/slightlyoff/ServiceWorker/issues/710) (decided)
  * [#703 Receivers of ranged responses must ensure all ranges come from the same underlying resource](https://github.com/slightlyoff/ServiceWorker/issues/703) (decided)
  * [#564 OCSP fetches bypass service worker](https://github.com/slightlyoff/ServiceWorker/issues/564)

# Day 2

* Come up with the order we want to tackle the following…
* [Which APIs within SW trigger fetch events, and to which SW?](https://github.com/whatwg/fetch/issues/303)
* [Avoid exposing cross-origin sizes](https://github.com/whatwg/storage/issues/31)
* Overnight responses to yesterday's actions
* Foreign Fetch
* [Eliminating startup latency](https://github.com/slightlyoff/ServiceWorker/issues/920)
* [Multiple SW scopes](https://github.com/slightlyoff/ServiceWorker/issues/921)
* [Checking modules & importScripts as part of regular update checks](https://github.com/slightlyoff/ServiceWorker/issues/839)
* [Making it easier to copy requests](https://github.com/whatwg/fetch/issues/245)
* [Generating ranged requests from cache.match](https://github.com/slightlyoff/ServiceWorker/issues/913)
* [Exposing fragments cross-origin for subresources](https://github.com/slightlyoff/ServiceWorker/issues/910)
* [clientcontrolled event](https://github.com/slightlyoff/ServiceWorker/issues/886)
* [Reporting system like CSP](https://github.com/slightlyoff/ServiceWorker/issues/877)
* [Cache transactions](https://github.com/slightlyoff/ServiceWorker/issues/823)
* [Running multiple SWs at once](https://github.com/slightlyoff/ServiceWorker/issues/756)
* [Launching without the location bar via openWindow](https://github.com/slightlyoff/ServiceWorker/issues/720)

These are just my suggestions, they aren't complete, and are totally up for debate.

**Comment by wanderview** [comment]
Lets talk about https://github.com/whatwg/fetch/issues/303.

**Comment by mkruisselbrink** [comment]
We should probably also go thru the issues without milestones to make sure they shouldn't be v1 issues. But maybe it makes more sense for somebody to do that before the meeting.

**Comment by RReverser** [comment]
@jakearchibald @wanderview https://github.com/whatwg/fetch/issues/245 doesn't seem to be here? You mentioned on Twitter it will be likely discussed.

**Comment by inexorabletash** [comment]
I won't be attending, but a plea for https://github.com/whatwg/storage/issues/31 to get some attention.

**Comment by jakearchibald** [comment]
@mkruisselbrink done

**Comment by jakearchibald** [comment]
To future-me: here's the script for getting issue data in the format above:

```js
function getAllIssues(url) {
  const allIssues = [];

  return fetch(url).then(function processResponse(response) {
    const nextLink = response.headers.get('link').split(',').find(a => a.trim().endsWith('rel="next"'));
    const nextUrl = nextLink && nextLink.replace(/(^\s*<|>;.*$)/g, '');

    return response.json().then(data => {
      allIssues.push(...data);

      if (nextUrl) {
        return fetch(nextUrl).then(processResponse);
      }
      return allIssues;
    });
  });
}


getAllIssues('//api.github.com/repos/slightlyoff/ServiceWorker/issues?milestone=2').then(issues => {
  window.issueStr = issues.map(issue => {
    return `  * [#${issue.number} ${issue.title}](${issue.html_url})`;
  }).join('\n');
});
```

**Comment by jakearchibald** [comment]
We should look at how many SWs are using global state. WebKit are interested in launching multiple instances of the SW in the fetch process.

**Comment by jakearchibald** [comment]
F2F: We need to gather the use-cases, and find out how we can solve them. We need to avoid getting locked into one worker instance.

**Comment by jakearchibald** [comment]
F2F:

* Lots of developers aren't keen on this
* Sounds like something browsers can do, eg provide a button on the failure page "Retry without SW" (worded in a way that users understand). Or if it keeps failing, the browser could auto unregister the SW

**Comment by jakearchibald** [comment]
Thanks to everyone who attended, and especially @wanderview and Mozilla for hosting!
