### ISSUE TITLE
Why does CacheStorage have [SecureContext] but not Cache?

### ISSUE THREAD

**Issue by inexorabletash** [slightlyoff/ServiceWorker#941]
CC: @mikewest

The global `caches` attributes have `[SecureContext]` [(link)](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#self-caches) which makes sense - hide the entry points except in secure contexts.

But the interfaces are inconsistent. [CacheStorage](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache-storage) has `[SecureContext]` but [Cache](https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#cache) does not. This seems inconsistent.

Is this just an oversight in applying a fix for #687 ?

**Comment by mkruisselbrink** [comment]
That does look a bit inconsistent indeed. I wonder what would be preferred though with regard to SecureContext on interfaces. For security it doesn't really matter if these interfaces have [SecureContext] or not, as the only way to get access to instances that do things is via methods that are SecureContext only. But maybe for consistency and/or feature detection it might make sense to hide all the interfaces as well? Not sure. Similarly ServiceWorker and ServiceWorkerRegistration currently don't have [SecureContext] but ServiceWorkerContainer does...

**Comment by inexorabletash** [comment]
I can see wanting `[SecureContext]` on the interface if there's a constructor and therefore we should be consistent for types without constructors. Although not a technical requirement (so maybe not in http://heycam.github.io/webidl/#SecureContext) we should probably be consistent in the platform and document it somewhere. Hence pestering @mikewest :)

**Comment by mikewest** [comment]
If the interface doesn't do anything at all without being inside a secure context, then yeah, mark it up with `SecureContext`. If there's value to your feature to being exposed, then do it that way. We don't really have rigid rules yet; we'll have to learn together what makes sense.

**Comment by mikewest** [comment]
I'd personally suggest erring on the side of putting the attribute on too many things; we can always remove it later if it turned out to be overzealous. :)

**Comment by jakearchibald** [comment]
Yeah this is just an oversight I think

**Comment by jungkees** [comment]
> I can see wanting [SecureContext] on the interface if there's a constructor and therefore we should be consistent for types without constructors.

The reason was exactly that. I.e., the `Cache`, `ServiceWorker` and `ServiceWorkerRegistration` don't have a constructor and can be gotten only from the methods exposed with `[SecureContext]`.

> We don't really have rigid rules yet; we'll have to learn together what makes sense.

Are there any other such cases yet? I can do either way but would like to have some good rationale.

**Comment by annevk** [comment]
You can also get them from the global. Since that doesn't enable anything useful, you should prevent exposure there with `[SecureContext]`.

**Comment by jungkees** [comment]
They can't be gotten from a non-secure context's global, either. But it seems all agreed on putting it. I'll address it in that way.

**Comment by annevk** [comment]
They can, e.g., `window.Cache`. You need `[SecureContext]` to prevent that.

**Comment by jungkees** [comment]
Ah.. didn't know it's exposed even without a constructor.
