### ISSUE TITLE
Firefox buggy

### ISSUE THREAD

**Issue by hakuno** [slightlyoff/ServiceWorker#948]
Hey there!

My Firefox version 48 runs service workers. But, I've already noticed the Chrome sounds better.

Because Firefox just puts a new one cache version. And old cache versions are left. I can verify it by executing on console:

`caches.keys().then(function(cacheNames) { console.log(cacheNames) })`

They don't go away on Firefox. Even although Chrome works well.

And it's my activate event function below:

`self.addEventListener('activate', function(event) {`
`var cacheWhitelist = ['xxxxxxxx'];`
`  event.waitUntil(`
`    self.caches.keys().then(function(cacheNames) {`
`      return Promise.all(`
`        cacheNames.filter(function (cacheName) {`
`          return (cacheWhitelist.indexOf(cacheName) === -1);`
`        })`
`        .map(function (key) {`
`          return self.caches.delete(key);`
`        })`
`      );`
`    })`
`  );`
`});`

How could I make it works properly?
Thanks in advance.

**Comment by jdm** [comment]
You should probably file this in [Mozilla's bug tracker](https://bugzilla.mozilla.org/enter_bug.cgi?product=Core&component=DOM%3A%20Service%20Workers) instead, since it's about a particular implementation of this specification.

**Comment by NekR** [comment]
If you are going to file an issue on Mozilla's bug tracker, then please
leave the link to it here.

**Comment by NekR** [comment]
If you are going to file an issue on Mozilla's bug tracker, then please
also leave the link to it here.

**Comment by wanderview** [comment]
Are you sure the activate event is firing?  If you are used to chrome devtool's forced update feature, then you might be surprised firefox does not activate the new worker during page reload.  You either need to use skipWaiting() or close all controlled windows before the new worker will fully activate.

**Comment by hakuno** [comment]
@wanderview Yes, I guess it's not being fired. I did mention at here:
[Bug 1294216](https://bugzilla.mozilla.org/show_bug.cgi?id=1294216)

Maybe some has got any tip. I can clear the old caches manually. Thus I'd try to enforce an event binding to call the function.

Should not the "spec" rule all the browsers' behaviour smoothly? :confused: 

I'll check it out (tomorrow). I'm glad since then! Thanks.

**Comment by wanderview** [comment]
Ok, I responded there.

**Comment by hakuno** [comment]
All right.

I can't open the console, unless it's seen as tab in some way.

If I want to override this rule as you said, so those methods help me on it. The `skipWaiting` and `claim` works perfectly. Thank you so.
