### ISSUE TITLE
Caching strategy: resource caching

### ISSUE THREAD

**Issue by alecf** [slightlyoff/ServiceWorker#95]
This is just one of a number of bugs around APIs that ServiceWorker could provide. I'm filing separate ones for each idea so that pros/cons/musings can be recorded somewhere for each one.

---

In contrast / complement to #92 we could provide a way for the response data itself to be cached by the user agent. What this means is that the actual contents of the result of the fetch, cache, or any other arbitrarily created response gets stored in an upstream cache.

This might look something like:

```javascript
e.respondWith(fetch(url), { expires: "2 days" });
```

This very general meaning that any resource including software-generated responses would be cached.

This isn't mutually exclusive with #92, though the presence of both in the API could be confusing.

**Comment by jakearchibald** [comment]
This is counter to the design we ended up with, but in the future we can consider cache types that have some kind of auto-eviction mechanic.
