### ISSUE TITLE
"or its equivalent"

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#953]
I'm not sure referencing this language sometimes but not always is useful. Everything that's black-box indistinguishable is fair game after all. I'd rather we remove the callouts to this in the various algorithms as they just make the algorithms harder to read.

**Comment by jungkees** [comment]
Indeed. I've thought the same for a long time. I think this sentence in https://slightlyoff.github.io/ServiceWorker/spec/service_worker/#conformant-algorithms covers the requirement: "Conformance requirements phrased as algorithms or specific steps can be implemented in any manner, so long as the end result is equivalent." I'll remove them.
