### ISSUE TITLE
Match Service Worker Registration has broken matching algorithm

### ISSUE THREAD

**Issue by annevk** [slightlyoff/ServiceWorker#954]
_clientURL_ will always start with "https://". How can it ever match a scope that is apparently never parsed and stored as-is?

**Comment by mkruisselbrink** [comment]
What do you mean with "never parsed and stored as-is"? In the Set Registration algorithm the key in the scope to registration map is set to the serialization (as defined in the URL spec) of the scope URL. And several steps earlier in the Start Registration algorithm the scope string as passed to register is parsed into a URL.

**Comment by annevk** [comment]
Yeah, my bad.
