### ISSUE TITLE
Reliable way to detect if a fetch is for a new page

### ISSUE THREAD

**Issue by wheresrhys** [slightlyoff/ServiceWorker#958]
I'm looking for a reliable way to modify only requests for entire html pages. The only thing I've found which correlates with this is that `clientId: null` on the fetch event. Is this specced and a reliable method to use, or is there a better way to detect these sorts of fetches.

**Comment by wanderview** [comment]
There is a lot of discussion about client ID for navigations in #808.  We decided, I believe, to offer separate client IDs on the FetchEvent for:

1. The client that initiated the navigation
2. The client that is being replaced by the navigation
3. The client that is being created by the navigation

This has not been spec'd yet, but issue #817 is open for that.

@jakearchibald correct me if I got this wrong.

**Comment by wanderview** [comment]
> I'm looking for a reliable way to modify only requests for entire html pages.

To do this, though, you can in theory look at `evt.request.mode` and see if its set to `navigation`.  Also I believe other sites have looked at the `Accept` header to see if it contains `text/html` to do this in the past.

Does that help?

**Comment by wheresrhys** [comment]
Great thanks. I hadn't heard of request.mode=navigation. I was thinking about Accept headers too, but https://www.keithcirkel.co.uk/the-ups-and-downs-of-the-http-header/ suggests this would be very flaky.
